### ISSUE TITLE
NTR: death confirmed likely from covid

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#100]
Again....please word this as you please! This would be a 'unit' of our 'case type'

**Comment by cstoeckert** [comment]
We think this is an information term similar to diagnosis.

**Comment by cstoeckert** [comment]
define this as a clinical finding.

**Comment by SAK22** [comment]
Just checking, so the death itself is defined as a clinical finding? Or the 'case type' and death and positive cases etc will be children of this?

**Comment by cstoeckert** [comment]
Not the death itself but rather the finding of death which is a data item.
How is this?
'finding of death from COVID-19' (alternative term: 'death confirmed likely from COVID')
Definition: A clinical finding of a death that has been confirmed to be likely caused by COVID-19.'

**Comment by SAK22** [comment]
That sounds good. I would need one for positive cases too, shall I made a new NTR?

**Comment by cstoeckert** [comment]
Yes, please go ahead and make NTRs for other clinical findngs needed.
