### ISSUE TITLE
Create script to remove conflicts of annotation properties from imported terms

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#101]
For releases currently need to manually fix conflicting and redundant annotations that come from imported terms (due to the external ontologies). Would be nice to be able to fix with a script.

**Comment by zhengj2007** [comment]
Found solution using Robot command 'remove'. See tracker:
https://github.com/ontodev/robot/issues/762

Example for only keeping OBI terms in NIAID-GSC-BRC.owl:

robot remove --input NIAID-GSC-BRC.owl \
    --base-iri 'http://purl.obolibrary.org/obo/OBI_' \
    --axioms external \
    --preserve-structure false \
    --trim false \
    --output NIAID-GSC-BRC_obi.owl

We need make sure all removed external terms imported in appropriate files as well.
