### ISSUE TITLE
NTR for count of entomology collections 

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#103]
Needed for dataset classifications.

**Comment by johnwjudkins** [comment]
Label: number of entomology collections
Definition: A count of collections of specimens that have only arthropods as their members.
Parent: count
Subclass axiom: 'is about' some ('collection of specimens' and 'has member' only Arthropoda)

**Comment by cstoeckert** [comment]
Looks good. Would be nice to include an example of usage like "Number of mosquito collections in an survey dataset."
