### ISSUE TITLE
'Dog Breed' as child of Eukaryota

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#104]
'Dog Breed' NCIT_C53693 is in microbiome.owl and is a child of Eukaryota in VEuPath. I don't think this fits because organism classes have organisms as instances, and an instance of dog breed is not a dog. This term might make more sense as an information content entity (similar to GENEPIO importing 'species' from NCBITaxon as a data item). I suppose the IRI could stay the same if we do this. Another option would be to replace this term with the NCBITaxon term for dog.

**Comment by cstoeckert** [comment]
Dog breed is not used anymore so should not import anymore from NCIT.
