### ISSUE TITLE
NTRs for organism terms in PopBio

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#105]
ID | label | parent
-- | -- | --
EUPATH:0043067 | Psorophora johnstonii | Psorophora
EUPATH:0043068 | Psorophora mathesoni | Psorophora
EUPATH:0043069 | Psorophora mexicana | Psorophora
EUPATH:0043070 | Toxorhynchites rutilus rutilus | Toxorhynchites rutilus
EUPATH:0043071 | Aedes atlanticus-tormentor morphological group | Ochlerotatus (subgenus)
EUPATH:0043072 | Aedes fijiensis | Finlaya
EUPATH:0043073 | Aedes hodgkini | Ochlerotatus (subgenus)
EUPATH:0043074 | Aedes hokkaidensis | Ochlerotatus (subgenus)
EUPATH:0043075 | Aedes idahoensis | Ochlerotatus (subgenus)
~~EUPATH:0043076~~ | ~~Aedes juppi~~ | ~~Ochlerotatus (subgenus)~~
~~EUPATH:0043077~~ | ~~Aedes ledgeri~~ | ~~Stegomyia~~
EUPATH:0043078 | Aedes mathesoni | Aedes mathesoni complex
EUPATH:0043079 | Aedes mathesoni complex | Ochlerotatus (subgenus)
EUPATH:0043080 | Aedes subdentatus | Aedimorphus
EUPATH:0043081 | Aedes tricholabis | Aedimorphus
EUPATH:0043082 | Aedes vexans arabiensis | Aedes vexans sensu lato
EUPATH:0043083 | Aedes vexans sensu lato | Aedimorphus
EUPATH:0043084 | Aedes vexans vexans | Aedes vexans sensu lato
EUPATH:0043085 | Aedes washinoi | Ochlerotatus (subgenus)
EUPATH:0043086 | Anopheles barberi | Anopheles (subgenus)
EUPATH:0043087 | Anopheles culicifacies AD subgroup | culicifacies species complex
EUPATH:0043088 | Anopheles distinctus | Cellia
EUPATH:0043089 | Anopheles flavicosta | Cellia
~~EUPATH:0043090~~ | ~~Anopheles franciscanus~~ | ~~Anopheles (subgenus)~~
EUPATH:0043091 | Anopheles georgianus | Anopheles (subgenus)
EUPATH:0043092 | Anopheles listeri | Cellia
EUPATH:0043093 | Anopheles natalensis | Cellia
EUPATH:0043094 | Anopheles perplexens | Anopheles (subgenus)
EUPATH:0043095 | Anopheles sinensis sensu lato | Anopheles (subgenus)
EUPATH:0043096 | Anopheles umbrosus | umbrosus group
~~EUPATH:0043097~~ | ~~Culex aurantapex~~ | ~~Culex (subgenus)~~
EUPATH:0043098 | Culex chorleyi | Culex (subgenus)
EUPATH:0043099 | Culex cinerellus | Culiciomyia
EUPATH:0043100 | Culex cuyanus | Culex (subgenus)
~~EUPATH:0043101~~ | ~~Culex inconspicuosus~~ | ~~Eumelanomyia~~
EUPATH:0043102 | Culex lineata | Culex (genus)
EUPATH:0043103 | Culex peringueyi | Maillotia
~~EUPATH:0043104~~ | ~~Culex rubinotus~~ | ~~Eumelanomyia~~
EUPATH:0043105 | Culex salisburiensis | Maillotia
~~EUPATH:0043106~~ | ~~Culex stigmatosoma~~ | ~~Culex (subgenus)~~
EUPATH:0043107 | Culex trifoliatus | Culex (subgenus)
~~EUPATH:0043108~~ | ~~Mimomyia hispida~~ | ~~Mimomyia (subgenus)~~
~~EUPATH:0043109~~ | ~~Mimomyia mediolineata~~ | ~~Mimomyia (subgenus)~~
~~EUPATH:0043110~~ | ~~Mimomyia mimomyiaformis~~ | ~~Mimomyia (subgenus)~~
EUPATH:0043111 | Sergentomyia theodori | Sergentomyia (subgenus)
EUPATH:0043112 | Uranotaenia hopkinsi | Uranotaenia (subgenus)
~~EUPATH:0043113~~ | ~~Uranotaenia mashonaensis~~ | ~~Pseudoficalbia~~
EUPATH:0043114 | Wyeomyia haynei | Wyeomyia

(edited to distinguish the subgenus and genus that are both named Culex)

**Comment by cstoeckert** [comment]
Include an explanation in editor notes why we're not using NCBI taxon IDs (don't exist and represent unusual groups that wouldn't be submitted.)

**Comment by johnwjudkins** [comment]
@SAK22 @bobular I think we discussed that some of these should not be submitted to NCBI because they represent a taxonomic level that NCBI does not include. Did I understand that correctly? If so, could one of you please point out which terms in this list should not be submitted?

**Comment by johnwjudkins** [comment]
In release. Leaving open in case we want to submit these to NCBI.

**Comment by johnwjudkins** [comment]
@SAK22 @bobular Following up on previous question in this thread. The taxon names in the table above (the ones that aren't struck out) have VEuPath IDs, not NCBITaxon. Should any of these be submitted to NCBI?

**Comment by SAK22** [comment]
This is tricky @johnwjudkins I would say do not request Anopheles culicifacies AD subgroup or Aedes atlanticus-tormentor morphological group and let me get back to you on the others after some discussion with @bobular . It is so tricky as you look in one inventory, it places them in one place, look at another it is elsewhere or does not exist at all! Mosquitoes seem to move around their tree a lot and sometimes change names along the way!

**Comment by zhengj2007** [comment]
Can we close it?

**Comment by johnwjudkins** [comment]
Replaced 3 IRIs in original post:

Taxon | Old IRI | Replacement IRI
-- | -- | --
Culex inconspicuosus | http://purl.obolibrary.org/obo/EUPATH_0043101 | http://purl.obolibrary.org/obo/NCBITaxon_2918769
Mimomyia hispida | http://purl.obolibrary.org/obo/EUPATH_0043108 | http://purl.obolibrary.org/obo/NCBITaxon_2918771
Uranotaenia mashonaensis | http://purl.obolibrary.org/obo/EUPATH_0043113 | http://purl.obolibrary.org/obo/NCBITaxon_487103

**Comment by bobular** [comment]
Thanks @johnwjudkins - I've updated these in the (VB->VEuPath migration) mapping spreadsheet.

I had a quick hunt through the tickets in this repo and didn't find any other new-to-NCBI species that we previously had as EUPATH_nnnnnn - do you know of any others?

**Comment by zhengj2007** [comment]
@bobular I did not find 'Culex inconspicuosus' in the popbio.owl file which including both popbio variables and values. Is it the missing one? Should I add it in?

**Comment by bobular** [comment]
Hi @zhengj2007 - I wasn't thinking about the popbio.owl file actually. Thanks for the heads-up. I'm not sure those species terms are relevant for the next data loading, but if they are I'll know where to look.

**Comment by zhengj2007** [comment]
Hi @bobular, we worked on the terms for harmonization work led by Chris. We mapped all popBio used terms to OBO Foundry ones. At that time, we assigned organism terms with EuPathDB IDs when they are not available in the NCBITaxon. John found some of them in the NCBITaxon lately. He replaced the term EuPathDB ID with NCBITaxon ones and deprecated the VEuPathDB ones in the VEuPathDB ontology. The popBio.owl file was generated based on the terms you provided including the organism terms. So, I updated the organism IDs in the popBio.owl as well since we should not use the VEuPathDB IDs anymore. However, I didn't find 'Culex inconspicuosus' in the popbio.owl. So, it could be the term not needed anymore. If it is used, we need to update its ID since the term http://purl.obolibrary.org/obo/EUPATH_0043101 will be deprecated in the ontology.

**Comment by bobular** [comment]
Hi @zhengj2007 

Thanks and sorry I missed this until now.

It seems that 'Culex inconspicuosus' isn't in the current large-ish chunk of data that we are using for migration and EDA data loading testing, so no urgent action is needed.

There will be a bunch of species and other terms to add to both the VEuPath ontology and popbio.owl when we move from testing to an actual production migration (Chado to EDA) but we will try to deal with those at the same time. 

Thanks for flagging this up!
