### ISSUE TITLE
Non-OBO children of 'Phenotypic abnormality'

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#107]
We are currently using externalByHand.owl to import the following classes from SNOMED, EFO, or MEDDRA as children of 'Phenotypic abnormality':

Animal bite
Bacterial infection of skin
Burn
Foreign body
Fracture
injury
Pyrexia of unknown origin
Soft tissue injury

I don't see any of these in our projects - do we still need them? If so, most of these can now be replaced with classes from HP or DOID.

**Comment by zhengj2007** [comment]
The terms were added for PRISM project several years ago. The ontology terms are required for all variables and values. Since they are not used by any clinEpi projects, I think you can remove them from import now.

**Comment by cstoeckert** [comment]
Done
