### ISSUE TITLE
NTR: needed COVID data item terms

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#108]
New term for positive covid case please

**Comment by cstoeckert** [comment]
'finding of testing positive for COVID-19' (alternative term: 'positive COVID case')
Definition: A clinical finding of testing positive for coronavirus indicating having COVID-19.'

Note that CIDO has http://purl.obolibrary.org/obo/OPMI_0000435 'positive COVID-19 diagnosis'

**Comment by SAK22** [comment]
Would I be able to use this OPMI ontology so I can add it to my datasets? Or is it best to wait for a veupath now? Apologies, I am not sure of best protocol for this!

**Comment by cstoeckert** [comment]
The following clinical data items are needed and will be made subclasses of http://purl.obolibrary.org/obo/OGMS_0000123:
positive cases, 
negative cases, 
number of tests, 
people in hospital with covid, 
ventilators used by covid patients, 
deaths in care homes, 
covid calls, 
online covid enquiries, 
Total number of lab-confirmed hospitalized patients under respiratory support at the moment of reporting (prevalence),
Total number of lab-confirmed hospitalized patients on ECMO at the moment of reporting (prevalence), 
total in ICU

@SAK22 can you provide initial definitions/ descriptions of each? Thanks!

**Comment by SAK22** [comment]
positive case: The representation of a positive conclusion of a diagnostic process for the COVID-19 coronavirus disease - http://purl.obolibrary.org/obo/OPMI_0000435
negative case: The representation of a negative conclusion of a diagnostic process for the COVID-19 coronavirus disease http://purl.obolibrary.org/obo/CIDO_0000437
number of tests : The representation of the number of COVID-19 coronavirus diagnostic tests
people in hospital with covid: ?? my thoughts and Bobs, we add the hospital as a 'context' as an extra column to the data then these can be positive cases??
ventilators used by covid patients: The representation of the number of ventilators in use by COVID-19 coronavirus patients
deaths in care homes: ?? again we can use deaths and add a context column?
covid calls: The number of calls received by the NHS regarding covid?
online covid enquires: Representation of online NHS 111 covid enquiries ? Running out of steam on definitions!

------- feel like these are less important to add??---------
Total number of lab-confirmed hospitalized patients under respiratory support at the moment of reporting (prevalence)? would this be the same as ventilators used by covid patients?
Total number of lab-confirmed hospitalized patients on ECMO at the moment of reporting (prevalence): ??

**Comment by bobular** [comment]
SAK/BM discussed today and made some refinements+comments

**positive case**: The representation of a positive conclusion of a diagnostic process for the COVID-19 coronavirus disease - http://purl.obolibrary.org/obo/OPMI_0000435

**negative case**: The representation of a negative conclusion of a diagnostic process for the COVID-19 coronavirus disease http://purl.obolibrary.org/obo/CIDO_0000437

**number of tests** : this attempted to capture total number of tests performed but as long as we are able to represent positive cases and negative cases as separate data records then the total will be available as the sum of these (e.g. viewable on the map as a pie chart of pos + neg)  (Note to Bob/Sarah: do we need to flag records as belong to a dataset with negative counts? This would be a great filter in the map. Use a constant_value column for this...?)

**people in hospital with covid**: SAK/BM we'll add the hospital as a 'context' as an extra column to the data then these can be regular positive case - will get back to you on context terms (e.g. care home, hospital, private home, prison, university, school etc)

**covid calls**:  a patient making contact with a telephone Covid helpline (needs more thought - what about the outcome/diagnosis made on the call?)
**online covid enquires**: a patient making contact with an online Covid helpline


These three need further thought, as they count something different from individual patient-cases (same person is often counted on consecutive days) - maybe ignore this data.  New patient admitted to ICU or put on a machine would be more comparable perhaps?
- ventilators used by covid patients 
- Total number of lab-confirmed hospitalized patients under respiratory support at the moment of reporting (prevalence)? would this be the same as ventilators used by covid patients?
- Total number of lab-confirmed hospitalized patients on ECMO at the moment of reporting (prevalence): ??

**Comment by cstoeckert** [comment]
Will add positive COVID, negative COVID, and COVID deaths for now.

**Comment by cstoeckert** [comment]
see https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/100 for COVID death term

**Comment by johnwjudkins** [comment]
In release; closing.
