### ISSUE TITLE
NTR: collection site altitude 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#111]
Firstly, I have chosen these EUPATH ontology terms for the collection site lat/long variables

longitude coordinate measurement datum OBI:0001621
latitude coordinate measurement datum OBI:0001620

Are these OK?

But what do I choose for altitude?

It's a very sparsely populated field, but I think we could continue to handle it.

**Comment by cstoeckert** [comment]
Will submit to OBI a NTR for altitude measurement datum.
A length measurement datum between a point at sea or ground level and some point above it.

**Comment by cstoeckert** [comment]
This has been added to OBI and has ID OBI:0002983
