### ISSUE TITLE
NTR: chlorthion

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#113]
Not sure how this escaped the mass CHEBIfication of the insecticides, but it remains (with just two data points from 1976 using it...)

MIRO:10000211 | chlorthion

Doesn't appear to be in CHEBI.  Could we have a EUPATH term please?  No need to submit to CHEBI as we don't expect more data.

More info here
https://pubchem.ncbi.nlm.nih.gov/compound/Chlorthion

Looks like nasty stuff (though probably all insecticides are)

**Comment by johnwjudkins** [comment]
I can make a new term under 'organophosphate insecticide' using the pubchem info.

**Comment by johnwjudkins** [comment]
As with the new organism terms I added, I didn't give this term a definition, but I made a note that I added the term to VEuPath because it is not in ChEBI. However, it inherits the insecticide role from its parent.

**Comment by cstoeckert** [comment]
Let's submit to ChEBI.

**Comment by Achchuthan** [comment]
I have made the submission to ChEBi. They have automatically assigned ChEBI identifier CHEBI:167184 for chlorthion. ChEBI curator will now review the submission and make final decision.

**Comment by Achchuthan** [comment]
This ChEBI term has now been curated: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:167184

**Comment by Achchuthan** [comment]
Chris, I have now assigned this issue back to you as the new term is now available in ChEBI.

**Comment by cstoeckert** [comment]
John please import in next release.
