### ISSUE TITLE
NTR: well net for arthropod immatures

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#114]
In row 82 of the master sheet, there is some discussion about this term not being needed.

Actually it is needed (it's there in the database and on the map).

many thanks,
Bob

**Comment by johnwjudkins** [comment]
How about this for a definition:

A device that is designed for the collection of arthropod larvae or pupae from water and consists of a conical net.

By the way, is this term equivalent to id: VSMO:0001481 collection net for immatures?

**Comment by SAK22** [comment]
I think this is a good definition! I don't know if to show it is different from the VSMO term, which is very similar but different in the fact that the VSMO term the net is on a handle and you sweep through the water. The well net is on a string and dropped down the well to dip just below the surface water in the well.

**Comment by johnwjudkins** [comment]
Added term. Closing.
