### ISSUE TITLE
NTR: data items for pathogen species, blood meal host species, 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#116]
My current plan to move pathogen assay data (insect samples assayed for a small number of pathogens by ELISA or PCR) and blood meal host identification data (similar idea but for around ~100 species of blood meal host) into VEuPath is *NOT* with a variable for each pathogen or host species (although we can try that if my proposal doesn't work out).

For this approach each assay will have a number of characteristics/properties/variables. One assay per organism detection goal.  Firstly for the pathogen infection assays:

1. pathogen organism (EUPATH_0000756) - value is a taxonomy term
2. presence of pathogen (EUPATH_0010889) - value is boolean
3. prevalence of pathogen (???) - value is a prevalence - units are usually percent

1 above is an existing term, but it's not a data item, so maybe we need a new term?

Then for the blood meal host data, it's very similar:

A. blood meal host organism
B. presence of blood meal host organism 
C. prevalence of blood meal host organism (this is called 'host blood index' in the community, value in percent)

For the blood meal data we're a bit less concerned about collecting negative results, so we could negotiate the need for B.

**Comment by cstoeckert** [comment]
To clarify, request is for potentially 4 new terms:
prevalence of pathogen - data item
blood meal host organism - organism with role 'blood meal source role'
presence of blood meal host organism - data item (boolean)
prevalence of blood meal host organism (e.g., % of mosquitoes that have human blood as a meal) - data item

**Comment by cstoeckert** [comment]
@bobular @SAK22 I've posted proposed labels, definitions, and examples of usage in the associated OBI tracker. https://github.com/obi-ontology/obi/issues/1288
Can you review to see if OK? Thanks.

**Comment by SAK22** [comment]
@cstoeckert I will look at this now and then confirm with @bobular his thoughts too.

**Comment by cstoeckert** [comment]
These have been added to OBI and will be in the upcoming release.
OBI_0002992 prevalence of pathogen in specimens
OBI_0002993 prevalence of blood meal specimens from a host organism
OBI_0002994 presence of blood from host organism in blood meal specimen
OBI_0002995 blood meal source organism
OBI_0002996 blood meal source role

https://github.com/obi-ontology/obi/pull/1316
