### ISSUE TITLE
NTR: Anopheles gambiae species complex chromosomal inversion data items

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#117]
Analogous to the Kdr L1014F-style variables we made recently I would like to represent chromosomal inversion genotypes in the same way: one assay has multiple variables to describe the genotype. 

These are the inversions we need - one on the 2L chromosome arm, and the others on 2R.

-  2La https://legacy.vectorbase.org/Anopheles_gambiae/StructuralVariation/Explore?sv=2La;svf=1;vdb=variation
-  2Rb https://legacy.vectorbase.org/Anopheles_gambiae/StructuralVariation/Explore?sv=2Rb;svf=1;vdb=variation
-  2Rc https://legacy.vectorbase.org/Anopheles_gambiae/StructuralVariation/Explore?sv=2Rc;svf=1;vdb=variation
-  2Rd https://legacy.vectorbase.org/Anopheles_gambiae/StructuralVariation/Explore?sv=2Rd;svf=1;vdb=variation
-  2Rj https://legacy.vectorbase.org/Anopheles_gambiae/StructuralVariation/Explore?sv=2Rj;svf=1;vdb=variation
-  2Ru https://legacy.vectorbase.org/Anopheles_gambiae/StructuralVariation/Explore?sv=2Ru;svf=1;vdb=variation
-  2Rk Not in VectorBase Ensembl

There are some existing ontology terms out there, e.g. in IDOMAL/MIRO
https://www.ebi.ac.uk/ols/ontologies/idomal/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMIRO_30000074&viewMode=All&siblings=true
But these don't have definitions...  however, the Ensembl genome browser links above provide reasonable information, including approx chromosomal locations.

The variables will store an integer number of copies of the inverted form, so 0, 1, or 2 (because the mosquito is diploid), so a label for the variables could be something like "Number of copies of inverted allele of 2La chromosomal inversion" - though let's aim for something much much shorter!

**Comment by cstoeckert** [comment]
Number of copies of inverted allele of 2La chromosomal inversion seems like a good start for a definition! 2La seems restricted to a limited number of species so that should be included. If these are measurement datums then the definition could be: "A measurement datum of the number of copies of the inverted allele of chromosome 2La in Anopheles gambiae."
The label then could be '2La Anopheles gambiae chromosomal inversion count'

**Comment by cstoeckert** [comment]
A measurement datum of the number of copies of the inverted allele of chromosome 2La in Anopheles gambiae complex where a refers to a region defined in X."
Provide a definition source: Based on some publication or GenBank record?

**Comment by bobular** [comment]
Hi @cstoeckert 
I'm bumping this ticket, since it's relevant to the one remaining major "TO DO" in the popbio migration process.

Looks like we needed some publications or other formal definition source.  Legacy VB Ensembl browser is down but hopefully I can find the inversion definitions on Ensembl Metazoa...

I found/downloaded/attached here the GFF-like file that defines the chromosomal locations of the inversion boundaries

[anopheles_gambiae_structural_variations.gvf.gz](https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/files/6507906/anopheles_gambiae_structural_variations.gvf.gz)

Sadly that file doesn't contain PubMed IDs - just publication titles.  I will try to track them down...

### 2La
Sharakhov, I.V., White, B.J., Sharakhova, M.V., Kayondo, J., Lobo, N.F., Santolamazza, F., Della Torre, A., Simard, F., Collins, F.H. and Besansky, N.J., 2006. Breakpoint structure reveals the unique origin of an interspecific chromosomal inversion (2La) in the Anopheles gambiae complex. Proceedings of the National Academy of Sciences, 103(16), pp.6258-6262.
PMID: 16606844

### 2Rj
Coulibaly, M.B., Lobo, N.F., Fitzpatrick, M.C., Kern, M., Grushko, O., Thaner, D.V., Traoré, S.F., Collins, F.H. and Besansky, N.J., 2007. Segmental Duplication Implicated in the Genesis of Inversion 2 Rj of Anopheles gambiae. PLoS One, 2(9), p.e849.
PMID: https://www.ncbi.nlm.nih.gov/pubmed/17786220

### 2Rb
Lobo, N.F., Sangaré, D.M., Regier, A.A., Reidenbach, K.R., Bretz, D.A., Sharakhova, M.V., Emrich, S.J., Traore, S.F., Costantini, C., Besansky, N.J. and Collins, F.H., 2010. Breakpoint structure of the Anopheles gambiae 2R b chromosomal inversion. Malaria journal, 9(1), pp.1-9.
PMID: https://pubmed.ncbi.nlm.nih.gov/20974007/

### 2Rc, 2Ru
White, B.J., Cheng, C., Sangaré, D., Lobo, N.F., Collins, F.H. and Besansky, N.J., 2009. The population genomics of trans-specific inversion polymorphisms in Anopheles gambiae. Genetics, 183(1), pp.275-288.
PMID: https://pubmed.ncbi.nlm.nih.gov/19581444/

### 2Rd
George, P., Sharakhova, M.V. and Sharakhov, I.V., 2010. High‐resolution cytogenetic map for the African malaria vector Anopheles gambiae. Insect molecular biology, 19(5), pp.675-682.
PMID: https://pubmed.ncbi.nlm.nih.gov/20609021/

**Comment by bobular** [comment]
### 2Rk

I don't think we have chromosomal coordinates for it, but it's literature reference is this:
https://pubmed.ncbi.nlm.nih.gov/12364623/

**Comment by cstoeckert** [comment]
'2La Anopheles gambiae complex chromosomal inversion count'
A measurement datum of the number of copies of the interspecific chromosomal inversion (2La) in Anopheles gambiae complex.
Editor note: 2La is described in: Sharakhov, I.V., White, B.J., Sharakhova, M.V., Kayondo, J., Lobo, N.F., Santolamazza, F., Della Torre, A., Simard, F., Collins, F.H. and Besansky, N.J., 2006. Breakpoint structure reveals the unique origin of an interspecific chromosomal inversion (2La) in the Anopheles gambiae complex. Proceedings of the National Academy of Sciences, 103(16), pp.6258-6262.PMID: 16606844

'2Rj Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the inversion 2Rj in Anopheles gambiae.
Editor note: 2Rj is described in: Coulibaly, M.B., Lobo, N.F., Fitzpatrick, M.C., Kern, M., Grushko, O., Thaner, D.V., Traoré, S.F., Collins, F.H. and Besansky, N.J., 2007. Segmental Duplication Implicated in the Genesis of Inversion 2 Rj of Anopheles gambiae. PLoS One, 2(9), p.e849. PMID:17786220

and so on.

**Comment by cstoeckert** [comment]
Here are the others:
'2Rb Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the chromosomal inversion 2Rb in Anopheles gambiae.
Editor note: 2Rb is described in: Lobo, N.F., Sangaré, D.M., Regier, A.A., Reidenbach, K.R., Bretz, D.A., Sharakhova, M.V., Emrich, S.J., Traore, S.F., Costantini, C., Besansky, N.J. and Collins, F.H., 2010. Breakpoint structure of the Anopheles gambiae 2R b chromosomal inversion. Malaria journal, 9(1), pp.1-9. PMID:20974007

'2Rc Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the trans-specific inversion 2Rc in Anopheles gambiae.
Editor note: 2Rc is described in: White, B.J., Cheng, C., Sangaré, D., Lobo, N.F., Collins, F.H. and Besansky, N.J., 2009. The population genomics of trans-specific inversion polymorphisms in Anopheles gambiae. Genetics, 183(1), pp.275-288. PMID:19581444

'2Ru Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the trans-specific inversion 2Ru in Anopheles gambiae.
Editor note: 2Ru is described in: White, B.J., Cheng, C., Sangaré, D., Lobo, N.F., Collins, F.H. and Besansky, N.J., 2009. The population genomics of trans-specific inversion polymorphisms in Anopheles gambiae. Genetics, 183(1), pp.275-288. PMID:19581444

'2Rd Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the chromosomal inversion 2Rd in Anopheles gambiae.
Editor note: 2Rj is described in: George, P., Sharakhova, M.V. and Sharakhov, I.V., 2010. High‐resolution cytogenetic map for the African malaria vector Anopheles gambiae. Insect molecular biology, 19(5), pp.675-682. PMID:20609021

'2Rk Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the chromosomal inversion 2Rk in Anopheles gambiae.
Editor note: 2Rk is described in:  Mario Coluzzi, Adriana Sabatini, Alessandra della Torre, Maria Angela Di Deco, Vincenzo Petrarca. A polytene chromosome analysis of the Anopheles gambiae species complex. PMID: 12364623

@bobular @SAK22 Please review and add any additional needed info in the Editor note. Thanks!

**Comment by cstoeckert** [comment]
We will assign IDs you can use in the reservation sheet and put them in once confirmed.

**Comment by bobular** [comment]
I still have to provide the extra info for the editor note. Haven't
forgotten!

**Comment by bobular** [comment]
2La Anopheles gambiae complex chromosomal inversion count'
A measurement datum of the number of copies of the interspecific chromosomal inversion (2La) in Anopheles gambiae complex.
Editor note: 2La is located on chromosome arm 2L:20524058-42165532 (approximate location in the AgamP3 assembly; GenBank: GCF_000005575.2) as described in: Sharakhov, I.V., White, B.J., Sharakhova, M.V., Kayondo, J., Lobo, N.F., Santolamazza, F., Della Torre, A., Simard, F., Collins, F.H. and Besansky, N.J., 2006. Breakpoint structure reveals the unique origin of an interspecific chromosomal inversion (2La) in the Anopheles gambiae complex. Proceedings of the National Academy of Sciences, 103(16), pp.6258-6262. PMID: 16606844

'2Rj Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the inversion 2Rj in Anopheles gambiae.
Editor note: 2Rj is located on chromosome arm 2R:3656857-14459087 (location in the AgamP3 assembly; GenBank: GCF_000005575.2) as described in: Coulibaly, M.B., Lobo, N.F., Fitzpatrick, M.C., Kern, M., Grushko, O., Thaner, D.V., Traoré, S.F., Collins, F.H. and Besansky, N.J., 2007. Segmental Duplication Implicated in the Genesis of Inversion 2 Rj of Anopheles gambiae. PLoS One, 2(9), p.e849. PMID:17786220

'2Rb Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the chromosomal inversion 2Rb in Anopheles gambiae.
Editor note: 2Rb is located on chromosome arm 2R:19023925-26758676 (location in the AgamP3 assembly; GenBank: GCF_000005575.2) as described in: Lobo, N.F., Sangaré, D.M., Regier, A.A., Reidenbach, K.R., Bretz, D.A., Sharakhova, M.V., Emrich, S.J., Traore, S.F., Costantini, C., Besansky, N.J. and Collins, F.H., 2010. Breakpoint structure of the Anopheles gambiae 2R b chromosomal inversion. Malaria journal, 9(1), pp.1-9. PMID:20974007

'2Rc Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the trans-specific inversion 2Rc in Anopheles gambiae.
Editor note: 2Rc is located on chromosome arm 2R:26780000-31450000 (location in the AgamP3 assembly; GenBank: GCF_000005575.2) as described in: White, B.J., Cheng, C., Sangaré, D., Lobo, N.F., Collins, F.H. and Besansky, N.J., 2009. The population genomics of trans-specific inversion polymorphisms in Anopheles gambiae. Genetics, 183(1), pp.275-288. PMID:19581444

'2Ru Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the trans-specific inversion 2Ru in Anopheles gambiae.
Editor note: 2Ru is located on chromosome arm 2R:31480000-35500000 (location in the AgamP3 assembly; GenBank: GCF_000005575.2) as described in: White, B.J., Cheng, C., Sangaré, D., Lobo, N.F., Collins, F.H. and Besansky, N.J., 2009. The population genomics of trans-specific inversion polymorphisms in Anopheles gambiae. Genetics, 183(1), pp.275-288. PMID:19581444

'2Rd Anopheles gambiae chromosomal inversion count'
A measurement datum of the number of copies of the chromosomal inversion 2Rd in Anopheles gambiae.
Editor note: 2Rj is located on chromosome arm 2R:31480000-42600000 (location in the AgamP3 assembly; GenBank: GCF_000005575.2) as described in: George, P., Sharakhova, M.V. and Sharakhov, I.V., 2010. High‐resolution cytogenetic map for the African malaria vector Anopheles gambiae. Insect molecular biology, 19(5), pp.675-682. PMID:20609021

2Rk - no change (we don't have coordinates for it)

**Comment by cstoeckert** [comment]
@johnwjudkins Can you add these to VEuPathDB ontology? Thanks!

**Comment by johnwjudkins** [comment]
For consistency with other count terms, I'll make labels with 'number of...' instead of '...count', and I'll make these children of 'count' and adjust the definition accordingly.
