### ISSUE TITLE
NTR:specimen collection time post disease onset

### ISSUE THREAD

**Issue by PhiBabs935** [VEuPathDB-ontology/VEuPathDB-ontology#118]
Hi,
This is a potential term request. It may not be needed, it depends. 

I am looking to replace the following term originally created for the Influenza Ontology (as it is not specific to influenza) with a term from an external ontology:

_post disease onset sample collection period_ [FLU:0001015] =def The time period that comprises the sample collection period when the sample was collected following the disease onset. 

I replaced that term with the following new term for FLU: 

_specimen collection time post disease onset_ =def A specimen collection time measurement datum that is the measure of 
a time when specimens are collected after the onset of disease in a host.

As you can see, I modeled this newer term on EUPATH's:

_specimen collection time post infection_ =def A specimen collection time measurement datum that is the measure of a 
time when specimens are collected after an infection starts

The reason I thought this term would be needed is that we can distinguish between the onset of infection and the onset of disease/illness/symptoms (which is also in line with the Infectious Disease Ontology/OGMS framework that FLU is part of). So it seemed these would be different measurement datums. But I wasn't absolutely sure.

**Comment by cstoeckert** [comment]
Thanks for raising this. I agree that infections are different from diseases. For terms useful outside of VEuPathDB we also want to submit them to a more general ontology. How about we submit them to OBI since these are specimen collection related measurements?

**Comment by PhiBabs935** [comment]
That sounds good to me, I plan on submitting some other FLU terms to OBI anyway.

So the idea is to submit both of the terms to OBI right?

**Comment by cstoeckert** [comment]
Discussed as part of https://github.com/obi-ontology/obi/issues/1286

**Comment by johnwjudkins** [comment]
New term merged into OBI. Closing.
