### ISSUE TITLE
typo: human study subject identifier

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#12]
subjet -> subject
http://purl.obolibrary.org/obo/EUPATH_0000095

**Comment by zhengj2007** [comment]
fixed on commit: https://github.com/EuPath-ontology/EuPath-ontology/commit/d6d2e0a93a0a847d14477698296a96b92822678d

**Comment by zhengj2007** [comment]
Fixed.
