### ISSUE TITLE
Plan for 'may treat' non-RO relation

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#121]
We have one non-RO relation: http://purl.obolibrary.org/obo/EUPATH_0000060
This is not used much but should consider discussing this further with OGMS. Not a high priority.
May even deprecate.

**Comment by johnwjudkins** [comment]
Could we replace it in favor of http://purl.obolibrary.org/obo/RO_0002606? This definition has the phrase "capable of some activity that negative regulates or decreases the magnitude of", which could be understood the same way as the phrase "may treat".

**Comment by cstoeckert** [comment]
I agree that 'is substance that treats' from RO can be used in place of 'may treat' in EUPATH.

**Comment by zhengj2007** [comment]
The relation is added for grouping drug products in ClinEpi terminologies in early development of VEuPathDB ontology. The classification is not used any more. I'd prefer to deprecate the relation. But we can contact DRON developers for this kind of classification and decide what relation should be used and import the logical axioms to VEuPathDB ontology if need.

**Comment by cstoeckert** [comment]
Have antimalarial role from ChEBI so can expand use of that as needed. Go ahead and deprecate our 'may treat' property.

**Comment by zhengj2007** [comment]
The relation has been deprecated.
