### ISSUE TITLE
NTR: terms for geohash variables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#122]
Entities in our database that have latitude and longitude variables will need seven geohash variables if we want to use MapVEu to show them in a scalable manner with semantic zooming. 

- geohash_1 is a single character string which corresponds to one of 32 rectangles covering the whole globe.
- geohash_2 is a two character string, the first character is from geohash_1 and the second character identifies one of 32 rectangles within the geohash_1 rectangle
- geohash_3 has three characters, the first two are geohash_2, and so on...
- ...
- geohash_7

Template for the seven new terms:

```
name: geohash_[X]
definition: geohash string encoding of geospatial location using [X] characters 
source: https://en.wikipedia.org/wiki/Geohash
```

I don't think these need to be nested in a clever way, but they could all have a parent term 'geohash string' maybe?

**Comment by bobular** [comment]
Could add something like this to the definition: ", providing approximately +/- [Y] km precision" (where Y comes from the table in the Wikipedia page)

**Comment by bobular** [comment]
JohnB is ready to get going with this - there may be a need for a general parent term 'geohash variable' too.

**Comment by zhengj2007** [comment]
Can we add the terms as 'information content entity' with definition Bob provided in the VEuPathDB ontology? The information is about 'geographic location'.

**Comment by bobular** [comment]
Minor update: Jay provided a full resolution 32 character geohash_32 string in the files for JohnB's test loading, and JohnB is loading this into the database because it contains all the information for the shorter versions (geohash_1 to _7).  He'll create the shorter versions in tables that need it.

So ideally we need an ontology term for geohash_32 please.

**Comment by cstoeckert** [comment]
Not planning on using 8-31

**Comment by zhengj2007** [comment]
I added 'geohash code' under identifier with definition: "An identifier that   encodes a geographic location into a short string of letters and digits." .

Also added terms, geohash_1 - geohash_32. By rechecking the definition, I think each one is a kind of geohash code representation rather than part of it. So, I added them as subClass of 'geohash code'.

**Comment by cstoeckert** [comment]
From PR #127 Propose that we use with spaces for the ontology label but include the label with the underscore for the alternative label. OK with you @bobular ?

**Comment by zhengj2007** [comment]
The terms were added.
