### ISSUE TITLE
NTR: additonal vector collection process terms

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#123]
Sarah and Bob went through the first page of (purple highlighted) collection processes and devices and organised them as best we could.  Some new terms could be useful:

Potential new terms marked with *
```
adult arthropod specimen collection process
|-- gravid female arthropod specimen collection process*
|-- arthropod collection process with automated identification* (devices such as BG-Counter which use size and wing beat frequency to discriminate between mosquitoes and other insects; CO2 used to bias collection towards blood feeders; counts automatically communicated over the mobile internet)
|-- collection of flying adults by passive interception* ("barrier trap" device may need some attention, SK to look)


processed material
|-- BG lure* (artificial human skin subsitute lure for use with BG-Sentinel trap - see also BG-lure dispenser)
```

Possible edits/attention for existing terms

- barrier trap (Sarah to check definition)
- Onderstepoort Veterinary Institute light-suction trap (parent should be light trap)
- sticky trap needs 'resting arthropod trap as parent'

**Comment by SAK22** [comment]
Update on barrier trap definition: . The barrier screen, designed to intercept mosquitoes as they fly between areas where blood meals are obtained and oviposition sites where eggs are laid, was developed in 2013 as a novel method of sampling outdoor mosquito populations. Barrier screens do not use an odorant lure and are thus a non-mechanical, simple, low maintenance and passive sampling method for use, even in isolated locations.
