### ISSUE TITLE
NTR: specimen collection duration in days or nights

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#125]
Variable with integer value. What we are recording here is not really the actual duration the trap is set for, but the number of daily collection cycles it is trapping for.  E.g. if traps work at night because mosquitoes are active at night, and you leave it out overnight, that counts as one "day".

old ID:
VBcv_0001009

**Comment by cstoeckert** [comment]
let's make this more general: specimen collection duration
