### ISSUE TITLE
NTR: geolocation precision and provenance terms

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#126]
### VBcv:0001140 | geolocation precision

Qualifier to describe the intended precision (number of decimal places) of lat/long coordinates. Usually applied to a whole study, but this annotation is attached to every geolocated entity.  If geolocation precision is 4 but a coordinate is recorded as 12.345 that just means that this was measured as a value that rounded to 12.3450

The values for this variable are also in the VBcv ontology: 

VBcv:0001144 | 0 decimal places or better precision
VBcv:0001145 | 1 decimal place or better precision
VBcv:0001146 | 2 decimal places or better precision
VBcv:0001147 | 3 decimal places or better precision
VBcv:0001148 | 4 decimal places or better precision

It would be great to have VEuPathDB terms for these please

### VBcv:0001139 | geolocation provenance

Qualifier to describe how the lat/long were obtained or derived. Don't think I can find anything suitable in VEuPath ontology.

Values for this variable are in the VBcv ontology and also here
https://vectorbase.org/popbio-map/web/?view=abnd&zoom_level=3&center=21.289374355860424,-65.47851562500001&summarizeBy=Location%20provenance&grid=true&shared_link=true&limitTerms=true&optimizeColors=true
and in the image
![image](https://user-images.githubusercontent.com/308639/106290580-8abdf300-6242-11eb-837b-8ea7bde4bc71.png)

**Comment by cstoeckert** [comment]
Estimated from administrative region 
Estimated from street address

**Comment by cstoeckert** [comment]
Consider plan specification for precision of value.

**Comment by johnwjudkins** [comment]
Label: geolocation provenance information
Definition: An information content entity that either identifies the process by which latitude and longitude data were obtained, or specifies that it is missing knowledge.

Label: geolocation precision objective specification
Definition: An objective specification to obtain geolocation data whose value has a particular degree of precision.
(I'm basing this on the mention that this is _intended_ precision, rather than resulting precision.)

Label: geolocation precision objective of at least zero decimal places
Definition: A geolocation precision objective specification of at least zero decimal places.
(and so on for the other terms)

**Comment by cstoeckert** [comment]
maybe identifies -> specifies for 'geolocation provenance information'

@bobular @SAK22 are the proposed term labels and definitions (with the one adjustment mentioned above) OK with you?

**Comment by SAK22** [comment]
@cstoeckert just to query the 'intended' precision. Being a little silly, could you explain what you mean here? I agree with the definition but just want to clarify what that means?

**Comment by cstoeckert** [comment]
We got 'intended' from Bob's initial description above: "Qualifier to describe the intended precision (number of decimal places) of lat/long coordinates. " Not sure about the answer to your question.

**Comment by SAK22** [comment]
Ok yes so intended precision, what we assign it as in VB. So they may give us 6dp but we add as 3dp. Happy with these!

**Comment by cstoeckert** [comment]
discussed and decided to remove 'at least' to make these clearer as siblings.

**Comment by cstoeckert** [comment]
Will also make terms for value of geolocation provenance information

**Comment by bobular** [comment]
Hi @johnwjudkins - is there a commit(s) I can find some EUPATH:nnnnnnn term IDs for this ticket?

**Comment by cstoeckert** [comment]
John will create a google sheet with terms scheduled to be added that will have the IDs that you can use.

**Comment by bobular** [comment]
Thank you

**Comment by johnwjudkins** [comment]
@bobular Please use this:
https://docs.google.com/spreadsheets/d/12e1at4Jn75ZYY9PoT1Cb2B4P12fMeM6QmZvG6xOyFXg/edit#gid=0

**Comment by bobular** [comment]
All added to the master lookup sheet (some time ago)

Thanks!

**Comment by zhengj2007** [comment]
It seems the terms were added and the definition issue was fixed. 

@johnwjudkins Shall we close the issue?
