### ISSUE TITLE
NTR: caregiver role

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#128]
Definition: A human social role that is realized in providing assistance in activities of daily living of another human being who lacks the capability to complete some of these activities alone.

Source: Wikipedia:caregiving and NCIT:'Activity of Daily Living'

This term might be suited to OMRSE, and it could include 'caretaker' as an alternative label, but 'caretaker' is more associated with responsibility for the care of a building. (ClinEpiDB labels also have been standardized to "caregiver" rather than "caretaker".) I would also suggest "caretaker" in VEuPath term labels be changed to "caregiver".

**Comment by cstoeckert** [comment]
Agree with submitting to OMRSE.

**Comment by johnwjudkins** [comment]
https://github.com/ufbmi/OMRSE/issues/154

**Comment by johnwjudkins** [comment]
In OMRSE and imported. Closing.
