### ISSUE TITLE
artemether & lumefantrine should be from ChEBI rather than DRON

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#129]
Related to discussion in https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/121:

We have 'artemether-lumefantrine drug product' with axioms identifying artemether and lumefantrine from DRON as parts. (Another axiom uses 'may treat', which we are deprecating.) DRON classifies these as drug products. I suggest replacing these with the associated terms in ChEBI (which have antimalarial roles that we can also include!) and change the axioms for 'artemether-lumefantrine drug product' to "'has active ingredient' some artemether" and "'has active ingredient' some lumefantrine".

These DRON terms are undefined, and the labels are problematic because they don't distinguish between a drug product/medication material and the compound which serves as the active ingredient. (We use other DRON drug product terms, but they are identified as solutions, tablets etc., so those are not problematic.)

**Comment by cstoeckert** [comment]
I agree with switching to ChEBI terms.
