### ISSUE TITLE
Axioms for 'medication role' and treatment terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#130]
Our 'medication role' is defined such that it is realized in a treatment in which a material is administered into an organism. I suggest we add the equivalent axiom:
('role of' only 'material entity') and ('realized in' only ('administering substance in vivo' and treatment))

If this axiom is acceptable, I can go on to create axioms for most of the ClinEpi terms for diarrhea treatment. These terms are information content entities that 'mention' treatment with some medication in some context, so I can create axioms that identify the material that bears the medication role that is realized in the treatment.

(By the way, have we considered an external ontology for 'medication role'?)

**Comment by cstoeckert** [comment]
This definitely should not be a EUPATH term. Note that it is also a OBIB term! http://purl.obolibrary.org/obo/OBIB_0000026 
Should probably be in OGMS.

**Comment by johnwjudkins** [comment]
https://github.com/OGMS/ogms/issues/156

**Comment by johnwjudkins** [comment]
Discussed during Feb. OGMS call. The term is accepted. OGMS plans to further develop roles and treatment, including my suggestion to develop plan specification and objective specification terms for treatments - similar to what OBI does w/assays.
