### ISSUE TITLE
Standardize definition annotation property

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#131]
The imported CMO terms using annotation property:
http://purl.obolibrary.org/obo/def for definition.

CMO:0000005	diastolic blood pressure
CMO:0000027	white blood cell count
CMO:0000254	forced expiratory volume
CMO:0000289	respiration rate
CMO:0000381	partial pressure of blood oxygen (Po2)

Can be replaced by IAO definition annotation when import using Ontofox.

**Comment by cstoeckert** [comment]
Agree with using mapping in Ontofox
http://purl.obolibrary.org/obo/def
mapTo http://purl.obolibrary.org/obo/IAO_0000115

**Comment by johnwjudkins** [comment]
CMO definitions are now values of IAO:0000115. Closing.
