### ISSUE TITLE
remove annotation properties not used or needed

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#132]
'source' created to indicate PRISM but not really used or needed.

1. EUPATH_0000052 EuPathDB alternative term
Not used. Shall we use it to indicate the label used in VEuPathDB? If not, deprecate it?

2. EUPATH_0000112	EuPathDB definition
Not used. Shall we deprecate the term?

Will wait until discuss with ClinEpi.

**Comment by zhengj2007** [comment]
The annotation properties have been deprecated.
