### ISSUE TITLE
NCIT terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#133]
The Ontozoo appears to have delisted NCIT; I noticed when Ontofox didn't work with NCIT terms. I can keep them by adding them to externalByHand instead, but this could be an opportunity to discuss replacements.

Fungus: we also have 'Fungi' from NCBITaxon, but we have the 'Fungus' NCIT ID in eupath-isa.
Reference: IAO has 'citation'. Replacing this would also require a change in eupath-isa.

**Comment by cstoeckert** [comment]
Jie will look at replacing and check on impact of genomics site.

**Comment by zhengj2007** [comment]
Will replace the NCIT term by NCBITaxon one after this VEuPathDB release.

**Comment by zhengj2007** [comment]
Replaced the NCIT term by NCBITaxon one in the eupath_isa.owl.

NCIT term can be removed from the import.

**Comment by johnwjudkins** [comment]
Ontofox can now import from NCIT. NCIT:Fungus is removed from the import .owl file. Closing.
