### ISSUE TITLE
Normalize subClasses of term 'count'

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#134]
The labels of subClasses of term 'count', some use 'count of', some use 'number of'. Might need to be normalized. Besides, the definitions of the terms would be better to be normalized.

ID|Label
-- | --
EUPATH:0022004 | count of beds with bednet
EUPATH:0043046 | count of traps
EUPATH:0000134 | number of Anopheles collections
EUPATH:0000595 | number of child occupants in a dwelling
EUPATH:0000121 | number of clinical visits
EUPATH:0000122 | number of clinical visits resulting in a malaria diagnosis
EUPATH:0000123 | number of clinical visits resulting in an asymptomatic   microscopic parasitemia diagnosis
EUPATH:0000486 | number of clinical visits resulting in an asymptomatic   parasitemia diagnosis
EUPATH:0000379 | number of common areas in a dwelling
EUPATH:0000492 | number of courses of antibiotics given
EUPATH:0000028 | number of days eating meat in a week
EUPATH:0043177 | number of entomology collections
EUPATH:0000348 | number of infections with P. falciparum in lifetime
EUPATH:0000349 | number of infections with P. falciparum in the last year
EUPATH:0000346 | number of infections with P. vivax in lifetime
EUPATH:0000347 | number of infections with P. vivax in the last year
EUPATH:0043155 | number of input specimens to assay
EUPATH:0000398 | number of insecticide-treated bed nets treated less than 6   months ago
EUPATH:0000399 | number of insecticide-treated bed nets treated more than 6   months ago
EUPATH:0000395 | number of livestock
EUPATH:0000400 | number of long last insecticide-treated bed nets
EUPATH:0000426 | number of malaria diagnosis past year
EUPATH:0000027 | number of meals per day
EUPATH:0000124 | number of non-routine clinical visits
EUPATH:0000336 | number of non-scheduled visits
EUPATH:0000396 | number of pets
EUPATH:0000019 | number of residents in a dwelling
EUPATH:0000025 | number of rooms for sleeping in a dwelling
EUPATH:0000125 | number of routine clinical visits
EUPATH:0000337 | number of scheduled visits
EUPATH:0000201 | number of sleeping places in dwelling with a household
EUPATH:0000619 | number of treatments
EUPATH:0000401 | number of untreated bed net

**Comment by cstoeckert** [comment]
We should move 'count' under 'measurement datum' to be consistent with STATO. Then all 'counts' will be under measurement datum in VEuPath. Should move all 'number of ..' terms in VEuPath to be under 'count' (some are directly under 'measurement datum'). Change labels to all be 'number of..'
