### ISSUE TITLE
ClinEpi 'Drinking water source' related terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#136]
In ClinEpi projects, terms used for annotations of 'Drinking water source' (ENVO_00003064), some used the subClasses of ENVO_00003064 'drinking water', some used subClasses of 'dwelling information'. The subClasses of 'dwelling information' are information content entity mentions 'drinking water' terms. So, why don't we use all 'drinking water' terms in ClinEpi annotations?

SubClasses of 'drinking water'
ID | Label
-- | --
EUPATH:0015050 | drinking water derived from bore hole water
EUPATH:0015046 | drinking water derived from rainwater
EUPATH:0000254 | drinking water from open public well
EUPATH:0000255 | drinking water from open well in yard
EUPATH:0000256 | drinking water from pipe into dwelling
EUPATH:0000257 | drinking water from pipe into yard
EUPATH:0000261 | drinking water from unprotected freshwater spring

SubClasses of 'dwelling information'
ID | Label
-- | --
EUPATH_0015033 | information on drinking water piped into dwelling
EUPATH:0015035 | information on drinking water piped into yard

Besides, I think rainwater (ENVO_01000600) is a fresh water that people can drink directly. Can we use rainwater (ENVO_01000600) for ClinEpi annotation purpose? We can discuss with EnVO people to add something like 'drinking water role'. It is similar to 'roof role', 'wall role' which can be born by 'wood'.

**Comment by johnwjudkins** [comment]
I agree that there are inconsistencies among the drinking water terms. The terms that are values for drinking water source etc. should be children of water, and the variables should be ICEs. (E.g. the placeholder EUPATH:0022063 is a variable described as "Whether the household has access to potable water".)

**Comment by cstoeckert** [comment]
Agree to deprecate :
EUPATH_0015033 | information on drinking water piped into dwelling
EUPATH:0015035 | information on drinking water piped into yard
and replace with existing:
EUPATH:0000256 | drinking water from pipe into dwelling
EUPATH:0000257 | drinking water from pipe into yard

**Comment by johnwjudkins** [comment]
@zhengj2007 Can we close this?
