### ISSUE TITLE
NTR: VNI subdivision

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#14]
It is used to specify the genetic subtype of Fungal organism.
Assigned ID: EUPATH_0005006
Associated Redmine ticket: #31466

**Comment by zhengj2007** [comment]
Shall we add the term in VEuPathDB ontology?

**Comment by johnwjudkins** [comment]
"VNI subdivision" refers to this variety of C. neoformans: http://purl.obolibrary.org/obo/NCBITaxon_2665964 according to https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5495072/. So should we just use the NCBITaxon term?
