### ISSUE TITLE
EUPATH:0000093	dwelling information, label, definition and logical axiom is not consistent

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#140]
EUPATH:0000093	dwelling information
Definition: An information content entity about dwelling.
Logical axiom: ('is about' some 'human dwelling')

Suggest to relabel the term as 'human dwelling information' and update the definition as 'An information content entity about human dwelling'.

**Comment by johnwjudkins** [comment]
I agree, but I would use "about a human dwelling" in the definition.

**Comment by johnwjudkins** [comment]
This term was deprecated. Closing.
