### ISSUE TITLE
Parent of some dwelling related terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#141]
ID | Label
-- | --
EUPATH:0000302 | information on dwelling facilities
EUPATH:0000303 | information on dwelling physical characteristics

The parent of the terms are ICE. Shall we move them under 'dwelling information'?

**Comment by johnwjudkins** [comment]
We've deprecated 'dwelling information'. Would you like to close this, @zhengj2007 ?
