### ISSUE TITLE
Normalize labels of ICE terms with expected boolean answers 

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#142]
The labels of the ICE terms that we expected boolean answers are not labeled consistently. Some use 'indicator of', some use 'information on', some contain 'whether'. Need to be normalized.

ID | Label
-- | --
EUPATH:0010418 | indicator of participant eligibility for enrollment
EUPATH:0000513 | information on availability of molecular data
EUPATH:0023013 | information on whether discharged from   hospital
EUPATH:0000588 | information on whether a family moved
EUPATH:0000417 | information on whether a person   is sick now
EUPATH:0000375 | information on whether a person plans to move
EUPATH:0000795 | information on whether assay performed
EUPATH:0000583 | information on whether bee colony treated with tetracycline
EUPATH:0000592 | information on whether bee larvae treated with tetracycline
EUPATH:0000580 | information on whether child exposed to antibiotics
EUPATH:0000495 | information on whether hive treated with tetracyline
EUPATH:0022053 | information on whether participant present for clinical visit
EUPATH:0000362 | information on whether received payment from primary economic   activity
EUPATH:0000363 | information on whether received payment from secondary   economic activity
EUPATH:0022057 | information on whether specimen collection prompted by sign of   fever
EUPATH:0000496 | information on whether specimen from mother or child
EUPATH:0010579 | information on whether Adenovirus ELISA   performed
EUPATH:0010580 | information on whether Astrovirus ELISA performed
EUPATH:0010590 | information on whether Cryptosporidium ELISA performed
EUPATH:0010591 | information on whether Entamoeba histolytica ELISA performed
EUPATH:0021056 | information on whether falcivax performed
EUPATH:0010592 | information on whether Giardia ELISA performed
EUPATH:0010583 | information on whether modified acid fast staining method performed
EUPATH:0010588 | information on whether Norovirus RT-PCR performed
EUPATH:0021060 | information on whether optimal-IT performed
EUPATH:0010581 | information on whether Rotavirus ELISA performed
EUPATH:0021031 | microscopy assay performed
EUPATH:0021047 | forgot where treatment within past year occurred
EUPATH:0021046 | indicator of self-treated malaria
EUPATH:0021045 | information on whether treated by private practice
EUPATH:0021044 | information on whether treated in clinic
EUPATH:0023057 | information on whether participant died in   hospital
EUPATH:0021066 | forgot whether used personal mosquito   repellent
EUPATH:0023027 | information on whether moved in past month
EUPATH:0023026 | information on whether moved in past twelve months
EUPATH:0021091 | information on whether given malaria   medication in past 2 weeks
EUPATH:0021090 | information on whether had fever in last 48 hours
EUPATH:0021096 | information on whether had fever in last two weeks
EUPATH:0000412 | information on whether has existing illness
EUPATH:0023056 | information on whether participant is member of tribe
EUPATH:0021088 | information on whether participant has sign
EUPATH:0021089 | information on whether participant has symptom
EUPATH:0000599 | information on whether antibiotics given to   mom
EUPATH:0000428 | information on whether antimalarial drug treated last year
EUPATH:0000409 | information on whether antimalarial drugs taken as advised
EUPATH:0023040 | information on whether antimalarial treatment initiated
EUPATH:0023046 | information on whether fifth antimalarial taken
EUPATH:0023045 | information on whether fourth antimalarial taken
EUPATH:0023012 | information on whether second antimalarial taken
EUPATH:0023024 | information on whether third antimalarial taken
EUPATH:0000410 | information on whether took antimalarial drugs in last 2 weeks
EUPATH:0010153 | indicator of whether receiving medication

Note: May miss some terms.

**Comment by johnwjudkins** [comment]
I could use "indicator of..." for all variables (not values) having boolean values (following OBIB). However, some of the terms in this list are multifilter values (e.g. EUPATH:0021066).

**Comment by cstoeckert** [comment]
Recognize that there is a difference between boolean (yes/no) and more general responses (yes, no, don't know, NA, etc.). Can use different labels (e.g., indicator of vs information on) to distinguish and adjust the textual definition accordingly. Would we want to use the same IRI for both? 
Further discussion, note that indicator of could be used for the limited set of responses (yes, no, don't know, NA) and distinguish from 'information on' which could be a free text response. 
Need to check on ClinEpi usage and adjust terms accordingly.

**Comment by zhengj2007** [comment]
The terms are not used in the VEuPath Database. Shall we deprecated?

Label | ID
-- | --
EUPATH:0000795 | information on whether assay performed
EUPATH:0000495 | information on whether hive treated with tetracyline
EUPATH:0000496 | information on whether specimen from mother or child

**Comment by zhengj2007** [comment]
ID | Label | Values in the ClinEpi | Proposed label
-- | -- | -- | --
EUPATH:0010418 | indicator of participant eligibility for enrollment | Yes/No/NA/missing/unknown | &nbsp;
EUPATH:0000513 | information on availability of molecular data | category, but values of subClasses   are Yes/No/NA
EUPATH:0023013 | information on whether discharged from hospital | Yes/No/NA/missing/unknown | indicator of discharged from hospital
EUPATH:0000588 | information on whether a family moved | Yes/No/NA/missing/unknown | indicator of a family moved
EUPATH:0000417 | information on whether a person is sick now | Yes/No/NA/missing/unknown | indicator of a person is sick now
EUPATH:0000375 | information on whether a person plans to move | Yes/No/NA/missing/unknown | indicator of a person plans to move
EUPATH:0000795 | information on whether assay performed | Not used | &nbsp;
EUPATH:0000583 | information on whether bee colony treated with tetracycline | Yes/No/NA/missing/unknown | indicator of bee colony treated with tetracycline
EUPATH:0000592 | information on whether bee larvae treated with tetracycline | Yes/No/NA/missing/unknown | indicator of bee larvae treated with tetracycline
EUPATH:0000580 | information on whether child exposed to antibiotics | Yes/No/NA/missing/unknown | indicator of child exposed to antibiotics
EUPATH:0000495 | information on whether hive treated with tetracyline | Not used | &nbsp;
EUPATH:0022053 | information on whether participant present for clinical visit | Yes/No/NA/missing/unknown | indicator of participant present for clinical visit
EUPATH:0000362 | information on whether received payment from primary economic   activity | Yes/No/NA/missing/unknown | indicator of received payment from primary economic activity
EUPATH:0000363 | information on whether received payment from secondary   economic activity | Yes/No/NA/missing/unknown | indicator of received payment from secondary economic activity
EUPATH:0022057 | information on whether specimen collection prompted by sign of   fever | information | &nbsp;
EUPATH:0000496 | information on whether specimen from mother or child | Not used | &nbsp;
EUPATH:0010579 | information on whether Adenovirus ELISA performed | Yes/No/NA/missing/unknown | indicator of Adenovirus ELISA performed
EUPATH:0010580 | information on whether Astrovirus ELISA performed | Yes/No/NA/missing/unknown | indicator of Astrovirus ELISA performed
EUPATH:0010590 | information on whether Cryptosporidium ELISA performed | Yes/No/NA/missing/unknown | indicator of Cryptosporidium ELISA performed
EUPATH:0010591 | information on whether Entamoeba histolytica ELISA performed | Yes/No/NA/missing/unknown | indicator of Entamoeba histolytica ELISA performed
EUPATH:0021056 | information on whether falcivax performed | Yes/No/NA/missing/unknown | indicator of falcivax performed
EUPATH:0010592 | information on whether Giardia ELISA performed | Yes/No/NA/missing/unknown | indicator of Giardia ELISA performed
EUPATH:0010583 | information on whether modified acid fast staining method   performed | Yes/No/NA/missing/unknown | indicator of modified acid fast staining method performed
EUPATH:0010588 | information on whether Norovirus RT-PCR performed | Yes/No/NA/missing/unknown | information on whether Norovirus RT-PCR performed
EUPATH:0021060 | information on whether optimal-IT performed | Yes/No/NA/missing/unknown | indicator of optimal-IT performed
EUPATH:0010581 | information on whether Rotavirus ELISA performed | Yes/No/NA/missing/unknown | indicator of Rotavirus ELISA performed
EUPATH:0021031 | microscopy assay performed | Yes/No/NA/missing/unknown | indicator of microscopy assay performed
EUPATH:0021047 | forgot where treatment within past year occurred | Yes/No/NA/missing/unknown | indicator of forgetting treatment location within past   year
EUPATH:0021046 | indicator of self-treated malaria | Yes/No/NA/missing/unknown | &nbsp;
EUPATH:0021045 | information on whether treated by private practice | Yes/No/NA/missing/unknown | indicator of treated by private practice
EUPATH:0021044 | information on whether treated in clinic | Yes/No/NA/missing/unknown | indicator of treated in clinic
EUPATH:0023057 | information on whether participant died in hospital | Yes/No/NA/missing/unknown | indicator of a participant died in hospital
EUPATH:0021066 | forgot whether used personal mosquito repellent | information | information on forgetting whether used personal mosquito   repellent
EUPATH:0023027 | information on whether moved in past month | Yes/No/NA/missing/unknown | indicator of moved in past month
EUPATH:0023026 | information on whether moved in past twelve months | Yes/No/NA/missing/unknown | indicator of moved in past twelve months
EUPATH:0021091 | information on whether given malaria medication in past 2   weeks | information | &nbsp;
EUPATH:0021090 | information on whether had fever in last 48 hours | Yes/No/NA/missing/unknown | indicator of had fever in last 48 hours
EUPATH:0021096 | information on whether had fever in last two weeks | Yes/No/NA/missing/unknown | indicator of had fever in last two weeks
EUPATH:0000412 | information on whether has existing illness | Yes/No/NA/missing/unknown | indicator of having existing illness
EUPATH:0023056 | information on whether participant is member of tribe | Yes/No/NA/missing/unknown | indicator of a participant is member of tribe
EUPATH:0021088 | information on whether participant has sign | Yes/No/NA/missing/unknown | indicator of a participant has sign
EUPATH:0021089 | information on whether participant has symptom | Yes/No/NA/missing/unknown | indicator of a participant has symptom
EUPATH:0000599 | information on whether antibiotics given to mom | Yes/No/NA/missing/unknown | indicator of antibiotics given to mom
EUPATH:0000428 | information on whether antimalarial drug treated last year | Yes/No/NA/missing/unknown | indicator of antimalarial drug treated last year
EUPATH:0000409 | information on whether antimalarial drugs taken as advised | Yes/No/NA/missing/unknown | indicator of antimalarial drugs taken as advised
EUPATH:0023040 | information on whether antimalarial treatment initiated | Yes/No/NA/missing/unknown | indicator of antimalarial treatment initiated
EUPATH:0023046 | information on whether fifth antimalarial taken | Yes/No/NA/missing/unknown | indicator of fifth antimalarial taken
EUPATH:0023045 | information on whether fourth antimalarial taken | Yes/No/NA/missing/unknown | indicator of fourth antimalarial taken
EUPATH:0023012 | information on whether second antimalarial taken | Yes/No/NA/missing/unknown | indicator of second antimalarial taken
EUPATH:0023024 | information on whether third antimalarial taken | Yes/No/NA/missing/unknown | indicator of third antimalarial taken
EUPATH:0000410 | information on whether took antimalarial drugs in last 2 weeks | Yes/No/NA/missing/unknown | indicator of taking antimalarial drugs in last 2 weeks
EUPATH:0010153 | indicator of whether receiving medication | Yes/No/NA/missing/unknown | indicator of receiving medication

Question: when should we use 'participant' or 'person' in the label?

**Comment by cstoeckert** [comment]
DIscussed and will review based on definitions whether referring to participant. If so, then label should indicate that. Otherwise can be general (person) or something else (family, bee hive). Jie will generate a new VEuPath terms sheet with reviewed/ tracker column to help with review.

**Comment by cstoeckert** [comment]
indicator of _whether_ Adenovirus ELISA _was_ performed (add whether and was to labels).
Do this for all of this type. Don't need to say if on participant specimen.
