### ISSUE TITLE
Normalize labels of ICE terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#144]
Some examples of ICE term labels. May consider to name the terms more consistently 

ID | Label
-- | --
EUPATH:0000431 | information on who treated malaria last year
EUPATH:0000612 | information specifying human or animal
EUPATH:0043005 | information specifying no arthropod attractor used
EUPATH:0000338 | malaria diagnosis and parasite status information
EUPATH:0000316 | malaria severity and basis information
EUPATH:0021026 | no treatment for fever

**Comment by zhengj2007** [comment]
Shall we close it?

**Comment by johnwjudkins** [comment]
I think I should work on the last 3 labels, in order to conform to the wiki.

**Comment by zhengj2007** [comment]
EUPATH:0000316 can be deprecated.

EUPATH:0000338 mixes two pieces of information, malaria diagnosis information and parasite status based on blood smear and LAMP tests. Not a good ontology term. But required by data provider. 
Here are the values of EUPATH:0000338
- Symptomatic malaria
- Blood smear positive, no malaria
- Blood smear negative, LAMP positive
- Blood smear negative, LAMP negative
- Blood smear negative, LAMP not done
- Blood smear indicated but not done
- Blood smear not indicated

**Comment by zhengj2007** [comment]
Add the values in the editor notes for term EUPATH:0000338
