### ISSUE TITLE
Deprecate EUPATH:0000739	environmental history?

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#147]
EUPATH:0000739
Label: environmental history
Definition: A planned process that an organism exposed to that are not one of the variables under study.

The term is not used   in VEuPathDB site. No child in the ontology. The term is not well defined. Shall we deprecate the term?

**Comment by cstoeckert** [comment]
I agree with deprecating.
