### ISSUE TITLE
Normalize labels of site related terms 

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#148]
ID | Label
-- | --
EUPATH:0010112 | hand washing location
EUPATH:0000542 | location of specimen collection
EUPATH:0000530 | location where GPS coordinates were taken
EUPATH:0010067 | place of death

**Comment by johnwjudkins** [comment]
My suggestion:

hand washing site
specimen collection site
GPS coordinate determination site
death site

Alternatively, reword with "site" at beginning e.g. "site of hand washing".

**Comment by johnwjudkins** [comment]
Changing 'place of death' to 'location of death' as discussed, keeping 'place of death' as alternative.
