### ISSUE TITLE
Remove unit in the measurement datum

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#149]
Some measurement datum terms with unit may consider to remove as what we did in clinEpi display terminologies.

ID | Label
-- | --
EUPATH:0000047 | hemoglobin level in g per dL
EUPATH:0000026 | land area measured in acres
EUPATH:0010316 | stool volume in ml
EUPATH:0000382 | total area measured in square meter
EUPATH:0000030 | distance to health facility in km
EUPATH:0000753 | specimen collection time in year

**Comment by johnwjudkins** [comment]
If we do this, we should deprecate EUPATH:0000753, since we have a term for specimen collection time from OBI.

**Comment by johnwjudkins** [comment]
EUPATH:0000382 is from one project (ICEMR Amazonia Peru) and refers to the total area of a land lot. Should we change the label & definition to reflect that? We could alternatively change it to 'area measurement datum' (which we would want to submit to IAO or OBI).

**Comment by cstoeckert** [comment]
Discussed and agree that this term should capture the context of the lot area that the dwelling is on and so should relabel and define to be more specific. Make this a new term. Can leave or deprecate EUPATH:0000382 (not urgent).
