### ISSUE TITLE
NTR 'PCR amplification of specific alleles'

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#151]
For VB popbio migration.

Usage of this term seems to be for genotyping - mainly microsatellites, chromosomal inversions and targeted assays of known resistance loci.  See below.

MIRO term didn't seem to have a definition.... see https://legacy.vectorbase.org/popbio/REST/cvterm/MIRO:20000100

I think we just need a simple PCR child of http://purl.obolibrary.org/obo/OBI_0000435 (genotyping assay)

https://vectorbase.org/popbio-map/web/?protocols_cvterms=MIRO:20000100&view=smpl&zoom_level=1&center=20.96143961409684,-55.19531250000001&summarizeBy=Available%20data%20types&grid=true&shared_link=true&limitTerms=true
![image](https://user-images.githubusercontent.com/308639/109368473-20c05a00-7891-11eb-9660-2f986f28c91f.png)

**Comment by cstoeckert** [comment]
This should be submitted to OBI as a NTR. In keeping with other genotyping assays differentiated by technology we could propose:
label: 'genotyping by PCR assay'
definition: A genotyping assay that uses polymerase chain reaction.
logical axioms: 
   genotyping assay
   has part some polymerase chain reaction
examples of usage: genotyping by PCR assay to identify microsatellites, chromosomal inversions and targeted assays of known resistance loci.

**Comment by zhengj2007** [comment]
@bobular Does 'genotyping by PCR assay' work?

**Comment by cstoeckert** [comment]
@bobular agrees with term (see Slack) so will submit to OBI.

**Comment by zhengj2007** [comment]
Term request submitted to OBI:
https://github.com/obi-ontology/obi/issues/1348

**Comment by bobular** [comment]
Thanks - incorporated into lookup sheet

OBI:0003032 | genotyping by PCR assay

**Comment by cstoeckert** [comment]
Still need to import after next OBI release.
