### ISSUE TITLE
NTR: 'combined feeding and gonotrophic status of insect'

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#152]
This is a variable used to describe mosquito samples.

Sarah can (please) help locate all the values used for this variable, but some are in the latest dry-run missing terms sheet.
https://docs.google.com/spreadsheets/d/1vlj-4NTpKJNjj-eU-JgJr6d2OHXiGwiK14InUeNmA7c/edit#gid=1723653757

There was some discussion about the "combined" thing being bad.  Take a look at the values used and maybe we can come up with a less offensive name ;-)

**Comment by cstoeckert** [comment]
@SAK22 looks like the values are fed and unfed female insect annotated in the sheet. Are there others? Not sure where gonotrophic comes in. Can you provide a suggested definition? Thanks!

**Comment by SAK22** [comment]
@cstoeckert ok so under combined feeding and gonotrophic status of insect there is unfed and fed female insect, the children of fed female insect are: fed and gravid female insect and freshly fed female insect.
If the combined is bad, we could split them out so each sample has an ontology for unfed or fed, male or female, gravid or non gravid?

**Comment by cstoeckert** [comment]
From some googling it looks like feeding affects the gonotrophic cycle. Does that mean you really only care about the feeding state of gravid females? i.e., don't need to annotate whether males are fed, don't care if non-gravid females are fed, just care if gravid females are fed or freshly fed?

**Comment by bobular** [comment]
Yes we only care about female feeding status.

(Males feed on nectar and don't bite humans/vertebrates - always ignored.)

**Comment by bobular** [comment]
Reminder to follow up :-)

**Comment by cstoeckert** [comment]
Sorry for the delay @bobular @SAK22 
In summary then, 4 terms are requested:
One for the variable: combined feeding and gonotrophic status
Three for the values:
fed gravid female insect
freshly fed female insect
unfed female insect

Simplest would be to make these information terms (information content entities) to capture the status in one term. Alternative is to use individually 'gravid organism' UBERON_0009097, female PATO_0000383, and come up with new terms for feeding status (fed, freshly fed, unfed).

If we go with the former (information terms) then propose these terms that mention blood meals:
gravid female insect feeding status: Information about a gravid female insect regarding when and if it had a blood meal.
fed gravid female insect status: A gravid female insect feeding status that it had a blood meal.
recently fed gravid female insect status: A gravid female insect feeding status of recently having a blood meal.
unfed gravid female insect status: A gravid female insect feeding status of not having a blood meal.

Thoughts?

**Comment by bobular** [comment]
I've looked into this more and unfortunately we have a few more values in VBcv...
![image](https://user-images.githubusercontent.com/308639/124309270-630ce700-db62-11eb-8e44-ca5023962535.png)

The good news is that `blood-fed twice` and `sugar-fed` aren't used in popbio, 

`fully-fed` and `partially-fed` are used, but I suggest mapping them both to `fed female insect`

Could we have new term `fed female insect` as a parent of  `fed gravid female insect` and `freshly fed female insect` ?

**Comment by cstoeckert** [comment]
Hi @bobular 
Note that this is the hierarchy of the terms that I proposed:
gravid female insect feeding status: 
	fed gravid female insect status: 
	recently fed gravid female insect status: 
	unfed gravid female insect status: 
Did you want this instead? 
female insect feeding status
	recently fed female insect status: 
	gravid female insect feeding status: 
		fed gravid female insect status: 
		unfed gravid female insect status:

**Comment by bobular** [comment]
I think we need a term for unfed females, so I've adjusted it a bit

```
female insect feeding status
-- unfed female insect status: **
-- recently fed female insect status:
-- gravid female insect feeding status:
--- fed gravid female insect status:
--- unfed gravid female insect status: **
```

`**` @SAK22 - would the unfed be better as "not recently fed"?

**Comment by SAK22** [comment]
I think unfed is fine, that is the commonly used term! Usually they are actually totally unfed as well, as they collect mosquitoes in the field, rear an F1 generation then use those for testing.

**Comment by cstoeckert** [comment]
Here are the adjusted proposed terms based on the discussion above:
female insect feeding status: Information about a female insect regarding when and if it had a blood meal.
unfed female insect status: A female insect feeding status of not having a blood meal.
recently fed female insect status: A female insect feeding status of recently having a blood meal.
gravid female insect feeding status: A female insect feeding status about a gravid female insect.
fed gravid female insect status: A gravid female insect feeding status that it had a blood meal.
unfed gravid female insect status: A gravid female insect feeding status of not having a blood meal.

**Comment by SAK22** [comment]
Looks great @cstoeckert should the fed gravid female description match the others? Using A gravid female insect feeding status **of having** a blood meal?

**Comment by cstoeckert** [comment]
@SAK22 Sounds good. Will make that change. Thanks for reviewing!

**Comment by bobular** [comment]
We'd need to check with @SAK22, but I'd suggest changing
```
unfed gravid female insect status: A gravid female insect feeding status of not having a blood meal.
```
to
```
unfed gravid female insect status: A gravid female insect feeding status of not recently having a blood meal.
```

Note that female mosquitoes feed on blood, digest and become gravid/make a batch of eggs (they store sperm from a previous insemination) - then they can feed again become gravid again.

So the "recent" thing is important.  Maybe it should be changed to "visible blood meal" or "undigested" or something?

**Comment by SAK22** [comment]
I think I like the idea of "visible blood meal" if we can make that work? As all this is done (mostly) by eye, so they look at the bellies of the mozzies, see no red but see a large tummy full of eggs.

**Comment by cstoeckert** [comment]
How's this then? Please edit as needed (such as adding "visible" to other definitions). Thanks. @SAK22 @bobular 

unfed gravid female insect status: A gravid female insect feeding status of not recently having a visible blood meal.

fed gravid female insect status: A gravid female insect feeding status of having a blood meal.

gravid female insect feeding status: A female insect feeding status about a gravid female insect.

female insect feeding status: Information about a female insect regarding when and if it had a blood meal.

unfed female insect status: A female insect feeding status of not having a blood meal.

recently fed female insect status: A female insect feeding status of recently having a blood meal.
