### ISSUE TITLE
NTR: 'DNA barcode assay' and two variables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#153]
### protocol term
Yet again a legacy VB term with no definition... https://legacy.vectorbase.org/popbio/REST/cvterm/VBcv:0001025

barcoding can mean at least two things to people
1. assaying a smallish panel of SNPs by whatever appropriate technology 
2. sequencing a small (~600) defined region of genome (usually mitochondrial, usually in COI gene) amplified by PCR

Here we mean the second meaning.

### variables

'barcode target locus' | VBcv:0001016 | no definition in VBcv
'oligonucleotide primer set' | VBcv:0001024 | has a definition! "oligonucleotide primer set used in a PCR reaction, e.g. amplification of a DNA barcode sequence"

Values for these terms in the dry run 2 missed terms sheet
https://docs.google.com/spreadsheets/d/1vlj-4NTpKJNjj-eU-JgJr6d2OHXiGwiK14InUeNmA7c/edit#gid=1723653757

Questions? Sarah, Bob or Sam

**Comment by cstoeckert** [comment]
For 'barcode assay' does 'taxonomic diversity assessment by targeted gene survey' http://purl.obolibrary.org/obo/OBI_0001960 work for this?

**Comment by bobular** [comment]
Sounds perfect, thanks!

**Comment by cstoeckert** [comment]
Great. I updated the popbio-term-usage spreadsheet with this term. Will work on the others.

**Comment by cstoeckert** [comment]
Some thoughts on the other requested terms:
- 'barcode target locus' is a role. Could be an evaluant role (http://purl.obolibrary.org/obo/OBI_0000067) that is realized in a 'taxonomic diversity assessment by targeted gene survey'
- 'oligonucleotide primer set' a processed material (http://purl.obolibrary.org/obo/OBI_0000047) that consists of oligonucleotides (http://purl.obolibrary.org/obo/CHEBI_7754) in which a primer role (http://purl.obolibrary.org/obo/OBI_0000405) inheres.

**Comment by cstoeckert** [comment]
DIscussed with ontology team and are OK with these definitions.
@bobular do these work for you?

**Comment by cstoeckert** [comment]
Discussed and agreed OK - will submit to OBI.

**Comment by cstoeckert** [comment]
Added to obi-edit.owl and made PR https://github.com/obi-ontology/obi/pull/1335

**Comment by cstoeckert** [comment]
In obi-dev now.

**Comment by cstoeckert** [comment]
@johnwjudkins Please import this for the next release. Thanks.

**Comment by bobular** [comment]
Two new terms from  obi-ontology/obi#1335 added to popbio term mapping master sheet
