### ISSUE TITLE
editor note of EUPATH:0000002 obsolete_dwelling

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#155]
The value of 'editor note' of EUPATH:0000002 obsolete_dwelling is 'FALSE' with type boolean. Consider to remove. Besides better add the 'obsolete reason'. If I am correct, I think the term is deprecated due to replace with ENVO_01000744 'human dwelling'. If so, better add it in.

**Comment by johnwjudkins** [comment]
Editor note removed. I will add a value for 'term replaced by' when we decide whether to use the label, ID, or IRI.
