### ISSUE TITLE
'term replaced by' annotations of deprecated terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#156]
The String type is used for 'term replaced by' annotation in VEuPathDB ontology. All except one deprecated terms indicate the replaced terms using ontology term IDs. The 'term replaced by' annotation value of EUPATH:0000368	'obsolete_garbage disposal'  is 'replaced with ENVO_01001260'. Better change it to ID only.

Following obsolete terms, the replaced term IDs indicated in the 'editor note' but not use 'term replaced by'. May be better to add replaced term using 'term replaced by' annotations

ID | Label | editor note
-- | -- | --
EUPATH:0000498 | obsolete_16S rRNA gene region for sequencing | replaced by: SO_0001000: rRNA_16S
EUPATH:0000454 | obsolete_average mapping coverage | deprecated in favor of GENEPIO_0000092 'read coverage'
EUPATH:0000049 | obsolete_clinical visit | replaced with OGMS:0000097
EUPATH:0000032 | obsolete_date of birth | replaced by EFO_0004950: date of birth
EUPATH:0000516 | obsolete_electrolyte disturbances | deprecated in favor of HP_0003111 'Abnormality of ion homeostasis'
EUPATH:0000573 | obsolete_genetic clade of organism | deprecated in favor of APOLLO_SV_00000232 'clade name'
EUPATH:0000061 | obsolete_has active ingredient | replaced with RO:0002248
EUPATH:0000340 | obsolete_human traveling information | replaced with OMRSE:00000142

Besides, we may consider to use replaced term IRI rather than term ID, i.e. annotation value type change from literal to IRI.

**Comment by johnwjudkins** [comment]
We could also use the label as this value, following OBI.

**Comment by zhengj2007** [comment]
I prefer to use IRI since it can link to the replaced term directly. The label may be changed in the ontology.
