### ISSUE TITLE
relabel http://purl.obolibrary.org/obo/EUPATH_0022001 community

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#158]
Not clear that this refers to a geographic location as opposed to a collection of humans as in PCO.

**Comment by johnwjudkins** [comment]
I suggest 'community location', or alternatively 'community site'.

**Comment by cstoeckert** [comment]
Note that this change will impact 'community visited ..' terms. See https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/139

**Comment by zhengj2007** [comment]
'community location' looks good to me.

**Comment by zhengj2007** [comment]
Consider to replace with ENVO 'dense settlement', http://purl.obolibrary.org/obo/ENVO_01000658

**Comment by cstoeckert** [comment]
These 'community' terms all refer to what is called 'settlement' in ClinEpi and we should replace/ adjust the terms accordingly. However, there is still a need for a node that is used to refer to either a cluster (study-based grouping) or a compound (physically shared housing). Since these are different types of entities we will use something like 'community information' as we have done for 'specimen information'.

**Comment by cstoeckert** [comment]
'community information' = an information content entity that is about a population of humans that bears a study group role such as cluster or compound study group role involving multiple households. Run this by ClinEpi first.

**Comment by cstoeckert** [comment]
Will change the IRI for 'community information' to EUPATH_0035127
