### ISSUE TITLE
DRON term(s) could replace 'medication role'

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#160]
'medication role' is a EUPATH term which we have proposed to OGMS. However, DRON may have 1 or 2 existing terms that could replace it.

DRON has 'drug product therapeutic function', which inheres in a 'drug product; and has subclass 'anti-malarial function of a drug product'.

The former is defined as:

A function inhering in a drug product that when realized, is realized by a process that either (1) negatively regulates symptom processes, processes leading to symptoms, and/or the realization of a disease, (2) has specified output some entity useful in the diagnosis of disease, or (3) negatively regulates or blocks etiological processes.

The latter is defined as:

A therapeutic function of a drug product that is realized by administration of the drug product resulting in creation of a material basis of a resistance to malaria infection disposition.

DRON also has 'clinical drug role', defined as: The role of a material entity to prevent, diagnose, treat, or study disease and/or its effects.

It may make more sense to use 'clinical drug role' and/or 'drug product therapeutic function' than it does for OGMS to use 'medication role'. I don't see a difference between a clinical drug and a medication. Note in the definition for 'anti-malarial function of a drug product' the relationship described between the drug product and the disease.

**Comment by zhengj2007** [comment]
Based on the definition, I think EUPATH 'medication role' is same as DRON 'clinical drug role'.

**Comment by cstoeckert** [comment]
I agree. I think we can deprecate our term and use DrOn's 'clinical drug role' instead.

**Comment by cstoeckert** [comment]
Add tracker to deprecated term and then can close.
