### ISSUE TITLE
IRI for artemether-lumefantrine product

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#162]
DRON:00032533 'artemether / lumefantrine Oral Tablet' could replace EUPATH:0000063 'artemether-lumefantrine drug product'. The DRON term explicitly mentions the tablet form, but it appears to be the only way it is administered.

**Comment by zhengj2007** [comment]
EUPATH:0000063 'artemether-lumefantrine drug product' is not used by any VEuPathDB datasets. 

The term was added for PRISM and has not been used anymore. I think we can deprecate the EuPath term and indicate it can be replaced with DRON:00032533. But it may not need to import DRON one.

**Comment by cstoeckert** [comment]
Agree to deprecate and import DrOn term if needed in future.
