### ISSUE TITLE
active ingredient: DRON vs RO

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#163]
Related to issue #162. We imported the complementary RO object properties 'active ingredient in' and 'has active ingredient'. 2 other ontologies imported them as well, but neither of them use this relation in axioms.

DRON on the other hand represents ['active ingredient'](http://purl.obolibrary.org/obo/DRON_00000028) as a role and uses this term in axioms for its drug product terms. For example, ['Fluconazole Oral Solution'](http://purl.obolibrary.org/obo/DRON_00031946) has an axiom that specifies [Fluconazole](http://purl.obolibrary.org/obo/CHEBI_46081) as active ingredient. This oral solution term and other DRON terms are used in PROVIDE and should be imported into VEuPath; this is a good reason to also import 'active ingredient' from DRON. I think DRON has the better definition as well.

**Comment by zhengj2007** [comment]
The RO relations are kind of shortcut relations as what logical axiom represented in DRON. The DRON one is not very friendly for retrieving the drugs that have a given active ingredient using DL query.

But it is fine to import the 'active ingredient' role from DRON.

**Comment by cstoeckert** [comment]
Discussed and agreed to go with RO 'has active ingredient' to link as needed.
