### ISSUE TITLE
VEuPath terms not used in the VEuPathDB datasets

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#166]
Following terms are not used in genomics, clinEpi and microbiomeDB datasets. Some of them may be used as controlled vocabulary of values of the variables or VectorBase datasets. Some terms may consider either as low priority or to be deprecated.

IRI | Type | Label
-- | -- | --
http://purl.obolibrary.org/obo/EUPATH_0000052 | AnnotationProperty | EuPathDB alternative term
http://purl.obolibrary.org/obo/EUPATH_0000112 | AnnotationProperty | EuPathDB definition
http://purl.obolibrary.org/obo/EUPATH_0001000 | AnnotationProperty | column order
http://purl.obolibrary.org/obo/EUPATH_0001007 | AnnotationProperty | datafile value
http://purl.obolibrary.org/obo/EUPATH_0000010 | Class | wall brick
http://purl.obolibrary.org/obo/EUPATH_0000022 | Class | household having electricity information
http://purl.obolibrary.org/obo/EUPATH_0000030 | Class | distance to health facility in km
http://purl.obolibrary.org/obo/EUPATH_0000038 | Class | diagnosis of uncomplicated malaria
http://purl.obolibrary.org/obo/EUPATH_0000042 | Class | diagnoses of complicated malaria with danger signs
http://purl.obolibrary.org/obo/EUPATH_0000045 | Class | severe malaria
http://purl.obolibrary.org/obo/EUPATH_0000050 | Class | routine clinical visit
http://purl.obolibrary.org/obo/EUPATH_0000051 | Class | human participant under investigation
http://purl.obolibrary.org/obo/EUPATH_0000053 | Class | dwelling ventilation
http://purl.obolibrary.org/obo/EUPATH_0000062 | Class | quinine drug product
http://purl.obolibrary.org/obo/EUPATH_0000063 | Class | artemether-lumefantrine drug product
http://purl.obolibrary.org/obo/EUPATH_0000088 | Class | diagnosis of uncomplicated malaria in the 1st trimester of pregnancy
http://purl.obolibrary.org/obo/EUPATH_0000089 | Class | diagnosis of asymptomatic microscopic parasitemia
http://purl.obolibrary.org/obo/EUPATH_0000093 | Class | dwelling information
http://purl.obolibrary.org/obo/EUPATH_0000098 | Class | ventilation function
http://purl.obolibrary.org/obo/EUPATH_0000099 | Class | dwelling facility
http://purl.obolibrary.org/obo/EUPATH_0000101 | Class | elevated temperature
http://purl.obolibrary.org/obo/EUPATH_0000102 | Class | temperature measurement datum
http://purl.obolibrary.org/obo/EUPATH_0000105 | Class | building material role
http://purl.obolibrary.org/obo/EUPATH_0000106 | Class | roof material role
http://purl.obolibrary.org/obo/EUPATH_0000107 | Class | wall material role
http://purl.obolibrary.org/obo/EUPATH_0000108 | Class | floor material role
http://purl.obolibrary.org/obo/EUPATH_0000109 | Class | dwelling facility role
http://purl.obolibrary.org/obo/EUPATH_0000111 | Class | floor brick
http://purl.obolibrary.org/obo/EUPATH_0000124 | Class | number of non-routine clinical visits
http://purl.obolibrary.org/obo/EUPATH_0000125 | Class | number of routine clinical visits
http://purl.obolibrary.org/obo/EUPATH_0000126 | Class | sample available information
http://purl.obolibrary.org/obo/EUPATH_0000128 | Class | peripheral blood mononuclear cell specimen
http://purl.obolibrary.org/obo/EUPATH_0000129 | Class | red blood cell specimen
http://purl.obolibrary.org/obo/EUPATH_0000130 | Class | average number of Plasmodium parasite-positive female Anopheles
http://purl.obolibrary.org/obo/EUPATH_0000131 | Class | average number of female Anopheles tested for Plasmodium parasite
http://purl.obolibrary.org/obo/EUPATH_0000132 | Class | average percent of Plasmodium parasite-positive female Anopheles
http://purl.obolibrary.org/obo/EUPATH_0000142 | Class | routine clinical visit date
http://purl.obolibrary.org/obo/EUPATH_0000145 | Class | antimalarial therapy given outside the study since last seen information
http://purl.obolibrary.org/obo/EUPATH_0000147 | Class | cause of participant death
http://purl.obolibrary.org/obo/EUPATH_0000148 | Class | clinical visit when sick
http://purl.obolibrary.org/obo/EUPATH_0000149 | Class | covered pit latrine without slab
http://purl.obolibrary.org/obo/EUPATH_0000153 | Class | days since a clinical visit with a malaria diagnosis
http://purl.obolibrary.org/obo/EUPATH_0000168 | Class | household bed asset
http://purl.obolibrary.org/obo/EUPATH_0000169 | Class | household bicycle asset
http://purl.obolibrary.org/obo/EUPATH_0000172 | Class | household cassette player asset
http://purl.obolibrary.org/obo/EUPATH_0000173 | Class | household chair asset
http://purl.obolibrary.org/obo/EUPATH_0000174 | Class | household clock asset
http://purl.obolibrary.org/obo/EUPATH_0000175 | Class | household cupboard asset
http://purl.obolibrary.org/obo/EUPATH_0000176 | Class | household electricity asset
http://purl.obolibrary.org/obo/EUPATH_0000177 | Class | household fixed phone asset
http://purl.obolibrary.org/obo/EUPATH_0000178 | Class | household mobile phone asset
http://purl.obolibrary.org/obo/EUPATH_0000180 | Class | household motorcycle or scooter asset
http://purl.obolibrary.org/obo/EUPATH_0000181 | Class | household radio asset
http://purl.obolibrary.org/obo/EUPATH_0000182 | Class | household refrigerator asset
http://purl.obolibrary.org/obo/EUPATH_0000183 | Class | household sofa asset
http://purl.obolibrary.org/obo/EUPATH_0000184 | Class | household table asset
http://purl.obolibrary.org/obo/EUPATH_0000185 | Class | household television asset
http://purl.obolibrary.org/obo/EUPATH_0000187 | Class | incident of malaria episode information
http://purl.obolibrary.org/obo/EUPATH_0000189 | Class | location of death
http://purl.obolibrary.org/obo/EUPATH_0000190 | Class | medical care outside the study clinic since last seen information
http://purl.obolibrary.org/obo/EUPATH_0000199 | Class | number of insecticide treated mosquito net(s) per person
http://purl.obolibrary.org/obo/EUPATH_0000206 | Class | plasma sample lost information
http://purl.obolibrary.org/obo/EUPATH_0000209 | Class | redraw of a symptom after clinical visit information
http://purl.obolibrary.org/obo/EUPATH_0000210 | Class | routine clinical visit for T-cell study
http://purl.obolibrary.org/obo/EUPATH_0000211 | Class | routine clinical visit with finger prick
http://purl.obolibrary.org/obo/EUPATH_0000212 | Class | routine clinical visit with venipuncture
http://purl.obolibrary.org/obo/EUPATH_0000213 | Class | routine clinical visit without any routine assessment done
http://purl.obolibrary.org/obo/EUPATH_0000214 | Class | screened air brick
http://purl.obolibrary.org/obo/EUPATH_0000220 | Class | uncovered pit latrine with slab
http://purl.obolibrary.org/obo/EUPATH_0000221 | Class | uncovered pit latrine without slab
http://purl.obolibrary.org/obo/EUPATH_0000222 | Class | unscreened air brick
http://purl.obolibrary.org/obo/EUPATH_0000254 | Class | drinking water from open public well
http://purl.obolibrary.org/obo/EUPATH_0000255 | Class | drinking water from open well in yard
http://purl.obolibrary.org/obo/EUPATH_0000261 | Class | drinking water from unprotected freshwater spring
http://purl.obolibrary.org/obo/EUPATH_0000275 | Class | ATCC number
http://purl.obolibrary.org/obo/EUPATH_0000313 | Class | single catch entomological measurement datum
http://purl.obolibrary.org/obo/EUPATH_0000314 | Class | scheduled clinical visit
http://purl.obolibrary.org/obo/EUPATH_0000315 | Class | unscheduled clinical visit
http://purl.obolibrary.org/obo/EUPATH_0000339 | Class | dwelling animal information
http://purl.obolibrary.org/obo/EUPATH_0000352 | Class | job role
http://purl.obolibrary.org/obo/EUPATH_0000353 | Class | economic activity
http://purl.obolibrary.org/obo/EUPATH_0000354 | Class | primary economic activity
http://purl.obolibrary.org/obo/EUPATH_0000356 | Class | primary economic activity description
http://purl.obolibrary.org/obo/EUPATH_0000357 | Class | secondary economic activity description
http://purl.obolibrary.org/obo/EUPATH_0000369 | Class | community name
http://purl.obolibrary.org/obo/EUPATH_0000370 | Class | study location name
http://purl.obolibrary.org/obo/EUPATH_0000371 | Class | first line malaria medication
http://purl.obolibrary.org/obo/EUPATH_0000372 | Class | second line malaria medication
http://purl.obolibrary.org/obo/EUPATH_0000386 | Class | information on place visited during a trip
http://purl.obolibrary.org/obo/EUPATH_0000388 | Class | information on travel before malaria
http://purl.obolibrary.org/obo/EUPATH_0000392 | Class | information on contact with malaria
http://purl.obolibrary.org/obo/EUPATH_0000393 | Class | information on participant status at visit
http://purl.obolibrary.org/obo/EUPATH_0000403 | Class | proximity to case dwelling datum
http://purl.obolibrary.org/obo/EUPATH_0000406 | Class | clinic location
http://purl.obolibrary.org/obo/EUPATH_0000408 | Class | division number
http://purl.obolibrary.org/obo/EUPATH_0000420 | Class | information on where malaria diagnosed in last 12 months
http://purl.obolibrary.org/obo/EUPATH_0000421 | Class | number of asexual parasite
http://purl.obolibrary.org/obo/EUPATH_0000434 | Class | primary health center name
http://purl.obolibrary.org/obo/EUPATH_0000436 | Class | information that there is no illness
http://purl.obolibrary.org/obo/EUPATH_0000453 | Class | location zone number
http://purl.obolibrary.org/obo/EUPATH_0000484 | Class | diagnosis of asymptomatic parasitemia
http://purl.obolibrary.org/obo/EUPATH_0000485 | Class | diagnosis of submicroscopic parasitemia
http://purl.obolibrary.org/obo/EUPATH_0000495 | Class | information on whether hive treated with tetracyline
http://purl.obolibrary.org/obo/EUPATH_0000496 | Class | information on whether specimen from mother or child
http://purl.obolibrary.org/obo/EUPATH_0000591 | Class | host organism
http://purl.obolibrary.org/obo/EUPATH_0000641 | Class | mouse cage number
http://purl.obolibrary.org/obo/EUPATH_0000736 | Class | propagation
http://purl.obolibrary.org/obo/EUPATH_0000756 | Class | pathogen organism
http://purl.obolibrary.org/obo/EUPATH_0000760 | Class | Candida albicans strain
http://purl.obolibrary.org/obo/EUPATH_0000762 | Class | presence of organism in specimen
http://purl.obolibrary.org/obo/EUPATH_0000787 | Class | groin lesion score
http://purl.obolibrary.org/obo/EUPATH_0000788 | Class | axillary lesion score
http://purl.obolibrary.org/obo/EUPATH_0000789 | Class | pinna lesion score
http://purl.obolibrary.org/obo/EUPATH_0000791 | Class | blood meal source role
http://purl.obolibrary.org/obo/EUPATH_0000792 | Class | lethal insecticide time 50
http://purl.obolibrary.org/obo/EUPATH_0000793 | Class | finding of death from COVID-19
http://purl.obolibrary.org/obo/EUPATH_0000794 | Class | treatment information
http://purl.obolibrary.org/obo/EUPATH_0000795 | Class | information on whether assay performed
http://purl.obolibrary.org/obo/EUPATH_0000796 | Class | sporozoite detection assay
http://purl.obolibrary.org/obo/EUPATH_0010096 | Class | first respiratory rate measurement datum
http://purl.obolibrary.org/obo/EUPATH_0011802 | Class | information on microscopy assay
http://purl.obolibrary.org/obo/EUPATH_0015033 | Class | information on drinking water piped into dwelling
http://purl.obolibrary.org/obo/EUPATH_0015035 | Class | information on drinking water piped into yard
http://purl.obolibrary.org/obo/EUPATH_0000060 | ObjectProperty | may treat

**Comment by cstoeckert** [comment]
Need to review to make sure ones needed by VectorBase are not removed for example.

**Comment by cstoeckert** [comment]
Some of these terms are needed for PopBio (e.g., http://purl.obolibrary.org/obo/EUPATH_0000792)
Need to check popbio-term-usage-VB-2019-08 - master list.

**Comment by johnwjudkins** [comment]
We should probably keep these:
IRI | Type | Label | JJ comments
-- | -- | -- | --
http://purl.obolibrary.org/obo/EUPATH_0000051 | Class | human participant under investigation | referenced in axioms
http://purl.obolibrary.org/obo/EUPATH_0000762 | Class | presence of organism in specimen | created as category for detection data terms
http://purl.obolibrary.org/obo/EUPATH_0000791 | Class | blood meal source role | requested from VB
http://purl.obolibrary.org/obo/EUPATH_0000792 | Class | lethal insecticide time 50 | requested from VB
http://purl.obolibrary.org/obo/EUPATH_0000793 | Class | finding of death from COVID-19 | requested from VB
http://purl.obolibrary.org/obo/EUPATH_0000794 | Class | treatment information | created to balance the ICE hierarchy
http://purl.obolibrary.org/obo/EUPATH_0000795 | Class | information on whether assay performed | created to balance the ICE hierarchy
http://purl.obolibrary.org/obo/EUPATH_0000796 | Class | sporozoite detection assay | was this requested from VB?

**Comment by zhengj2007** [comment]
EUPATH_0000796 sporozoite detection assay

Do not find the term in the Pop Bio master sheet.
https://docs.google.com/spreadsheets/d/1vlj-4NTpKJNjj-eU-JgJr6d2OHXiGwiK14InUeNmA7c/edit#gid=1074853426

**Comment by cstoeckert** [comment]
OK to obsolete the terms in the schedule to deprecate file in templates.

**Comment by johnwjudkins** [comment]
@zhengj2007 Can we close this?

**Comment by zhengj2007** [comment]
Yes. Please go ahead to close the issue.
