### ISSUE TITLE
Proposed changes to import and build of VEuPathDB Ontology

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#170]
We started with a BRC-based view. We still want to include all these terms but to improve the build and use of ROBOT, propose to import these terms as a module rather than start with a view.

Also want to import the OBO metadata ontology to get the standard annotation properties.

Will begin implementing after next VEuPathDB ontology release.

**Comment by zhengj2007** [comment]
changes have been made and merged to master
