### ISSUE TITLE
2 axioms for upcoming release

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#173]
This is consistent with OBI's use of 'life cycle stage' in the axiom for [this term](http://purl.obolibrary.org/obo/OBI_0001328).

ID | label | subclass axiom
-- | -- | --
EUPATH:0000528 | gametocyte detection assay | realizes some ('measurand role' and ('role of' some ('participates in' some 'gametocyte stage')))
EUPATH:0000796 | sporozoite detection assay | realizes some ('measurand role' and ('role of' some ('participates in' some 'sporozoite stage')))

Or should these be submitted to OBI?

**Comment by cstoeckert** [comment]
submitting gametocyte assay to OBI but don't need sporozoite assay.
