### ISSUE TITLE
medication material

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#176]
This links back to https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/160 and  https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/130. We decided to submit 'medication role' to OGMS who accepted it, then we decided we didn't need it since we already had 'clinical drug role'.

However, 'medication material' has children and is defined based on 'medication role', and OGMS decided 'medication role' is important and distinct from 'clinical drug role' (but OGMS does not have a recent release).

For now, should we keep 'medication role'? We could import it from OBIB.

**Comment by cstoeckert** [comment]
Discussed. Just wait until OGMS releases with 'medication role' and replace then.

**Comment by cstoeckert** [comment]
This is ready too as OGMS and OBIB new releases are out.

**Comment by cstoeckert** [comment]
taken care of by import term PR.
