### ISSUE TITLE
2 'blood urea concentration' terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#177]
EUPATH:0023010 and EUPATH:0021227 have the same labels, definitions, and axioms. This redundancy happened because 2 different ClinEpi projects had terms for blood urea concentration, but one expressed it in blood urea nitrogen (BUN), while the other was blood urea concentration. These are different only in that one is a fraction of the other (amount of urea nitrogen is a fraction of amount of urea). I think the best resolution is to deprecate EUPATH:0021227 (and make another release candidate).

**Comment by cstoeckert** [comment]
Discussed and agreed that although interconvertable, BUN and blood urea concentration are two different entities and should keep as two terms. Will fix label and definition to specifically describe BUN - blood urea nitrogen.
