### ISSUE TITLE
terms with same label in release candidate

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#178]
EUPATH:0043049	trap for emerging adult arthropods
OBI:0003008	trap for emerging adult arthropods

Should deprecate EUPATH one.

EUPATH:0021227	blood urea concentration
EUPATH:0023010	blood urea concentration

Should merge the terms

**Comment by cstoeckert** [comment]
blood urea concentration addressed in #177

**Comment by cstoeckert** [comment]
These have both been addressed in the 2021-04-28 candidate release
