### ISSUE TITLE
NTR: has execution

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#181]
There is a common relationship between a planned specification and a planned process. This is represented in the axiom:

realizes some (concretizes some 'plan specification')

Would it be useful to have a new object property to simplify this axiom? I submit the following:

label: has execution
definition: A relation between a plan specification and a process that realizes a concretization of the same plan specification.
domain: plan specification
range: planned process
inverse: 'execution of'
example of usage: The relation between a study design and a study design execution.

If this is useful, I am open to other suggestions for the label, and I could submit the term to RO (or OBI or COB instead).

**Comment by zhengj2007** [comment]
Please see this tracker submitted many years ago:
https://github.com/obi-ontology/obi/issues/636

**Comment by cstoeckert** [comment]
Agree to use this (and other terms) from COB.

**Comment by cstoeckert** [comment]
Want the inverse http://purl.obolibrary.org/obo/COB_0000016 executed by which would be used for 'plan specification' 'executed by' 'planned process'
