### ISSUE TITLE
Proposed axiom changes to VEuPath terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#182]
These terms about diarrhea treatment have nested axioms. I am creating this tracker item to propose simpler axioms, which also involves parent changes for the existing terms and adding one new term that is currently a placeholder but can serve as parent for the existing terms.

Unshaded rows: current parents & axioms
Shaded rows: proposed parents & axioms

ID | current parent & proposed parent | current axiom & proposed axiom | comment
-- | -- | -- | --
EUPATH:0015669 |  |  | I will add this placeholder to the ontology as 'information on diarrhea treatment'
EUPATH:0015669 | treatment information | mentions some (('is substance that treats' some diarrhea) and ('has role' some 'medication role')) |  
EUPATH:0010378 | treatment information | mentions some (treatment and (realizes some ('participant under investigation role' and ('role of' some ('human participant under investigation' and ('bearer of' some diarrhea))))) and (precedes some 'health care encounter')) |  
EUPATH:0010378 | information on diarrhea treatment | is about' some (treatment and precedes some 'health care encounter') |  
EUPATH:0010391 | treatment information | mentions some     (treatment     and (realizes some         ('participant under investigation role'         and ('role of' some             ('human participant under investigation'             and ('bearer of' some diarrhea)))))     and (realizes some (concretizes some 'health care prescription'))) |  
EUPATH:0010391 | information on diarrhea treatment | is about' some (treatment and realizes some (concretizes some 'health care prescription')) | or use COB_0000086 as object property here
EUPATH:0010390 | treatment information | mentions some     (treatment     and (realizes some         ('participant under investigation role'         and ('role of' some             ('human participant under investigation'             and ('bearer of' some diarrhea)))))     and ('occurs in' some 'health care facility')) |  
EUPATH:0010390 | information on diarrhea treatment | is about' some (treatment and ('occurs in' some 'health care facility')) |

**Comment by cstoeckert** [comment]
Go ahead and make changes for a review in a PR
