### ISSUE TITLE
Add annotation properties needed for EDA to VEuPathDB ontology

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#185]
The Exploratory data analysis (EDA) workspace has led to changes in the way variables will be displayed on the ClinEpiDB and VEuPathDB web sites. Annotation properties describing default units and data ranges have been created for the web display owl files. We will add them to the VEuPathDB ontology so they can be properly defined and managed.

**Comment by cstoeckert** [comment]
From https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/blob/master/src/ID_range.txt
In-house annotation property: EUPATH_0001000- EUPATH_0001100
    - EUPATH_0001006 - replaces
    - EUPATH_0001008 - unitLabel
    - EUPATH_0001009 - unitIRI 
    - EUPATH_0001010 - dataSet
    - EUPATH_0001011 - repeated
    - EUPATH_0001012 - is_featured
    - EUPATH_0001013 - hidden
    - EUPATH_0001014 - scale
    - EUPATH_0001015 - is_temporal
    - EUPATH_0001016 - timeKey

**Comment by sweverschulman** [comment]
need to add the follow to the above list

**Comment by zhengj2007** [comment]
- EUPATH_0001006 - replaces
- EUPATH_0001008 - unitLabel
- EUPATH_0001009 - unitIRI
- EUPATH_0001010 - dataSet
- EUPATH_0001011 - repeated
- EUPATH_0001012 - is_featured
- EUPATH_0001013 - hidden
- EUPATH_0001014 - scale
- EUPATH_0001015 - is_temporal
- EUPATH_0001016 - mergeKey
- EUPATH_0001017 - defaultDisplayRangeMin
- EUPATH_0001018 - defaultDisplayRangeMax
- EUPATH_0001019 - defaultBinWidth

**Comment by cstoeckert** [comment]
Go ahead and add these.

**Comment by cstoeckert** [comment]
The listed properties were confirmed at the July 1, 2021 ClinEpiDB meeting.
