### ISSUE TITLE
NTR: Cluster/Study Grouping and Community

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#186]
ClinEpi has requested separate terms to capture Cluster/Study Grouping and Community. Community will just refer to a physical grouping. 
Proposed definitions from Danica:
Cluster = groups of participants (as opposed to individual participants) that are randomized to receive an intervention
Compounds = multiple households (typically 3 to 10 in Bangladesh), usually comprised of blood relatives, who share a common courtyard and infrastructure (such as a latrine).

**Comment by cstoeckert** [comment]
We have community http://purl.obolibrary.org/obo/EUPATH_0022001 "A geographic location that is either a city or an area containing settlements where the inhabitants share a common trait." Does common trait include infrastructure? Will this work for 'compound'? Do we need 'community information' for EDA entity 'community' node that is about a community/compound?

We have cluster study group role that seems to fit the proposed definition. Do we need something more like 'cluster information' which is about participants with a shared cluster study group role?

**Comment by sweverschulman** [comment]
Category type term. One that catches the information about cluster/community/compounds - like household information.

**Comment by cstoeckert** [comment]
study cluster information: An information content entity about the groups of participants that are randomized to receive an intervention in a trial.

community information:  An information content entity about the multiple households that share a location and a common trait such as infrastructure.

**Comment by zhengj2007** [comment]
The term 'study cluster information' (EUPATH_0000797) is not used in any projects. 

Comments from Sheena: Discussed with ClinEpi Outreach and decided to change "Cluster level information" to "Health center level information" to better match how we have "Village level information" and "School level information" when the clusters are based around Villages and Schools.

So, we may keep the term as the parent of the specific cluster terms used in the clinEpi.

**Comment by zhengj2007** [comment]
Keep 'study cluster information' (EUPATH_0000797), add "Health center level information", "Village level information" and "School level information" as its subClass. Will confirm with outreach team.

**Comment by johnwjudkins** [comment]
Following up with Outreach - please comment on whether you agree with Jie's suggestions.

**Comment by zhengj2007** [comment]
Discussed on Mar 18 clinEpi meeting. Confirmed with the outreach team that we will keep 'study cluster information'  and add "Health center level information", "Village level information" and "School level information" as its subClass in the ontology.

**Comment by zhengj2007** [comment]
@johnwjudkins Could you please add "Health center level information", "Village level information" and "School level information" with parent and definitions in the placeholder sheet? Thanks!

**Comment by zhengj2007** [comment]
@johnwjudkins Could you please confirm that you have added "Health center level information", "Village level information" and "School level information" in the placeholder sheet?

**Comment by johnwjudkins** [comment]
@zhengj2007 They are in the placeholder sheet. However, they are undefined. They all have the parent Community, which is identified in the sheet.

**Comment by zhengj2007** [comment]
@johnwjudkins Sounds good. The parent should be  'study cluster information'.
