### ISSUE TITLE
NTR: laboratory population

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#187]
Used to describe the "material type" of PopBio samples that represent laboratory colonies of vector species.

Could be a child of [OBI population](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000181) 

Or maybe a child of [OBI processed material](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000040&viewMode=All&siblings=false#) - similar to 'cell culture'

Or maybe just a VEuPath term - I don't mind!

**Comment by cstoeckert** [comment]
We'll make this a child of OBI population. Something like:
"A population where the collection of individuals is located and maintained in a laboratory or research facility." Does that work @bobular ? If so, we can submit to OBI.

**Comment by bobular** [comment]
Sounds great to me @cstoeckert - thanks

**Comment by bobular** [comment]
Any update from OBI?  Thanks

**Comment by cstoeckert** [comment]
Submitted to OBI https://github.com/obi-ontology/obi/issues/1370

**Comment by cstoeckert** [comment]
A question came up about this at OBI. https://github.com/obi-ontology/obi/issues/1370 "Would this fit as a research resource ID (https://scicrunch.org/resources)?"
I think the question is whether a laboratory population as we are defining it would qualify as a research resource (and could be given one of their IDs). @bobular What do you think?

**Comment by bobular** [comment]
I don't really understand.  Discuss tomorrow?

**Comment by cstoeckert** [comment]
Has been added to obi-dev as OBI_0003086. see https://github.com/obi-ontology/obi/pull/1392
