### ISSUE TITLE
NTR: 'Melanoconion' taxonomic term

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#188]
'Melanoconion' (VBsp_0002995)

unmapped in the master sheet

attn @SAK22

**Comment by cstoeckert** [comment]
@bobular @SAK22 can you provide a parent class for this? 
I found this http://entnemdept.ufl.edu/creatures/misc/flies/culex_pilosus.htm
Is this the same thing? How does it relate? Thanks

**Comment by SAK22** [comment]
@cstoeckert we would need the parent of this species you link to. So Culex pilosis is a species in the subgenus Melanoconion. Melanoconion is a subgenus of the genus Culex.

**Comment by cstoeckert** [comment]
Thanks @SAK22 
Is this it? http://purl.obolibrary.org/obo/NCBITaxon_53535 
we can add it to the list of terms to import.

**Comment by SAK22** [comment]
@cstoeckert yes I think that is correct!

**Comment by cstoeckert** [comment]
@SAK22 great. We'll take care of getting it in the VEuPathDB ontology. Can you update the PopBio master sheet to indicate that you can use NCBITaxon_53535 for 'Melanoconion' (VBsp_0002995)? Thanks!

**Comment by bobular** [comment]
> Can you update the PopBio master sheet to indicate that you can use NCBITaxon_53535 for 'Melanoconion'

Done

**Comment by SAK22** [comment]
Thanks Bob!

From: bobular ***@***.***>
Date: Thursday, 10 June 2021 at 23:05
To: VEuPathDB-ontology/VEuPathDB-ontology ***@***.***>
Cc: Kelly, Sarah A ***@***.***>, Mention ***@***.***>
Subject: Re: [VEuPathDB-ontology/VEuPathDB-ontology] NTR: 'Melanoconion' taxonomic term (#188)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Can you update the PopBio master sheet to indicate that you can use NCBITaxon_53535 for 'Melanoconion'

Done

**Comment by johnwjudkins** [comment]
This term will be added in https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/pull/202

**Comment by cstoeckert** [comment]
PR #202 with this term has been merged so closing.
