### ISSUE TITLE
NTR: 'mixed species'

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#189]
'mixed species' (VBcv_0001005)

This term has been used in at least one dataset (VBP0000155) to represent the results of blood meal host assays done on many samples but reported as a percentage.

A typical result would be
```
human  25%
animal  75%
mixed species 0%
```
meaning no mixed blood meals, or
```
human  25%
animal  25%
mixed species 50%
```
meaning half of the assayed insects had fed from both sources

If we had the results for individual mosquitoes we wouldn't need the mixed species term.  We could think about a new term, or Sarah and I could think again (probably for the fifth time) about how to represent this dataset.

**Comment by cstoeckert** [comment]
@bobular Since this is used to report the percentage of mixed species, can this be a data item rather than an aggregate of species? i.e.,
'proportion of mixed species in blood meal' : A measurement data item that is the output of an assay or set of assays to determine representation of organism source for blood meals from a group of arthropods and reflects the proportion of results where there is more than one blood meal source.

**Comment by bobular** [comment]
This might mean that we need terms for "proportion of human in blood meal", "proportion of hispid cotton rat in blood meal" and so on for all the species.

I wonder if we can just go with [PATO mixed](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002122) for now?

**Comment by bobular** [comment]
It affects just three projects and only 22 blood meal assays out of 12.4k - it's not worth sweating over IMO!

https://vectorbase.org/popbio-map/web/?blood_meal_host=mixed%20species&view=meal&zoom_level=2&center=-12.726084296948184,86.66015625000001&summarizeBy=Project&grid=true&shared_link=true&limitTerms=true

**Comment by cstoeckert** [comment]
@bobular What about http://purl.obolibrary.org/obo/PCO_0000029 multi-species collection of organisms ?

**Comment by bobular** [comment]
Yes that would work - does it need importing into VEuPath ontology?

**Comment by cstoeckert** [comment]
Yes need to import for next release.
