### ISSUE TITLE
Deprecated terms without indicating which terms they were replaced by

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#191]
Deprecated EuPath   Term ID | Display Label | Replaced Term ID | Replaced Term Label
-- | -- | -- | --
EUPATH:0000340 | Travel details | OMRSE:00000142 | human traveling information
EUPATH:0000345 | Education level | OMRSE:00002045 | highest level of education data item
EUPATH:0000368 | Garbage disposal | ENVO:01001260 | waste disposal process

Better to add the replaced terms in

**Comment by cstoeckert** [comment]
Agree with adding annotation property 'replaced by' for these. Should be part of our SOP.

**Comment by zhengj2007** [comment]
changes merged to master
