### ISSUE TITLE
ID of Deprecated term 'obsolete_antimalarial'

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#192]
Deprecated term 'obsolete_antimalarial' with ID, EUPATH_0000686.

EUPATH_0000686 is assigned to term 'Hygiene' and used in ClinEpi projects. 

Shall we reassign a new ID to 'Hygiene' or delete 'obsolete_antimalarial'  from the ontology?

**Comment by cstoeckert** [comment]
Even though 'Hygiene' is a placeholder term it is widely used in ClinEpi now.
Since nothing is likely to break if just get rid of obsolete_antimalarial, OK to just drop and so the placehold 'hygeine' will uniquely have that ID.

**Comment by zhengj2007** [comment]
changes merged to master.
