### ISSUE TITLE
Deprecated term EUPATH_0000594

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#194]
Term EUPATH_0000594 'information of specimen obtained from the mother or chid' is used in microbiomeDB. The term is deprecated in the VEuPathDB ontology and replaced by EUPATH_0000496 'information on whether specimen from mother or child', which is tagged as 'scheduled for obsoletion on or after'. 

Shall we deprecate EUPATH_0000496 and keep EUPATH_0000594 in the ontology since it is used in the microbiomeDB?

**Comment by cstoeckert** [comment]
So need to put things back the way they were so that data loaded by MicrobiomeDB has an active ontology ID.

**Comment by zhengj2007** [comment]
Changes merged to master.
