### ISSUE TITLE
Label consistency for organism identification assay terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#195]
EUPATH:0000724 'stool test for microorganisms' should be 'feces microbiology assay' (to match OBI), should have 'organism identification assay' as parent, and should be defined as "An organism identification assay that identifies a microorganism in a feces specimen."

EUPATH:0000538 'parasite detection assay' should be under either 'pathogen detection assay' or 'organism identification assay'. 

I noticed these while constructing the assay template.

**Comment by cstoeckert** [comment]
Make 'stool test for microorganisms' an alternative label.

'pathogen detection assay' we added and has logical axiom of objective to detect organism.
Need to fix in OBI. If we make this a defined class then we can assert parasite assay as organism identification assay and infer the other.

Will make an OBI issue to adjust 'pathogen detection assay'

**Comment by johnwjudkins** [comment]
https://github.com/obi-ontology/obi/issues/1360

**Comment by cstoeckert** [comment]
These were fixed in OBI and imported (deprecating VEuPath terms)
