### ISSUE TITLE
Reverse the deprecation of EUPATH:0000574 NLST Clade

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#199]
EUPATH:0000574 NLST Clade is deprecated in the VEuPathDB ontology. The term is still needed by genomics site. 

Need to reverse the deprecation.

**Comment by cstoeckert** [comment]
Need to get a definition. Check with VEuPathDB outreach.

**Comment by zhengj2007** [comment]
The term used in genomics study EUSTDY0057, calbSC5314_HTS_SNP_Hirakawa_HTS_SNP_RSRC and calbSC5314_copyNumberVariations_Hirakawa_HTS_SNP_RSRC datasets.

**Comment by zhengj2007** [comment]
https://redmine.apidb.org/issues/44873

**Comment by cstoeckert** [comment]
Need to remove from obsolete table. Fix label. Give definition.

**Comment by johnwjudkins** [comment]
Assigning to @cstoeckert for definition.

**Comment by cstoeckert** [comment]
label: multilocus sequence type clade
alternative label: MLST clade
Definition: A clade name based on multilocus sequence typing (MLST), a widely used approach to microbial isolate differentiation for epidemiological purposes.
Definition source: https://pubmed.ncbi.nlm.nih.gov/14605179/
parent class: APOLLO_SV_00000232 'clade name'
Example of usage: "Clades were assigned based on multilocus sequence type (MLST) analysis of seven loci or prior work reporting fingerprint clades" Figure 1 in https://genome.cshlp.org/content/25/3/413/F1.expansion.html
