### ISSUE TITLE
hemoglobin level

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#200]
We used 'hemoglobin level' (http://purl.obolibrary.org/obo/EUPATH_0000047) in clinEpi projects. Shall it be replaced by 
http://purl.obolibrary.org/obo/CMO_0000026  'blood hemoglobin level'

**Comment by johnwjudkins** [comment]
Makes sense to me.

**Comment by cstoeckert** [comment]
Let's go with CMO term.
