### ISSUE TITLE
Replace 'medication role' with OGMS term

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#207]
OGMS included 'medication role' in their latest release with the same definition as OBIB/VEuPath. So I will make a pull request replacing the OBIB term with the OGMS term in imports and deprecating the VEuPath term.

**Comment by cstoeckert** [comment]
Waiting on OGMS to make a release with merged owl. Expect in a couple weeks with help from Jie.

**Comment by zhengj2007** [comment]
The term is also used in the imported OBIB. Need wait that OBIB replace the term with OGMS one. See the tracker: https://github.com/biobanking/biobanking/issues/79

**Comment by cstoeckert** [comment]
taken care of with a merge PR already.
