### ISSUE TITLE
NTR: MicrobiomeDB terms needed for EDA

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#208]
MicrobiomeDB has requested the listed terms to be used in the Exploratory Data Analysis (EDA) workspace being developed:
* Measurement of  relative abundance of organisms
* Measurement of  relative abundance of organisms grouped at the level of kingdom
* Measurement of  relative abundance of organisms grouped at the level of phylum
* Measurement of  relative abundance of organisms grouped at the level of class
* Measurement of  relative abundance of organisms grouped at the level of  orders
* Measurement of  relative abundance of organisms grouped at the level of family
* Measurement of  relative abundance of organisms grouped at the level of genus
* Measurement of  relative abundance of organisms grouped at the level of species
* Alpha diversity
* Alpha diversity, Shannon
* Alpha diversity, inverse Simpson
* Functional profiling
* Pathway abundance
* Pathway coverage
* Level 4 EC abundance

**Comment by cstoeckert** [comment]
The requested terms are a combination of analyses (e.g., relative abundance analysis) and outputs of those analyses (e.g., relative abundance of kingdom data item). 

- label: relative taxonomic abundance analysis
- definition: A data transformation of input sequence data to obtain the fraction of relative abundance of organisms.

- label: relative abundance of kingdom data
- definition: A data item that is the output of a relative taxonomic abundance analysis for organisms grouped at the level of kingdom.

- label: relative abundance of phylum data
- definition: A data item that is the output of a relative taxonomic abundance analysis for organisms grouped at the level of phylum.

- and so on for the other taxonomic groupings.

- label: alpha diversity taxonomic analysis
- definition: A data transformation of input sequence data to obtain a mean species diversity.

**Comment by cstoeckert** [comment]
label: metagenome pathway and function analysis
definition: A data transformation of metagenome input sequence data involving mapping to genes with full Enzyme Commision (EC) number enzyme classifications and calculation of pathways.

label: 4th level EC metagenome abundance data
definition: A data item that is the output of a metagenome pathway and function analysis for the number of copies of genes annotated at the finest (4th level) EC classification.

label: metagenome enzyme pathway abundance data
definition: A data item that is the output of a metagenome pathway and function analysis for the number of copies of a pathway defined by EC classifications. 

label: metagenome enzyme pathway coverage data
definition: A data item that is the output of a metagenome pathway and function analysis for gene coverage in a pathway defined by EC classifications.

**Comment by zhengj2007** [comment]
I think following label should add as 'alternative label' in the ontology.

> * Measurement of  relative abundance of organisms
> * Measurement of  relative abundance of organisms grouped at the level of kingdom
> * Measurement of  relative abundance of organisms grouped at the level of phylum
> * Measurement of  relative abundance of organisms grouped at the level of class
> * Measurement of  relative abundance of organisms grouped at the level of  orders
> * Measurement of  relative abundance of organisms grouped at the level of family
> * Measurement of  relative abundance of organisms grouped at the level of genus
> * Measurement of  relative abundance of organisms grouped at the level of species
> * Alpha diversity
> * Alpha diversity, Shannon
> * Alpha diversity, inverse Simpson
> * Functional profiling
> * Pathway abundance
> * Pathway coverage
> * Level 4 EC abundance

**Comment by cstoeckert** [comment]
The proposed alternative labels confuse the analysis method with the data output from the analysis. I'd like to avoid that.

**Comment by zhengj2007** [comment]
It seems we are using the ontology term labels in the microbiome.owl rather than the labels shown below. So, please ignore my comments on adding them as the alternative terms in VEuPathDB ontology.


> MicrobiomeDB has requested the listed terms to be used in the Exploratory Data Analysis (EDA) workspace being developed:
> 
> * Measurement of  relative abundance of organisms
> * Measurement of  relative abundance of organisms grouped at the level of kingdom
> * Measurement of  relative abundance of organisms grouped at the level of phylum
> * Measurement of  relative abundance of organisms grouped at the level of class
> * Measurement of  relative abundance of organisms grouped at the level of  orders
> * Measurement of  relative abundance of organisms grouped at the level of family
> * Measurement of  relative abundance of organisms grouped at the level of genus
> * Measurement of  relative abundance of organisms grouped at the level of species
> * Alpha diversity
> * Alpha diversity, Shannon
> * Alpha diversity, inverse Simpson
> * Functional profiling
> * Pathway abundance
> * Pathway coverage
> * Level 4 EC abundance
