### ISSUE TITLE
NTR: sporozoite and gametocyte

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#213]
We already import the sporozoite and gametocyte terms from OPL, but having terms for the cells themselves could simplify axiom development (e.g. 'gametocyte detection assay').

label | definition | equivalent axiom
-- | -- | --
sporozoite | A parasite organism in the sporozoite stage. | ('parasite organism' and ('participates in' some 'sporozoite stage'))
gametocyte | A parasite organism in the gametocyte stage. | ('parasite organism' and ('participates in' some 'gametocyte stage'))

That last definition is based on an assumption that a gametocyte is an organism rather than a germ cell _of_ an organism; I'm not certain which it is.

EDIT: These may be appropriate for OPL.

**Comment by cstoeckert** [comment]
discussed and recognized that we don't want general terms. These organism specific terms can be used for the detection assays whose labels should be made organism-specific e.g, Plasmodium gametocyte assay.
