### ISSUE TITLE
NTR: terms for outputs of blood, milk, urine, etc. tests

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#214]
Example for blood:
Label: blood test datum
Definition: A measurement datum that is the specified output of a blood test.
Equivalent axiom: 'measurement datum' and is_specified_output_of some 'blood test'.

Similarly for milk, feces, urine. These would be children of 'measurement datum' (allowing for categorical/count/scalar values). 'blood test datum' would be the parent of the terms that are children of 'Blood test' in ClinEpi (and so on), thus preventing hundreds of terms from having 'measurement datum' as parent; these terms would inherit the axiom defining 'blood test datum' as the output of a blood test.  'blood test datum' would also be analogous to the term labeled 'Raw test result for blood' in ClinEpi, but for the output of a laboratory test instead of a microbiology test.

**Comment by cstoeckert** [comment]
Submit to OBI at least to check with them.

**Comment by cstoeckert** [comment]
blood assay is in OBI. Still need to submit / check with OBI. Don't need to wait on OGMS as these aren't necessarily clinical.

**Comment by zhengj2007** [comment]
Is all the blood test results measurement datum? I think it could be boolean value, like positive, negative. How about change the definition to 'a data item that is the specified output of a blood test.'?

**Comment by johnwjudkins** [comment]
Since a blood test is an assay, the output is always a measurement datum, which would include both categorical and scalar measurement data.

Since OBI had concerns about ending up with parallel hierarchies, I should draw up a more specific hierarchy showing how these data terms would be arranged. I should also do this for microbiology test data terms as children of 'organism identification datum'. It will look as we discussed where a data item has an axiom specifying an assay that produced it and an axiom specifying the identified organism.
