### ISSUE TITLE
Terms to add to VEuPathDB: pyrethroid and maybe more

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#221]
- [ ] 'pyrethroid insecticide` CHEBI:26413 ([spreadsheet](https://docs.google.com/spreadsheets/d/1vlj-4NTpKJNjj-eU-JgJr6d2OHXiGwiK14InUeNmA7c/edit#gid=1006114387&range=942:942))

**Comment by johnwjudkins** [comment]
It's in the latest release: http://www.ontobee.org/ontology/EUPATH?iri=http://purl.obolibrary.org/obo/CHEBI_26413

**Comment by bobular** [comment]
Oh, cool.  I should have checked, duh!

**Comment by cstoeckert** [comment]
Sounds like this is taken care of so closing but reopen if I missed something.
