### ISSUE TITLE
NTR: 'Obsolete class' class (as in OBI)

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#222]
I noticed this while working on https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/pull/217 - OBI has an 'Obsolete class' with IRI http://www.geneontology.org/formats/oboInOwl#ObsoleteClass as a parent to their deprecated classes; their template for obsolete terms also uses 'Obsolete class'. We have many of our own deprecated terms, so do we want the 'Obsolete class', or do we want to continue placing deprecated terms under owl:Thing, or some other option?

**Comment by cstoeckert** [comment]
The main benefit of having a parent obsolete class is it makes viewing the ontology less cumbersome for example in Protege. I think it's a nice addition and worth reusing the same IRI as OBI but not essential.
