### ISSUE TITLE
Some SYMP terms not needed in the ontology

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#224]
There are a few SYMP terms in the ontology that are not used in any project or could be replaced.

abscess (SYMP:0000672): No project of ours even references abscess.

underweight (SYMP:0000475), wasting (SYMP:0000174): These are related to the terms Underweight and Wasted in ClinEpi, but those are not symptom terms; they are Anthropometry terms which can be defined based on a combination of weight, height, and age data, so these SYMP terms are not needed.

cough (SYMP:0000614): This is used in a project, but we may want to replace it with HP:0012735 for consistency, since 'Barking cough' is from HP.

**Comment by cstoeckert** [comment]
DIscussed July 28, 2021. Agree with dropping unused SYMP terms (check across all projects) and use HP cough in place of SYMP cough so avoid mixed hierarchy.

**Comment by johnwjudkins** [comment]
Merged, closing.
