### ISSUE TITLE
Terms to import

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#226]
These are terms that can serve as the object of axioms for ICE terms for: diagnoses, autopsy report, reason brought to intensive care.

label | ID | context in ClinEpi
-- | -- | --
hyperbilirubinemia | HP_0002904 | diagnosis
Feeding difficulties | HP_0011968 | 'Difficulty feeding' as reason brought to NICU
Coldness | HP_0033850 | 'Cold to touch' as reason brought to NiCU
apnea | HP_0002104 | value for 'Contributing cause of death'
congenital malformation | OGMS_0000089 | value for 'Contributing cause of death'
hypothermia | HP_0002045 | symptom and cause of death
Myocardial infarction | HP_0001658 | symptom
meconium aspiration syndrome | DOID_11049 | reason brought to NICU, condition at autopsy
perinatal necrotizing enterocolitis | DOID_8677 | diagnosis (NICU), CoD, autopsy
neural tube defect | DOID_0080074 | NICU diagnosis
ophthalmia neonatorum | DOID_9699 | diagnosis
polycythemia | DOID_8432 | diagnosis
Pulmonary hemorrhage | HP_0040223 | diagnosis
fetal erythroblastosis | DOID_1098 | 'RH incompatibility' as diagnosis
ABO Hemolytic Disease of the Newborn | NCIT_C106273 | 'ABO incompatibility' as diagnosis

**Comment by cstoeckert** [comment]
Not urgent but fine to add these.
