### ISSUE TITLE
Definitions that contain units or should be revised for clarity

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#229]
I see two definitions that could be revised for clarity. Here are the current definitions and my proposals:

ID | current definition | proposed definition
-- | -- | --
EUPATH:0000489 | A laboratory finding about parasite present which is negative in both blood smear and LAMP assay. | A presence of parasite that indicates that no parasite was detected in a specimen, either by loop-mediated isothermal amplification or blood smear.
EUPATH:0000029 | how often problems satisfying food needs in a household | A categorical measurement datum that specifies how frequently the food needs of a household were not met.

I think we should also consider revising labels and definition that contain units, for example:
'asexual parasite density in count per ul by microscope'.

**Comment by cstoeckert** [comment]
The proposed changes are fine and agree to just modify labels and definitions to remove mention of units.
'asexual parasite density by microscope' would be most general. Can be 'asexual parasite density in count per volume by microscope' if need to distinguish from other variables.
