### ISSUE TITLE
NTR: Florida Keys Mosquito Control district organization

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#242]
Please could we make a term for

Label:  Florida Keys Mosquito Control district organization
Definition: An organization that monitors mosquito species in the Florida Keys district, performs abatement, and is located in the Florida Keys, Florida, USA.

Parent term: organization of specimen collector
IRI: http://purl.obolibrary.org/obo/OBI_0001893
Definition: An organization that is the affiliation of the person collecting the specimen

**Comment by cstoeckert** [comment]
Thanks @SAK22, sorry but I was not clear with my question. Is there only one Florida Keys Mosquito Control District organization (and only one Collier Mosquito Control District organization, and only one Cass County Vector Control District organization, etc.) or are there multiple organizations within the Florida Key Mosquito Control District?

**Comment by SAK22** [comment]
@cstoeckert just one is the answer :) 1 Florida Keys Mosquito Control district organization.
