### ISSUE TITLE
NTR: version of the "_ detected" terms where a value will be a number

### ISSUE THREAD

**Issue by wbazant** [VEuPathDB-ontology/VEuPathDB-ontology#246]
Could I also ask for the versions of the terms where a value will be a number? "Taxon detected" was added, but "Abundance of taxon, CPM" originally wasn't. I just talked to Dan and realised we also need those, so that we can show numbers in addition to the Y/N multifilter.

https://redmine.apidb.org/issues/45788

**Comment by cstoeckert** [comment]
Here is the template for NTRs:
label:
definition: 
definition source:
parent:
For this request it might be:
label: count of taxon-specific sequence matches
definition: A count of the number of sequences that match a specific taxon. Usually provided as copies per million. 
definition source: MicrobiomeDB
parent:  count
@wbazant does this work for you?

**Comment by wbazant** [comment]
@cstoeckert It's fine, I was a bit confused because the tickets in Redmine seemed good for a while. I can make you redmine tickets that link to Github NTRs. 

I also appreciate how you phrased the label, I can see it's better than what I've proposed! The ticket had:


Term | Parent | Type | Description
-- | -- | -- | --
Taxon detected | Data analysis |   | Data indicates presence of a member that has a taxonomic assignment
Plant detected | Taxon detected | multifilter | Data indicates presence of a member of the Viridiplantae kingdom
Animal detected | Taxon detected | multifilter | Data indicates presence of a member of the Metazoa kingdom
Fungus detected | Taxon detected | multifilter | Data indicates presence of a member of the Fungi kingdom
Protist detected | Taxon detected | multifilter | Data indicates presence of a eukarote that is not a plant, animal, or fungus
x detected | [Plant, Animal, Fungus, Protist] detected | Boolean | Data indicates presence of x
Taxonomic abundance analysis | Data analysis |   | Relative abundance data, as copies per million (CPM)
x abundance, CPM | Taxonomic abundance analysis, CPM | numeric | Relative abundance of x, as copies per million (CPM)


John added the first five. The "x detected" / "x abundance, CPM" terms are only needed as a stopgap until EDA. I've decided I'll add them myself and maintain a fork of the .owl until they're not needed.


So I want only this one term, actually!

label: count of taxon-specific sequence matches
definition: A count of the number of sequences that match a specific taxon. Usually provided as copies per million.
definition source: MicrobiomeDB
parent: count

Or actually should parent be: data analysis? I've not seen the "count" term.

**Comment by cstoeckert** [comment]
The ontology parent is 'count' as this is a type of count (http://purl.obolibrary.org/obo/STATO_0000047) while the web display parent can be 'data analysis' to place it topically.

**Comment by cstoeckert** [comment]
We will create this term but want to label for the ontology as 'number of taxon-specific sequence matches' to be consistent with sibling terms in the VEuPathDB ontology.

**Comment by cstoeckert** [comment]
Follow up information indicates that this may not be a count (a data item denoted by an integer and represented the number of instances or occurences of an entity). An example value is 12.34 CPM (copies per million reads).

How about this?
label: normalized number of taxon-specific sequence matches
alternative label: taxon-specific sequence matches
definition: A data item of the normalized number of sequences that match a specific taxon. Usually provided as copies per million.
definition source: MicrobiomeDB
example of usage: 12.34 CPM (copies per million reads)
parent: data item

**Comment by wbazant** [comment]
parent: data item is good! adding normalized is a good way out. I think the definition really highlights that CPMs are a confusing unit, but the label including "normalized" should communicate that you can compare this number across samples and that the bigger the number, the bigger the amount of the taxon that was detected.
