### ISSUE TITLE
Differentiate two "Taxon detected" terms

### ISSUE THREAD

**Issue by wbazant** [VEuPathDB-ontology/VEuPathDB-ontology#247]
Remove a clash with the other "Taxon detected".
change: "Taxon detected by microbiology test" and "Taxon detected by sequence match"?

Apply also to "Fungus detected" etc. I guess.

@zhengj2007

**Comment by zhengj2007** [comment]
I will check the clinEpi. May need to use different labels. I mean how we name them in the terminologies not in the VEuPathDB ontology.

**Comment by cstoeckert** [comment]
@wbazant These are currently place holder terms but we want to make these ontology terms. Please provide initial definitions for the taxon detected by sequence match terms (including subclasses like fungus detected).

**Comment by wbazant** [comment]
@cstoeckert
how about:

Taxon detected: whether a method based on sequence match that was applied to reads coming from a sequencing assay of the sample has detected a taxon.
Fungus detected: whether a method based on sequence match that was applied to reads coming from a sequencing assay of the sample has detected a fungus.

**Comment by cstoeckert** [comment]
label: taxon detected by sequence match
ontology parent: data item 
definition: A data item that indicates whether a method based on sequence match that was applied to reads coming from a sequencing assay of the sample has detected a taxon.
definition source: MicrobiomeDB

**Comment by cstoeckert** [comment]
label: fungal taxon detected by sequence match
ontology parent: taxon detected by sequence match
definition: A taxon detected by sequence match that indicates whether a fungal taxon was detected.
definition source: MicrobiomeDB

@wbazant please let us know if this and the above "taxon detected by sequence match" is OK and we will create them.

**Comment by wbazant** [comment]
@cstoeckert 
I've thought for a while what a difference between detecting a fungus vs. detecting a fungal taxon is, and whether a taxon is even something you can detect rather than only being something you can read about in a book. EDAM:Taxon is a child of EDAM:Organism name, and the definition makes it clear that a taxon is a name of a group - "The name of a group of organisms belonging to the same taxonomic rank." but  NCIT:Organism lists "Taxon" as a synonym. OBI:Organism does not have a synonym Taxon, but OBI:Organism has a synonym Taxon.

If you think that's a distinction worth keeping then maybe we could have "Organism detected by sequence match" and "Fungus detected by sequence match" ? Otherwise, the current version is okay too. Whatever goes in, could it also go in with the term from https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/246 ?

**Comment by cstoeckert** [comment]
Great point @wbazant ! This is where ontological realism can be useful. What is actually being detected? If talking about a sequence match (data aligning with other data), then initially at least, it is not an actual fungus that was detected but rather a sequence with characteristics of a fungal sequence. An individual organism exists independent of sequence matching so it doesn't seem right to say there is a class of organisms whose nature may change based on the parameters of the match. 

To clarify then the definition of "taxon detected by sequence match" might be improved to say: A data item that indicates whether a method applied to data coming from a sequencing assay of the sample has detected matching sequences associated with organisms of a particular taxonomic grouping. We might improve the label to be "Sequence match for a taxonomic grouping"

By extension, a "Sequence match for a fungal taxonomic grouping" would be: A sequence match by taxonomic grouping that indicates whether a sequence with characteristics of a fungal sequence was detected.

**Comment by wbazant** [comment]
Hm, the method does actually try to detect a taxon! Each taxon is represented through a few sequences of marker genes, and different pieces of evidence are weighed up against each other on the level of whole taxa. The results aren't a list of sequences like in a BLAST match, but names of taxa.

How about this definition: A data item that indicates whether a method applied to data coming from a sequencing assay of the sample has detected a taxon through identifying sequences associated with organisms of a particular taxonomic grouping.

I wouldn't want the label changed to "Sequence match for a taxonomic grouping" - wouldn't it make people expect to see the match itself?

**Comment by cstoeckert** [comment]
I'm OK with this one: A data item that indicates whether a method applied to data coming from a sequencing assay of the sample has detected a taxon through identifying sequences associated with organisms of a particular taxonomic grouping.
Also with keeping the 'taxon detected by sequence match' label where taxon is understood not be the organism but the name of a taxonomic grouping.

**Comment by wbazant** [comment]
Great! This label + definition, and the current 'Taxon detected' getting changed to 'Taxon detected by microbiology test', would be a great resolution of this NTR.

**Comment by johnwjudkins** [comment]
@wbazant I've assigned these IRIs:
EUPATH:0009269 'normalized number of taxon-specific sequence matches'
EUPATH:0009270 'taxon detected by sequence match'
EUPATH:0009271 'fungal taxon detected by sequence match'

**Comment by cstoeckert** [comment]
Also change labels accordingly:
animal taxon detected by sequence match
plant taxon detected by sequence match
protist taxon detected by sequence match

**Comment by cstoeckert** [comment]
EUPATH:0009269 'normalized number of taxon-specific sequence matches' for issue #246 
EUPATH:0009267 'taxon detected by sequence match' (reuse IRI)
EUPATH:0009268 'fungal taxon detected by sequence match' (reuse IRI)

**Comment by cstoeckert** [comment]
The labels have been changed in microbiomedb.owl but still need to add to the VEuPathDB ontology
