### ISSUE TITLE
NTR: L43F-CYP4J5

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#248]
label: CYP4JF-L43F ? OR just L43F @bobular ?
parent term: ?
definition: Pyrethroid resistance associated point mutation (L-F), located within a p450 gene in the 2La inversion. 

@bobular can you check my definition too?

**Comment by cstoeckert** [comment]
@SAK22 To make this term, we need to know what is the reference Protein Ontology term it refers to. Then we can create the allele as we did for the insecticide resistance alleles (e.g., PR_000050412 Kdr V1016G) and create a prevalence term if needed.

**Comment by SAK22** [comment]
Hmmm I can't find it, will try different variations of this to try and look and let you know @cstoeckert

**Comment by cstoeckert** [comment]
After discussion with @SAK22 and @bobular we will create a term analogous to http://purl.obolibrary.org/obo/EUPATH_0043162 'prevalence of Kdr V1016G' and then add in axioms to the mutation and protein later after they are submitted to PR.
label: 'prevalence of CYP4J5 L43F'
definition: A data item that is the output of an assay to quantify the frequency of the genetic variation resulting in cytochrome P450 CYP4J5 L43F associated with pyrethroid resistance and located in the 2La inversion of Anopheles gambiae. 
definition source: VEuPathDB
parent: data item

**Comment by bobular** [comment]
Thanks!  It's possible that the capitalization should be Cyp4J5 - proteins are all caps, and genes are just capitalized?
This is a mutation in the gene, but the numbering is protein-based.  Very confusing!

**Comment by johnwjudkins** [comment]
Reserving EUPATH:0043234 for this term. @SAK22 @bobular

**Comment by SAK22** [comment]
Thank you!

**Comment by bobular** [comment]
Hi @johnwjudkins  -  please could we also have a "prevalence of wild type Cyp4J5 L43" term

analogous to existing term EUPATH_0043191 prevalence of wild type Rdl A296
