### ISSUE TITLE
Update two OMIABIS with OBIB IDs

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#249]
OBIB assigned OBIB prefix IDs to OMIABIS terms. So, we need to remove two following terms from externalByhand.owl
OMIABIS_0001011 count of current total human study participant
OMIABIS_0001018 cross sectional study design

Import the terms using OntoFox from OBIB:
OBIB_0000687 count of current total human study participant
OBIB_0000694 cross sectional study design

Need work on it when new OBIB release is out.

**Comment by cstoeckert** [comment]
OBIB release is out.
