### ISSUE TITLE
import list for terms referenced by ClinEpi placeholders

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#263]
This is in addition to OBI terms we created and imports mentioned in other tracker items. I'm not sure about using SNOMED terms, but no other ontology has these E. coli types.

IRI | label | parent (blank if computed by ontofox)
-- | -- | --
http://purl.obolibrary.org/obo/NCBITaxon_35336 | Rotavirus G4 |  
http://purl.obolibrary.org/obo/NCBITaxon_2560525 | Human orthorubulavirus 2 |  
http://purl.obolibrary.org/obo/PR_000014678 | alpha-1-antitrypsin |  
http://purl.obolibrary.org/obo/NCBITaxon_941442 | Giardia intestinalis assemblage A |  
http://purl.obolibrary.org/obo/NCBITaxon_1394984 | Giardia intestinalis assemblage B |  
http://purl.obolibrary.org/obo/NCBITaxon_36470 | Streptococcus group A |  
http://purl.obolibrary.org/obo/NCBITaxon_373153 | Streptococcus pneumoniae D39 (serotype 2) |  
http://purl.obolibrary.org/obo/OBI_0001985 | microarray assay |  
http://purl.obolibrary.org/obo/OBI_0000865 | 96-well neutralization assay |  
http://purl.obolibrary.org/obo/NCBITaxon_726 | Haemophilus haemolyticus |  
http://purl.obolibrary.org/obo/NCIT_C62584 | Coagulase-Negative Staphylococcus | Staphylococcus
http://purl.obolibrary.org/obo/VO_0000741 | Haemophilus influenzae serotype b | Haemophilus influenzae
http://purl.obolibrary.org/obo/FLU_0001024 | antibody titer | scalar measurement datum
http://purl.obolibrary.org/obo/OBI_0000920 | cytometric bead array assay |  
http://purl.bioontology.org/ontology/SNOMEDCT/419527005 | Streptococcus pneumoniae serotype 2 | Streptococcus pneumoniae
http://purl.obolibrary.org/obo/NCBITaxon_1513 | Clostridium tetani |  
http://purl.bioontology.org/ontology/SNOMEDCT/116397003 | Enteroaggregative Escherichia coli | Escherichia coli
http://purl.bioontology.org/ontology/SNOMEDCT/116395006 | Enterohemorrhagic Escherichia coli | Shiga toxin-producing Escherichia coli
http://purl.bioontology.org/ontology/SNOMEDCT/116396007 | Enteroinvasive Escherichia coli | Escherichia coli
http://purl.bioontology.org/ontology/SNOMEDCT/83285000 | Enteropathogenic Escherichia coli | Escherichia coli
http://purl.bioontology.org/ontology/SNOMEDCT/116394005 | Enterotoxigenic Escherichia coli | Escherichia coli
http://purl.bioontology.org/ontology/SNOMEDCT/838549008 | Shiga toxin-producing Escherichia coli | Escherichia coli

**Comment by zhengj2007** [comment]
For microbiomeDB, we'd like to import
http://purl.obolibrary.org/obo/ECTO_9002101 exposure to pyrethroid insecticide

**Comment by cstoeckert** [comment]
Let's wait on terms from FLU and SNOMED. Others should be OK.

**Comment by johnwjudkins** [comment]
A few more taxon terms:

http://purl.obolibrary.org/obo/NCBITaxon_130309 Human mastadenovirus F (Adenovirus 40/41 in ClinEpi)
http://purl.obolibrary.org/obo/NCBITaxon_10407 Hepatitis B virus
http://purl.obolibrary.org/obo/NCBITaxon_11103 Hepacivirus C (Hepatitis C virus in ClinEpi)
http://purl.obolibrary.org/obo/NCBITaxon_11676 Human immunodeficiency virus 1
