### ISSUE TITLE
phenotype terms for geneomic dataset

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#265]
Fungal phenotype terms:

phenotype: resistance to azole
 http://purl.obolibrary.org/obo/OMP_0006055

phenotype: resistance to posaconazole
 http://purl.obolibrary.org/obo/PHIPO_0000625

phenotype: resistance to voriconazole
 http://purl.obolibrary.org/obo/PHIPO_0000590 

(Details see https://redmine.apidb.org/issues/46756)

Please import the terms to VEuPathDB ontology

**Comment by cstoeckert** [comment]
Agree that this should go in next release.
