### ISSUE TITLE
"presence of Vibrio cholerae O1 by bacteriology" used as a label for two ontology terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#27]
Term "presence of Vibrio cholerae O1 by bacteriology" is assigned two different IDs
EUPATH_0015290, EUPATH_0015462
The term has different alternative label, one is "Vibrio cholerae O1, by bacteriology", one is "Vibrio cholerae 01, by bacteriology".
I think the later one is typo. Need to check the clinEpi terminology files to fix the issue in the clinEpi terminologies and keep one ID for "presence of Vibrio cholerae O1 by bacteriology" in the VEuPathDB ontology.

**Comment by johnwjudkins** [comment]
This is exactly like #28. @zhengj2007 should fix the typo in GEMS 1A, and I can fix EUPATH_0015462 for the upcoming VEuPath release.

**Comment by zhengj2007** [comment]
The label is changed in GEMS 1A.

The label for EUPATH_0015462 in GEMS 1A is 'Vibrio cholerae O1, by bacteriology result'. The label, definition and parent need to do corresponding changes in VEuPathDB ontology.

**Comment by johnwjudkins** [comment]
Changes to EUPATH_0015462:
Label: data about Vibrio cholerae O1 by differential medium assay
Definition: a data item that is the specified output of a differential medium assay that has the objective of determining whether a specimen contains Vibrio cholerae serogroup O1
