### ISSUE TITLE
label changes to organism identification data terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#278]
The presence_data and raw_data templates are constructed so that terms in the resulting module include the organism, assay, and specimen type in their labels and definitions e.g. 'Plasmodium in umbilical cord blood by microscopy assay datum'. However, some similar terms are already in the ontology whose labels and definitions do not mention the specimen type. For example, EUPATH:0023004 is 'presence of bacteria by microscopy' even though the template gives it the label 'presence of bacteria in blood by microscopy assay'. EUPATH:0010599 is another term whose label does not mention the feces/stool sample. (This is the result of changes in ClinEpi project hierarchies.) I propose allowing the template to overwrite these labels and definitions to avoid inconsistency or confusion.

**Comment by zhengj2007** [comment]
Add the old label as alternative term if the meaning is same.

**Comment by zhengj2007** [comment]
We would like to add the labels of organism identification data used in the ClinEpi in the ontology as alternative labels. However, organism identification data in different sample types used same labels. For example, we have four 'Salmonella, by multiplexed qPCR' terms in clinEpi, detected from 4 different sample types, 'Salmonella in pleural fluid|Salmonella in induced sputum|Salmonella in lung aspirate|Salmonella in nasopharyngeal/oropharyngeal swabs'. Would like to know how these terms are deal with in download file. We may use same approach in the ontology.
