### ISSUE TITLE
"presence of Vibrio cholerae O139 by bacteriology" used as a label for two ontology terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#28]
"presence of Vibrio cholerae O139 by bacteriology" is associated two IDs, EUPATH_0015463 and EUPATH_0015293.
Two ontology terms have same alternative label but different definition. Need to check whether they are same term and fix the issue in both clinEpi terminlogies and VEuPathDB ontology.

**Comment by johnwjudkins** [comment]
EUPATH_0015463 needs the 0 corrected to O in GEMS 1A (Can you fix this, @zhengj2007 ?). In the VEuPath ontology, it is in the wrong category; I will fix it for the upcoming release.

EUPATH_0015293 needs no changes.

**Comment by zhengj2007** [comment]
Label for EUPATH_0015463 is fixed in GEMS 1A project.

Display label for EUPATH_0015463 is 'Vibrio cholerae O139, by bacteriology result'. The label, definition, and parent need to be updated in the VEuPathDB ontology.

The definitions of presence ontology terms are not consistent. Some are "a categorical measurement datum that specifies whether ... was detected ...". Some are "a categorical measurement datum that specifies that ... was detected ...". 
I'd prefer the one. Besides, do we need to say 'was detected in a specimen ...'?

**Comment by johnwjudkins** [comment]
Regarding the "presence" terms, I will change the following terms' definitions to read "...specifies whether...":
EUPATH_0015291
EUPATH_0015292
EUPATH_0015293

**Comment by johnwjudkins** [comment]
Changes to EUPATH_0015463:
Label: data about Vibrio cholerae O139 by differential medium assay
Definition: a data item that is the specified output of a differential medium assay that has the objective of determining whether a specimen contains Vibrio cholerae serogroup O139
