### ISSUE TITLE
microbiome_human_only.owl: ontology mapping with files from MBSTDY0021 folder

### ISSUE THREAD

**Issue by wbazant** [VEuPathDB-ontology/VEuPathDB-ontology#280]
This is about adjusting the sample details mapping in the new .owl so I can use it for EDA data loading.

Because EDA allows an entity graph, we no longer need separate studies for different result types. I've merged some files,  producing a new folder, MBSTDY0021. See here: https://github.com/VEuPathDB/ApiCommonMetadataRepository/tree/master/ISA/metadata/MBSTDY0021. The previous folder was MBSTDY0020 but I will use a different structure for EDA.

As a result some studies have different names.
These sample details files are merged:
- DIABIMMUNE, DIABIMMUNE_WGS -> DiabImmune
- UgandaMaternalV1V2, UgandaMaternalV3V4 -> UgandaMaternal
- ResistomeWgs , ResistomeAmplicon -> Resistome
the other files I still want in human_only_microbiome.owl got symlinked to their previous versions.

Additionally, it's currently not consistently refering to the files:
        <obo:EUPATH_0000755 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">StLouisNICU.txt::country</obo:EUPATH_0000755>
        <obo:EUPATH_0000755 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Uganda_Maternal::country</obo:EUPATH_0000755>
I would prefer it consistent: either {dataset name}::{header} or {dataset name}.txt::{header}? Maybe {dataset name}::{header} is better.

Also, I'm not sure if you have a way of doing this, but do you have a way of checking that all the terms from the studies are present in the .owl? I can help with this if needed, one term that I've found missing so far is "Host common name", EUPATH_0000512. If it is intentionally not provided (because it's always the same value) I can remove that column from the files.

Could you update these aspects of the microbiome_human_only.owl?

**Comment by zhengj2007** [comment]
@wbazant The microbiome_human_only.owl is generated from the tab-delimited file:
https://github.com/VEuPathDB/ApiCommonData/blob/master/Load/ontology/Microbiome/doc/Microbiome_human_only_conversion.csv

It contains the column 'dataFile' to specify the sample file name. We can update the dataFile name as you request and the variables accordingly. The variable name is made as {dataFile}::{header}(variable) as what we did in clinEpi projects. 

You can go ahead to change variable and dataFile columns in the Microbiome_human_only_conversion.csv and we can remake the OWL file based on the csv file. The csv file contains two new datasets I worked on mapping but not found the corresponding sample files under MBSTDY0020. So, I made the dataFile names 'Dantas_earlyLife' and 'Uganda_Maternal'.





</body>

</html>

**Comment by wbazant** [comment]
Done! I've updated the conversion file or the sample detail files for everything that was different. The only one I couldn't do was

https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/283


Details of the changes I made can be viewed in git - I tried to change one thing at a time and put all the details in history.

conversion file https://github.com/VEuPathDB/ApiCommonData/commits/master/Load/ontology/Microbiome/doc/Microbiome_human_only_conversion.csv
sample details files: https://github.com/VEuPathDB/ApiCommonMetadataRepository/commits/master/ISA/metadata/MBSTDY0021
and I've also written two little programs to get the variables from the two sources so that I can compare them https://github.com/VEuPathDB/ApiCommonMetadataRepository/commit/89f9db1c5ed

Could you do #283 and remake the microbiome_human_only.owl?

**Comment by zhengj2007** [comment]
Have added the term back in the conversion file and remade the microbiome_human_only.owl.

**Comment by wbazant** [comment]
I've changed the conversion file slightly: https://github.com/VEuPathDB/ApiCommonData/commit/c85e8c4d01119 so that EnteralFeeds_2mo also has the NICUDischarge.txt:: in front, but I can work with the owl you made, thank you!

**Comment by zhengj2007** [comment]
@wbazant I remade the OWL file base on the updated conversion file.

**Comment by wbazant** [comment]
The terms agree now!
