### ISSUE TITLE
raw_data template and the 'threshold cycle'/'Ct value' terms 

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#281]
Similar to #278. Before EDA changes, ClinEpi had many terms for Ct values, which result from flurogenic PCR assays to identify organisms. At that time, we added these placeholder terms to the ontology as children of 'threshold cycle' (STATO) and labeling them accordingly.

However, EDA changes have resulted in "Ct value" being removed from the label and becoming the unit of those terms instead. Now these labels contain the phrase "TAC result". I propose allowing the template to change these labels based on the same patterns as the template's other assay output terms, which would produce labels following the pattern '(organism) in (specimen) by fluorogenic PCR assay datum'. As an example, EUPATH:0015343 'TaqMan threshold cycle for Cryptosporidium hominis in feces' would become 'Cryptosporidium hominis in feces by fluorogenic PCR assay datum'.

**Comment by zhengj2007** [comment]
Will keep the labels for this release and discuss with the ClinEpi outreach team to see whether we need to improve the labels.
