### ISSUE TITLE
NTR: Oral diet at 2 months of age

### ISSUE THREAD

**Issue by wbazant** [VEuPathDB-ontology/VEuPathDB-ontology#283]
This is the term:

variable NICUDischarge.txt::EnteralFeeds_2mo
term:EUPATH_0009273
parent: EUPATH_0000678
label: Oral diet at 2 months of age

This term made it into last release but then disappeared.

 I've found it with this command:
```
[wbazant@yew ApiCommonData]$ git log -GEnteralFeeds_2mo Load/ontology/Microbiome/
```

Jie your commit from Nov 17 adds the term only to the .owl, and commit from Dec 6 removes it from the owl.

```
commit cb29e268c2e7da2b8e3f6e2a00e9e542d93b3607
Author: zhengj2007 <zhengj2007@gmail.com>
Date:   Mon Dec 6 09:44:12 2021 -0500    add terms for new NICU metagenomic study, refs #46709commit ded3d5ece6123bbb147098669b37f5e14fc758c7
Author: zhengj2007 <zhengj2007@gmail.com>
Date:   Wed Nov 17 11:35:17 2021 -0500    add new terms needed by new dataset
```

Can you add this term to the human only conversion file and the owl? I didn't want to do it myself because I'm not sure the term EUPATH_0009273 is still correct.

**Comment by zhengj2007** [comment]
The term may be removed by mistake.

Add the term back in both microbiome.owl and microbiome_human_only.owl
