### ISSUE TITLE
"subnational region relocated from within past 12 months" used as a label for two ontology terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#29]
Label "subnational region relocated from within past 12 months" is used for two ontology terms, EUPATH_0023047 (subClassOf 'human traveling information') and EUPATH_0023044 (subClassOf 'relocation information'). If they are different ontology terms, we need to use different labels.

**Comment by cstoeckert** [comment]
Could the label for EUPATH_0023047 be a cut and paste mistake where it was meant to be 'subnational region visited within past 12 months' in keeping with other subclasses of 'human traveling information'?

**Comment by zhengj2007** [comment]
Yes. The display label for EUPATH_0023047 (subClassOf 'human traveling information') is 'States visited in last 12 months'. Change label to 'subnational region visited within past 12 months' sounds good to me.

**Comment by johnwjudkins** [comment]
This change is going in the release candidate.
