### ISSUE TITLE
Issue in VEuPathDB release candidate 

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#291]
Found two terms, UBERON_0001062 and CARO_0000000 with same label 'anatomical entity'. Both terms are used in UBERON. I have submitted the issue to UBERON, https://github.com/obophenotype/uberon/issues/2296.

We can make the release as it but add the issue in the release note. Or manually replace CARO_0000000 by UBERON_0001062 in the imported UBERON file to temporarily solve the issue. Current two terms are siblings. Looked weird. And many terms under CARO_0000000 'anatomical entity' also under specific classes under UBERON_0001062  'anatomical entity'. I'd prefer to try manually replacement first.

**Comment by johnwjudkins** [comment]
I'll go with the manual replacement option.

**Comment by zhengj2007** [comment]
I think we may also need to replace CARO_0000000 by UBERON_0001062 in the imported CARO file. Hope it can fix the issue.
