### ISSUE TITLE
issue labels

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#297]
May consider to add issue status labels, such as
- status - in progress
- status - pause
- status - pending

We may also delete unused labels, such as enhancement, duplicate, etc.

Question: what difference between label 'curation' and 'NTR'?

**Comment by johnwjudkins** [comment]
I suppose we don't need 'curation'. We have 'NTR', and issues about changing labels or definitions or adding axioms etc. would fall under 'cleanup' or some new label more specific than 'curation'.

**Comment by johnwjudkins** [comment]
I agree with deleting unused labels.

**Comment by zhengj2007** [comment]
I checked the redmine ticket. 'curation' refers to Annotation/Curation team. So, we need to keep the label.

**Comment by zhengj2007** [comment]
Removed unused labels
Added descriptions to labels 
Added new label 'Pending' to tag the issues that wait for the changes/decisions made in other resources.
