### ISSUE TITLE
error running make imports

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#299]
@zhengj2007 
Running `make imports` does not update the owl files and instead gives this:

`[Fatal Error] :1:50: White spaces are required between publicId and systemId.
INVALID ONTOLOGY FILE ERROR Could not load a valid ontology from file: import_EFO.owl
For details see: http://robot.obolibrary.org/errors#invalid-ontology-file-error`

The same occurs with any import file (not just EFO). However, the Ontofox site works, and ROBOT has not updated recently. The import owl files not missing.

**Comment by zhengj2007** [comment]
It seems the ontoFox service has some problem. I have contacted Oliver He for fixing it.

**Comment by zhengj2007** [comment]
Fixed the issue. Should work now.

**Comment by johnwjudkins** [comment]
@zhengj2007 I still get the same error.

**Comment by johnwjudkins** [comment]
`make -B imports` worked. Thanks.
