### ISSUE TITLE
Terms without definitions

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#30]
A list of terms without definitions:
material may be  used for [EUPATH:0000005]
symptom or sign of [EUPATH:0000044]
Amazonia data dictionary label (es)   [EUPATH:0000263]
Amazonia preferred label (en)   [EUPATH:0000264]
Amazonia preferred label (es)   [EUPATH:0000265]
ontological label [EUPATH:0000266]
PRISM data dictionary label (en)   [EUPATH:0000267]
PRISM preferred label (en)   [EUPATH:0000268]
Amazonia description [EUPATH:0000269]
PRISM description [EUPATH:0000270]
term type [EUPATH:0000271]
resource ID [EUPATH:0000272]
ontological definition [EUPATH:0000273]
Indian data dictionary label (en)   [EUPATH:0000329]
Indian preferred label (en)   [EUPATH:0000330]
Indian description [EUPATH:0000331]
Amazonia data dictionary label (en)   [EUPATH:0000332]
NLST Clade of organism [EUPATH:0000574]

Most of these terms are annotation properties. Some of them may not be used anymore and can be considered to deprecate.

**Comment by johnwjudkins** [comment]
'symptom or sign of' seems problematic in some instances e.g. 'cerebral malaria' SubClassOf 'symptom or sign of' some 'severe malaria'. Cerebral malaria is a realizable entity, whereas neither a sign nor a symptom is ever a realizable entity.

**Comment by zhengj2007** [comment]
No domain/range is set for 'symptom or sign of' object property. So, axiom is fine: 'cerebral malaria' SubClassOf 'symptom or sign of' some 'severe malaria'. Please ignore the label of the relation. 
The logical axiom is set for automatic classification for PRISM project few years ago. We may clean it up in the future.

**Comment by cstoeckert** [comment]
I agree that we will want to relabel the object property 'symptom or sign of'. How about 'manifestation of'? (as per https://www.cdc.gov/malaria/about/disease.html#severe)

**Comment by zhengj2007** [comment]
Following annotation Properties are not used anymore, can be removed or deprecated.

- Amazonia data dictionary label (es) [EUPATH:0000263]
- Amazonia preferred label (en) [EUPATH:0000264]
- Amazonia preferred label (es) [EUPATH:0000265]
- ontological label [EUPATH:0000266]
- PRISM data dictionary label (en) [EUPATH:0000267]
- PRISM preferred label (en) [EUPATH:0000268]
- Amazonia description [EUPATH:0000269]
- PRISM description [EUPATH:0000270]
- resource ID [EUPATH:0000272]
- ontological definition [EUPATH:0000273]
- Indian data dictionary label (en) [EUPATH:0000329]
- Indian preferred label (en) [EUPATH:0000330]
- Indian description [EUPATH:0000331]
- Amazonia data dictionary label (en) [EUPATH:0000332]
- term type [EUPATH:0000271]

Object Properties:
- material may be used for [EUPATH:0000005]
- symptom or sign of [EUPATH:0000044]
The logical axiom is not used in any application so far. May consider to clean up 'symptom or sign of [EUPATH:0000044]' 

Class:
- NLST Clade of organism [EUPATH:0000574]
Need to add definition.

**Comment by johnwjudkins** [comment]
We were never able to identify how 'NLST clade of organism' was meant to be used. Should we deprecate it?

**Comment by zhengj2007** [comment]
Since 'NLST clade of organism' is not used in any VEuPathDB projects, we can deprecate the term.

**Comment by johnwjudkins** [comment]
I'm including these suggested changes in the release candidate, which will have 'manifestation of' as the label for EUPATH:0000044.
