### ISSUE TITLE
Can't find ontology term "Covington, LA" for the column header [city]

### ISSUE THREAD

**Issue by weili-apidb** [VEuPathDB-ontology/VEuPathDB-ontology#304]
Can't find ontology term "Covington, LA" for the column header [city]
 
Covington, LA: Covington City in Louisiana

**Comment by zhengj2007** [comment]
The value for city does not require ontology term. So, any string should work. No need to add "Covington, LA" as an ontology term.

**Comment by weili-apidb** [comment]
Yes, agreed. It was a format issue. The column headers were messed up. Thank you.
