### ISSUE TITLE
OBI replacement term for ERO:immunoassay?

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#313]
Based on [this issue](https://github.com/obi-ontology/obi/issues/1203), is OBI:0002773 'single-value binding of antibody with reporter to antigen assay' suitable to replace ERO:0001362 'immunoassay' in VEuPath?

**Comment by zhengj2007** [comment]
Yes. Please go ahead.

OBI:0002773 'single-value binding of antibody with reporter to antigen assay' with 'immunoassay' as alternative term.

**Comment by zhengj2007** [comment]
The other ERO terms imported to VEuPathDB are:
ERO:0000722 patient screening
ERO:0001372 laparotomy

The terms are not used in any VEuPathDB projects. With replacing ERO:0001362 'immunoassay', we don't need to import any terms from inactive ERO ontology. Both ontoFox input text and output OWL file can be removed.
