### ISSUE TITLE
Inconsistent labels in VEuPathDB ontology and ClinEpi web display terminologies

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#33]
Annotation property, EUPATH_0001005 multifilter, is used to indicate the term type in the ClinEpi web display terminologies including multifilter now. So, we need to update the label and definition in the ontology.
label: term type
alternative label: termType
proposed definition: The annotation specifies how terms is used in generation search filters on the website. It has five options:
- category: a term to organize the variables for exploration on the website
- variable: a variable in the dataset
- variable, derived: one term that is calculated, using the data in two or more other variables
- multifilter: any value below it in the hierarchy will be displayed as a multifilter
- value: the value of a multifilter

**Comment by johnwjudkins** [comment]
I'm making this change in the release candidate.
