### ISSUE TITLE
update axiom of EUPATH_0000219 'time of screening'

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#333]
Related to #326:

'time of screening' is defined axiomatically such that it `'is about' some 'patient screening'`, even though 'patient screening' is an ERO term, and we are deprecating those. In the pull request I submitted a change going one parent up from 'patient screening' so that the axiom becomes `'is about' some assay`.

I did suggest a 'patient screening' term [here](https://github.com/obi-ontology/obi/issues/1332), but it was pointed out that that phrase has diverse contexts. I noticed the ClinEpi label is 'Timing of enrollment', implying some context of screening for a clinical trial. Perhaps we can come up with a patient screening term for this context.

**Comment by zhengj2007** [comment]
We need the help from clinEpi team to understand the meaning of 'Timing of enrollment'
