### ISSUE TITLE
NTRs: Tick bacteria

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#334]
Hello! So these can all be found in NCBItaxon and for Vectorbase we need these for tick-borne bacteria data :)

Babesia microti
Anaplasma phagocytophilum
Borrelia miyamotoi
Borreliella burgdorferi

Thank you!

**Comment by zhengj2007** [comment]
Will add the NCBItaon terms in the ontology
