### ISSUE TITLE
NTRs: Tick species

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#335]
Please could we add these tick species.

Amblyomma maculatum
Amblyomma americanum
Amblyomma cajennense
genus Amblyomma
genus Rhipicephalus
Rhipicephalus sanguineus
genus Dermacentor
Dermacentor variabilis
Dermacentor occidentalis
Dermacentor andersoni
Ixodes pacificus

Thank you!

**Comment by zhengj2007** [comment]
@johnwjudkins will check the terms in NCBITaxon and import the terms.
