### ISSUE TITLE
NTR: citizen science collection

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#336]
Please could we add a tick collection method: 

citizen science collection

A broad term used as we do not know the exact method of how the general public collected their tick specimens as part of this project: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199644#sec020

**Comment by SAK22** [comment]
This looks great!

**Comment by zhengj2007** [comment]
Available in the release version
