### ISSUE TITLE
Missing ontology terms from FungiDB

### ISSUE THREAD

**Issue by weili-apidb** [VEuPathDB-ontology/VEuPathDB-ontology#337]
The following ontology terms are missing from FungiDB (fung-inc):
Could not determine Accession Number for: [elk] 
Could not determine Accession Number for: [deer] 
Could not determine Accession Number for: [ferret] 
Could not determine Accession Number for: [bird]

**Comment by zhengj2007** [comment]
Here are the mapped NCBITaxon terms with scientific names of the organism
[elk] - NCBITaxon_1574408 Cervus canadensis
[deer] - NCBITaxon_9850 Cervidae
[ferret] - NCBITaxon_9669 Mustela putorius furo
[bird] - NCBITaxon_8782 Aves

If the terms are used in organism annotation, please add the terms with mapped ontology IDs in the ontologyMappings.xml. It should fix the loading issues. Please let me know if there is any further problem.

**Comment by weili-apidb** [comment]
It works now. Thank you,
