### ISSUE TITLE
annotation property: EUPATH_0000274 display order

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#34]
The label of term in the clinEpi terminologies is 'displayOrder'. 
Proposed to add the alternative label: displayOrder for the term.

Other annotation associated with the term are:
definition: The order variables will appear in under a given parent term. Left blank if alphabetical order is accepted
comment: annotation used for specifing the order of terms displayed on the EuPathDB website  

Proposed to delete comment and update the definition as:
The annotation is used to specify the order of terms displayed on the website.

**Comment by cstoeckert** [comment]
"An annotation property used to specify the order of terms displayed on a website."

**Comment by johnwjudkins** [comment]
I'm removing the comment and updating to Chris's definition in the release candidate.
