### ISSUE TITLE
OMO annotation conflicting with BFO

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#355]
@zhengj2007 
OMO in its latest release has replaced 'alternative term' with 'alternative label', conflicting with BFO and other ontologies. (I see no other similar issues.)

This raises 2 issues:

1. Which label do we use? [This](https://github.com/information-artifact-ontology/ontology-metadata/issues/8) suggests it should be 'alternative label'?
2. How do we fix this in the .owl file?

Issue 2 may be solved by replacing the import URL for either BFO or OMO with our own import file (like we do for most import ontologies) in eupath-dev.

**Comment by zhengj2007** [comment]
We should use 'alternative label'. We can change the label in the release eupath.owl file.
