### ISSUE TITLE
rename 'diagnosis at hospitalization' & add axiom

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#357]
'diagnosis at hospitalization' should be renamed to 'diagnosis at admission' - it is meant to refer to OMRSE:'admission process'. Besides the label change, an axiom should connect the two terms; I propose

'part of' some (is_specified_output_of some 'admission process').

Similarly, 'diagnosis at discharge' should have the axiom

'part of' some (is_specified_output_of some 'patient discharge').

These axioms show that the diagnosis is part of the documentation associated with admission or discharge, respectively.

**Comment by zhengj2007** [comment]
'diagnosis at hospitalization' should be renamed to 'diagnosis at hospital admission'

**Comment by johnwjudkins** [comment]
Reopening because some labels and definitions still have "hospitalization" rather than "hospital admission". A similar issue is that we have 'diagnosis at discharge' even though the OMRSE term is 'patient discharge', so we may want to change that to 'diagnosis at patient discharge' (and change its children as well).
