### ISSUE TITLE
NTR: Putatively essential

### ISSUE THREAD

**Issue by Achchuthan** [VEuPathDB-ontology/VEuPathDB-ontology#367]
For new term requests, please provide the following information:
**putatively essential** [required]

**inferred essential**, **putatively  lethal** [optional]

**Definition** [required except for organism name]
Absolutely necessary or vital for the life of an organism, as inferred either from direct experimental evidence or from indirect evidence.

**Contributor** [optional]
Achchuthan Shanmugasundram (0000-0003-2349-6929)

**Requester** [optional]
FungiDB

**Comment by zhengj2007** [comment]
Shall we consider to add it in VEuPathDB ontology as an ICE?

**Comment by zhengj2007** [comment]
Parent: http://purl.obolibrary.org/obo/OBI_0001909 conclusion based on data 
Definition: gene absolutely necessary or vital for the life of an organism, as inferred either from direct experimental evidence or from indirect evidence.
@johnwjudkins will improve the definition when add term in the ontology

**Comment by johnwjudkins** [comment]
Definition:

An information content entity about a gene that is absolutely necessary or vital for the life of an organism, as inferred either from direct experimental evidence or from indirect evidence.

@Achchuthan please review. I'm writing this definition as a general information term, but if this is meant as a Boolean term (information indicating whether or not a gene is putatively essential), then let me know and I'll update.

**Comment by Achchuthan** [comment]
HI @johnwjudkins,
Thanks for drafting the definition of this term. I am happy with it. I'm assigning it back to you!!

**Comment by zhengj2007** [comment]
@Achchuthan, John added the term with label 'information on putatively essential gene' and ID 'EUPATH_0043245'.

**Comment by zhengj2007** [comment]
@johnwjudkins Add 'putatively essential' as VEuPathDB alternative label
