### ISSUE TITLE
NTR: Phenotype

### ISSUE THREAD

**Issue by Achchuthan** [VEuPathDB-ontology/VEuPathDB-ontology#368]
For new term requests, please provide the following information:
**phenotype** [required]

**Definition** [required except for organism name]
 Any of the set of observable characteristics of an organism resulting from the interaction of its genotype with the environment.

**Other ontologies with this term** 

-  FYPO (http://purl.obolibrary.org/obo/FYPO_0000001) and PHIPO (http://purl.obolibrary.org/obo/PHIPO_0000505) have this term with the same definition. 
- NCIT (http://purl.obolibrary.org/obo/NCIT_C16977) and EFO (http://www.ebi.ac.uk/efo/EFO_0000651) also have a similar definition. 
- The definition of phenotype in FlyBase Controlled Vocabulary (http://purl.obolibrary.org/obo/FBcv_0001347) only refers to abnormal phenotypes and this is incorrect in our context. 
- The Unified Phenotype Ontology (uPheno, http://purl.obolibrary.org/obo/UPHENO_0001001) also has this term. However, I am not sure whether uPheno is loaded in VEuPatHDB GUS database.

**Contributor** [optional]
Achchuthan Shanmugasundram (0000-0003-2349-6929)

**Requester** [optional]
FungiDB

**Comment by zhengj2007** [comment]
http://purl.obolibrary.org/obo/OGMS_0000023 
phenotype
Definition: A (combination of) quality(ies) of an organism determined by the interaction of its genetic make-up and environment that differentiates specific instances of a species from other instances of the same species.

Base on the definition, it is not restricted to human or animal and doesn't only refer to abnormal phenotype. We may use OGMS: phenotype.

**Comment by zhengj2007** [comment]
@Achchuthan Will check whether OGMS loaded in the GUS. If not, request term import.

**Comment by Achchuthan** [comment]
@zhengj2007, this term from OGMS is loaded in GUS. So, I can use this term.
