### ISSUE TITLE
Term 'Blood smear performed' and 'Blood smear not performed'

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#37]
deprecate EUPATH_0000488 as it is not used. Will need to add a Blood smear performed' (EUPATH_0041029)
see Redmine ticket #37801

**Comment by johnwjudkins** [comment]
EUPATH_0000488 is deprecated in eupath_dev.owl, and EUPATH_0041029 is in eupath_dev.owl. These changes will be reflected in the new release.
