### ISSUE TITLE
naming convention wiki page

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#370]
@johnwjudkins is working on the wiki.

**Comment by zhengj2007** [comment]
The content looks good. May consider to change some formats for easy searching and identifying the naming convention we used, such as, using  internal link list the naming convention categories, highlight the naming conversion we used (current using double quotations, may also use bold font) and list them using bullet points when have more than one in a category.

**Comment by johnwjudkins** [comment]
The page is updated @zhengj2007
