### ISSUE TITLE
normalization of time measurement data terms not discussed

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#374]
Related to #150. We have terms whose labels begin with "number of" and do not represent frequencies as does 'number of days per week at primary job'. As we discussed, _those_ terms will be moved to 'count'. However, the following terms are true TMD, and I propose changing their labels to "duration of...". All TMD are durations of processes according to the defining [axiom](http://purl.obolibrary.org/obo/IAO_0000416), so we can label the following terms thusly.

ID |  Proposed label | Current label
-- | -- | --
EUPATH:0000191 | duration of study participation from enrollment to current visit |  number of days from participant enrollment in a study until current visit
EUPATH:0000525 | duration of study participation from first to current specimen collection | number of days to follow up specimen collection
EUPATH:0000427 | duration since last diagnosis of malaria | number of months since malaria diagnosis
EUPATH:0000377 | duration of residence in dwelling | number of years living in dwelling
EUPATH:0000378 | duration of residence in community | number of years living in community

**Comment by zhengj2007** [comment]
Looks good to me. If we'd like to make the terms without time units, we'd update the definitions accordingly.

**Comment by johnwjudkins** [comment]
The following are terms about the proportion of time one spends in an occupation. We discussed moving these from TMD to 'count'. I agree these are not TMD, but they may not be counts either, because one can work 7.5 hours per day. It may be better to move them up to 'measurement datum' instead. My proposals:


ID | project label | current ontology label | proposed ontology label | current definition | proposed definition
-- | -- | -- | -- | -- | --
EUPATH:0000350 | Time spent in occupation every week | number of days per week at primary job | days per week at primary occupation | A time measurement datum of days in a week at primary job. | A measurement datum of days per week spent in one's primary occupation.
EUPATH:0000351 | Time spent in occupation 2 every week | number of days per week at secondary job | days per week at secondary occupation | A time measurement datum of days in a week at secondary job. | A measurement datum of days per week spent in one's secondary occupation.
EUPATH:0000366 | Time spent in occupation every day | number of hours per day at primary economic activity | hours per day at primary occupation | A time measurement datum about number of hours per day spend at primary economic activity. | A measurement datum of hours in one's primary occupation per day spent in that occupation.
EUPATH:0000367 | Time spent in occupation 2 every day | number of hours per day at secondary economic activity | hours per day at secondary occupation | A time measurement datum about number of hours per day spend at secondary economic activity. | A measurement datum of hours in one's secondary occupation per day spent in that occupation.

**Comment by zhengj2007** [comment]
Discussed on the ontology team meeting August 3. Will update ontology label as project label and update the definition accordingly, such as time spend daily, weekly
