### ISSUE TITLE
Proposed axioms for existing VEuPath terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#39]
Note that EUPATH:0010579 is also affected by issue #38 and the axiom proposed here for OBIB:0000029 is already in OBIB.

ID | label |   | superclass |   | object property |   | object
-- | -- | -- | -- | -- | -- | -- | --
EUPATH:0000310 | information on observation details | Equivalent To | information content entity | and | is about | some | 'clinical visit'
EUPATH:0000430 | information on antimalarial drug used last year | SubClass Of | information content entity | and | is about | some | 'has role' some ('has active ingredient' some antimalarial)
OBIB:0000029 | medication material | Equivalent To | material entity | and | has role | some | 'medication role'
EUPATH:0000302 | information on dwelling facilities | SubClass Of | information content entity | and | is about | some | process and 'has participant' some 'human being'
EUPATH:0000303 | information on dwelling physical characteristics | SubClass Of | information content entity | and | is about | some | 'part of' some dwelling
EUPATH:0010036 | information on eligibility criterion | Equivalent To | directive information entity | and | mentions | some | 'eligibility criterion'
EUPATH:0000411 | information on existing illness | SubClass Of | information content entity | and | is about | some | 'human participant under investigation' and 'bearer of' some disease
EUPATH:0000381 | information on kitchen location | SubClass Of | information content entity | and | is about | some | dwelling
EUPATH:0000425 | information on malaria parasite infection diagnosis past year | SubClass Of | information content entity | and | part of | some | diagnosis and mentions some malaria
EUPATH:0000391 | information on organization responsible for treating bed nets | SubClass Of | information content entity | and | is about | some | organization
EUPATH:0000307 | information on participant study details | Equivalent To | information content entity | and | part of | some | 'study design execution' and 'part of' some (investigation and 'has participant' some 'Homo sapiens')
EUPATH:0011730 | information on breastfeeding process | Equivalent To | information content entity | and | is about | some | 'breastfeeding process'
EUPATH:0010037 | information on relation to participant | SubClass Of | information content entity | and | is about | some | 'Homo sapiens'
EUPATH:0000607 | information on weight loss in last three months | SubClass Of | information content entity | and | is about | some | 'Weight loss'
EUPATH:0000420 | information on where malaria diagnosed in last 12 months | SubClass Of | information content entity | and | is about | some | 'geographic location' and 'contains process' some ('diagnostic process' and has_specified_output some (diagnosis and mentions some malaria))
EUPATH:0010579 | information on whether Adenovirus ELISA performed | SubClass Of | information content entity | and | is about | some | 'fecal specimen'
EUPATH:0000383 | information on whether occupant owns or pays rent on dwelling | SubClass Of | information content entity | and | is about | some | dwelling
EUPATH:0022057 | information on whether specimen collection prompted by sign of fever | SubClass Of | information content entity | and | is about | some | 'specimen collection objective'
EUPATH:0000154 | duration of abdominal pain | Equivalent To | time measurement datum | and | is duration of | some | 'Abdominal pain'
EUPATH:0000359 | occupation | SubClass Of | information content entity | and | is about | some | realizes some 'social role'
EUPATH:0022049 | duration of current secondary occupation | SubClass Of | time measurement datum | and | is duration of | some | realizes some ('social role' and 'role of' some 'human participant under investigation')
EUPATH:0000138 | participant observation duration time | SubClass Of | time measurement datum | and | is duration of | some | ('part of' some 'study design execution') and ('has participant' some 'participant under investigation')
EUPATH:0023050 | treatment start date | SubClass Of | time measurement datum | and | is about | some | 'process boundary' and starts some treatment
EUPATH:0023051 | treatment start time | SubClass Of | time measurement datum | and | is about | some | 'process boundary' and starts some treatment
EUPATH:0000423 | parasite species information | Equivalent To | data item | and | is_specified_output_of | some | 'organism identification assay' and realizes some ('evaluant role' and 'role of' some 'blood specimen')
EUPATH:0021034 | information on Plasmodium malariae diagnosis within past year | SubClass Of | information content entity | and | mentions | some | 'Plasmodium malariae'

**Comment by cstoeckert** [comment]
Regarding EUPATH:0000310, are these observations only at clinical visits or can they be household visits? If only clinical, then that should probably be reflected in the label (for example, "information on clinical observation details")

**Comment by cstoeckert** [comment]
reagrding EUPATH:0000302, how is info on dwelling facilities about "process and 'has participant' some 'human being'"?

**Comment by cstoeckert** [comment]
for EUPATH:0010579, if we are keeping this general then it should not be defined as about a fecal specimen.

**Comment by cstoeckert** [comment]
EUPATH:0000423: including blood specimen seems too specific for a general "parasite species information"

**Comment by johnwjudkins** [comment]
EUPATH_0000310: The definition of 'clinical visit' does not specify where the patient is seen (could be household or clinic), so I don't think we need to change the label.
EUPATH_0000302: I had based that axiom on the definition, but now I think we should use the following axiom: Equivalent to 'information content entity' and 'is about' some 'dwelling facility'
EUPATH_0010579: I'll use 'specimen' instead of 'fecal specimen'.
EUPATH_0000423: 'blood specimen' is mentioned in the definition. Perhaps I should change the label; in ClinEpi it's 'Plasmodium species, by microscopy'.

**Comment by zhengj2007** [comment]
The term 'clinical visit' is added for PRISM project. The clinical observation is more general and not limited to the observations that happened during clinical visit. We expanded the meanings of EUPATH:0000310 to cover all kinds of observations related to clinical when bring in MALED and GEMS datasets. So, it is not just about 'clinical visit' and textual definition of EUPATH:0000310 should be updated too.  We may consider to add 'clinical observation' and associate it with EUPATH:0000310.

> Regarding EUPATH:0000310, are these observations only at clinical visits or can they be household visits? If only clinical, then that should probably be reflected in the label (for example, "information on clinical observation details")

**Comment by zhengj2007** [comment]
EUPATH:0000430: has axiom:
has role' some ('has active ingredient'   some antimalarial)

Looks weird to me. It is information about material entity, or about role. If it is about material entity, better use 'material entity' and has_role some antimalarial. 'has active ingredient' is a subProperty of 'has part'. It sounds weird to say a role has_part of another role. If we want to use  'has active ingredient', may consider axiom like is_about some ('material entity' and only ('has active ingredient' and some ('has role' some antimalarial))).

**Comment by zhengj2007** [comment]
EUPATH_0000302: need to update the textual axioms as well.

**Comment by zhengj2007** [comment]
EUPATH:0000303: information on dwelling physical characteristics
logical axiom: is_about some 'part of' some dwelling
  - is it about 'dwelling' good enough?

EUPATH:0000411: information on existing illness
logical axiom: is_about some 'human participant under investigation'   and 'bearer of' some disease
  - disease is a disposition, it should hold true for all human, how about 'human participant under investigation' and 'participates in' some 'disease course'?

EUPATH:0000425: information on malaria parasite infection diagnosis past year
logical axiom: 'part of' some diagnosis and mentions some malaria
  - Do we want to say information part_of another information, or just is_about is enough?

EUPATH:0000307: information on participant study details 
logical axiom: part of some 'study design execution' and 'part of' some (investigation and 'has participant' some 'Homo sapiens')
  - information cannot be part_of some process ('study design execution'). May consider to simplify the axiom as is_about some human and has_role some 'human participant under investigation'

EUPATH:0022057: information on whether specimen collection prompted by sign of fever
logical axiom: is_about some 'specimen collection objective'
  - 'specimen collection objective' is A objective specification to obtain a material entity for potential use as an input during an investigation. Not sure it is the meaning of EUPATH:0022057.

EUPATH:0000154 duration of abdominal pain
logical axiom: 'is duration of' some 'Abdominal pain'
  - range of 'is duration of' is process. 'Abdominal pain' is quality not process.

EUPATH:0000138 participant observation duration time
logical axiom: 'is duration of' some	('part of' some 'study design execution') and ('has participant' some 'participant under investigation')
  - not clear what is the intersection process of process ('part of' some 'study design execution') and process ('has participant' some 'participant under investigation'). May consider to simplify it as is_about process and ('has participant' some 'participant under investigation')

EUPATH:0000423 parasite species information
logical axiom: Equivalent_To 'data item' and is_about some is_specified_output_of some 'organism identification assay' and realizes some ('evaluant role' and 'role of' some 'blood specimen')
  - I think it cannot be Equivalent_To axiom if not mention parasite in the axiom
  - If it is 'data item', may consider to remove 'information' in the label, rename it like 'parasite species datum'.

A couple of terms related to diagnosis, logical axioms are inconsistent. Need to consider which one we'd like to use.
  - EUPATH:0000425	information on malaria parasite infection diagnosis past year
  - EUPATH:0021034	information on Plasmodium malariae diagnosis within past year

ps: John: I found you added some logical axioms based on the textual definitions. Since some of terms were created at the beginning of the clinEpi project, they may not correct, such as being used different from the time they were added. I'd prefer to add logical axioms based on how we use the terms now and improve and update textual definitions.

**Comment by johnwjudkins** [comment]
EUPATH:0000425 is about Plasmodium (any species), whereas EUPATH:0021034 is about Plasmodium malariae. Both are about the disease "malaria", but only EUPATH:0021034 is specifically about the species "malariae".

**Comment by johnwjudkins** [comment]
Revised axioms of original post, based on comments in this thread:

ID | label |   | superclass |   | object property |   | object | notes
-- | -- | -- | -- | -- | -- | -- | -- | --
EUPATH:0000310 | information on observation details | Equivalent To | information content entity | and | is about | some | 'clinical visit' | commented but OK
EUPATH:0000430 | information on antimalarial drug used last year | SubClass Of | information content entity | and | mentions | some | 'has active ingredient' only ('has role' some antimalarial) | changed per Jie's comment
OBIB:0000029 | medication material | Equivalent To | material entity | and | has role | some | 'medication role' | no comment
EUPATH:0000302 | information on dwelling facilities | Equivalent To | information content entity | and | is about | some | 'dwelling facility' | changed after Chris's comment
EUPATH:0000303 | information on dwelling physical characteristics | SubClass Of | information content entity | and | is about | some | dwelling | changed after Jie's comment. "Total area" is a characteristic, but it is not "part" of the dwelling
EUPATH:0010036 | information on eligibility criterion | Equivalent To | directive information entity | and | mentions | some | 'eligibility criterion' | no comment
EUPATH:0000411 | information on existing illness | SubClass Of | information content entity | and | is about | some | 'human participant under investigation' and 'participates in' some 'disease course' | changed per Jie's comment
EUPATH:0000381 | information on kitchen location | SubClass Of | information content entity | and | is about | some | dwelling | no comment
EUPATH:0000425 | information on malaria parasite infection diagnosis past year | SubClass Of | information content entity | and | is about | some | diagnosis and mentions some malaria | changed per Jie's comment; I avoid declaring information about information, but there are examples of this
EUPATH:0000391 | information on organization responsible for treating bed nets | SubClass Of | information content entity | and | is about | some | organization | no comment
EUPATH:0000307 | information on participant study details | Equivalent To | information content entity | and | is about | some | 'study design execution' and 'has participant' some 'Homo sapiens' | changed based on Jie's comment but different from her suggestion
EUPATH:0011730 | information on breastfeeding process | Equivalent To | information content entity | and | is about | some | 'breastfeeding process' | no comment
EUPATH:0010037 | information on relation to participant | SubClass Of | information content entity | and | is about | some | 'Homo sapiens' | no comment
EUPATH:0000607 | information on weight loss in last three months | SubClass Of | information content entity | and | is about | some | 'Weight loss' | no comment
EUPATH:0000420 | information on where malaria diagnosed in last 12 months | SubClass Of | information content entity | and | is about | some | 'geographic location' and 'contains process' some ('diagnostic process' and has_specified_output some (diagnosis and mentions some malaria)) | no comment
EUPATH:0010579 | information on whether Adenovirus ELISA performed | SubClass Of | information content entity | and | is about | some | specimen | changed per Chris's comment
EUPATH:0000383 | information on whether occupant owns or pays rent on dwelling | SubClass Of | information content entity | and | is about | some | dwelling | no comment
EUPATH:0022057 | information on whether specimen collection prompted by sign of fever | SubClass Of | information content entity | and | is about | some | 'specimen collection process' | changed per Jie's comment
EUPATH:0000154 | duration of abdominal pain | SubClass Of | time measurement datum | and | is duration of | some | process | may need further discussion to connect 'Abdominal pain'
EUPATH:0000359 | occupation | SubClass Of | information content entity | and | is about | some | realizes some 'social role' | no comment
EUPATH:0022049 | duration of current secondary occupation | SubClass Of | time measurement datum | and | is duration of | some | realizes some ('social role' and 'role of' some 'human participant under investigation') | no comment
EUPATH:0000138 | participant observation duration time | SubClass Of | time measurement datum | and | is duration of | some | study design execution' and ('has participant' some 'participant under investigation') | simplified per Jie's comment but not the same as her suggestion
EUPATH:0023050 | treatment start date | SubClass Of | time measurement datum | and | is about | some | 'process boundary' and starts some treatment | no comment
EUPATH:0023051 | treatment start time | SubClass Of | time measurement datum | and | is about | some | 'process boundary' and starts some treatment | no comment
EUPATH:0000423 | parasite species information | Equivalent To | data item | and | is_specified_output_of | some | 'organism identification assay' and realizes some ('evaluant role' and 'role of' some 'blood specimen') | no comment
EUPATH:0021034 | information on Plasmodium malariae diagnosis within past year | SubClass Of | information content entity | and | is about | some | diagnosis and mentions some 'Plasmodium malariae' | changed to match other ICE about diagnosis

**Comment by johnwjudkins** [comment]
Axioms for additional information content entities:

ID | label |   | superclass |   | object property |   | object
-- | -- | -- | -- | -- | -- | -- | --
EUPATH:0000291 | treatment outcome information | SubClass Of | information content entity | and | is about | some | treatment
EUPATH:0000605 | 'summary information of investigation' | SubClass Of | information content entity | and | is about | some | investigation
EUPATH:0000604 | 'sequencing batch information' | SubClass Of | information content entity | and | is about | some | 'sequencing assay'
OBI:0000905 | 'sequence feature annotation' | SubClass Of | information content entity | and | is about | some | region
EUPATH:0000358 | 'secondary economic activity in last month' | SubClass Of | information content entity | and | is about | some | 'economic activity'
EUPATH:0000126 | 'sample available information' | SubClass Of | information content entity | and | is about | some | specimen and is_specified_output_of some ('specimen collection process' and 'part of' some 'clinical visit')
EUPATH:0022038 | 'rivers traveled on most recent trip' | SubClass Of | information content entity | and | mentions | some | river
EUPATH:0023001 | 'relocation information' | SubClass Of | information content entity | and | is about | some | household
EUPATH:0000376 | 'relationship to head of Family' | SubClass Of | information content entity | and | is about | some | 'family relationship' and 'inheres in' some 'participant under investigation'
EUPATH:0000206 | 'plasma sample lost information' | SubClass Of | information content entity | and | is about | some | blood plasma specimen
EUPATH:0000386 | information on place visited during a trip' | SubClass Of | information content entity | and | is about | some | 'geographic location'
EUPATH:0023055 | information on participant travel in the last twelve months' | SubClass Of | information content entity | and | is about | some | 'human participant under investigation'

**Comment by cstoeckert** [comment]
For EUPATH:0000154, I don't think it's useful to have an axiom on the duration of some process. Would be more useful to indicate that it's about some abdominal pain.

**Comment by johnwjudkins** [comment]
Changed EUPATH:0000154 to 'is about' some 'Abdominal pain'.

**Comment by johnwjudkins** [comment]
Minor edit: the class is 'human dwelling'; there is no 'dwelling'.

**Comment by johnwjudkins** [comment]
These are in the new release. Closing.
