### ISSUE TITLE
NTR: Eukaryote detection and abundance analysis

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB-ontology/VEuPathDB-ontology#392]
For new term requests, please provide the following information:
**Term Label** Eukaryote detection and abundance analysis

**Synonyms** NA

**Definition** Abundance of eukaryotic species detected using the CORRAL method [[1](https://www.biorxiv.org/content/10.1101/2022.03.09.483664v1)]

**Suggested Parent Term** Whole metagenome sequencing assay https://www.ebi.ac.uk/ols/ontologies/eupath/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0002623

**Examples** NA

**Contributor** NA

**Requester** MicrobiomeDB

**Comment by zhengj2007** [comment]
Some related terms have been added as children of [data transformation](https://ontobee.org/ontology/EUPATH?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0200000)

**Comment by asizemore** [comment]
Thanks @zhengj2007 ! Is there anything more you need from me at this time?

**Comment by zhengj2007** [comment]
Discussed on the call. It is a child of 'data transformation' (data analysis). 

Thanks @asizemore for submitting the term.
@johnwjudkins will work on the definition and add the term in the ontology. He will contact you  if he needs more information.

**Comment by johnwjudkins** [comment]
My suggestions: 
Label: analysis of eukaryote abundance
Definition: A data transformation that uses data from a whole metagenome sequencing assay and CORALE (for Clustering of Reference Alignments) software to specify taxa of Eukaryota in a specimen. 
Definition source: https://www.biorxiv.org/content/10.1101/2022.03.09.483664v1

**Comment by asizemore** [comment]
hey @johnwjudkins ! The name got changed so it's CORRAL now instead of CORALE. Otherwise looks good to me! I'll check in with Dan to get his opinion as well.
