### ISSUE TITLE
NTR: resistance to tebuconazole

### ISSUE THREAD

**Issue by weili-apidb** [VEuPathDB-ontology/VEuPathDB-ontology#397]
phenotype: resistance to tebuconazole

**Comment by zhengj2007** [comment]
@weili-apidb I found two existing ontology terms.

http://purl.obolibrary.org/obo/FYPO_0007716
An increased chemical resistance phenotype observed in the vegetative growth phase of the life cycle in which cells grow in the presence of a higher concentration of tebuconazole than normal.
(This is fission yeast phenotype) 

http://purl.obolibrary.org/obo/PHIPO_0000679
A growth phenotype which describes the resistance of individuals or populations after exposure to tebuconazole. Typically, organisms are deemed resistant to a chemical if they survive at a concentration of the chemical that does not allow wild type individuals or populations to grow.
(This is more general phenotype) 

Does one of them fit your needs?

**Comment by Achchuthan** [comment]
Hi @weili-apidb, @weili-apidb,
I prefer the PHIPO term as this is a more taxon-generic ontology than FYPO. Please go ahead with using http://purl.obolibrary.org/obo/PHIPO_0000679
