### ISSUE TITLE
NTR: Boolean datum

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#40]
Definition: A data item that indicates either the presence or the absence of some thing.
(I had previously suggested "binary datum" but this is more specific and in line with OBI development of value specifications.)

**Comment by zhengj2007** [comment]
How is it difference from adding a new term under 'value specification', such as 'binary/boolean value specification'?

**Comment by johnwjudkins** [comment]
We use 'categorical measurement datum' as superclass for terms labeled as 'presence of [species] by [assay]', each of which have a value that indicates the presence or absence of a species (and we decided to use that category instead of 'categorical value specification'). Placing these terms under 'Boolean datum' instead would distinguish these terms from the terms ClinEpi describes as "raw" data.

**Comment by johnwjudkins** [comment]
As discussed, we are resolving this issue by introducing the class 'presence of organism in specimen', defined as "A data item that indicates whether some organism is present in a specimen."
