### ISSUE TITLE
NTR: Could not determine Accession Numbers from Characteristics [organism]

### ISSUE THREAD

**Issue by weili-apidb** [VEuPathDB-ontology/VEuPathDB-ontology#402]
Could not determine Accession Numbers for the following terms of Characteristics [organism]:
------------------------------------------------
Grape
RPWYT-35
COUCAL
HON-9
KWALE
RNWYT-18
29TH HRSWN-8
COUCAL
RAWYT-1-26
19TH ESBWYT-45
20TH FHBSN-50
19TH EBSWYT-18
19TH EBSWYT-82
Oryx
Moose
----------------------------------------------------
ISA simple file:
https://github.com/VEuPathDB/ApiCommonMetadataRepository/blob/master/ISA/metadata/EUSTDY0168/s_study_sample.txt

**Comment by zhengj2007** [comment]
Organism (host of fungus in this study) field is required to provide ontology terms as values. Here are mappings of some of the terms you listed. 

term | mapped ontology term label | mapped ontology term ID
-|-|-
Grape | Vitis | NCBITaxon_3603
COUCAL | Centropus | NCBITAXON_57401
Oryx | Oryx | NCBITAXON_9957
Moose | Alces alces | NCBITAXON_9852
KWALE | Francolinus | NCBITAXON_9018

If they are not available in the ontologyMappings.xml, need to add them under  section as:
 ` <ontologyTerm source_id="NCBITaxon_9606" type="characteristicValue" parent="characteristicQualifier">` 
   `  <name>human</name>` 
  ` </ontologyTerm>`

I have no idea about what the organisms of following terms:
- RPWYT-35
- HON-9
- RNWYT-18
- 29TH HRSWN-8
- RAWYT-1-26
- 19TH ESBWYT-45
- 20TH FHBSN-50
- 19TH EBSWYT-18
- 19TH EBSWYT-82

@weili-apidb Could you please provide more information?

**Comment by weili-apidb** [comment]
Hi Jie. Thank you for working on this. Those organisms are host (wheat variety). The original metadata file is attached in the redline ticket:
https://redmine.apidb.org/issues/47445

**Comment by zhengj2007** [comment]
@weili-apidb I added the mapped term to 'wheat' in the mapping table (see my first comment). 

I think the following terms are the wheat strains:
- RPWYT-35
- HON-9
- RNWYT-18
- 29TH HRSWN-8
- RAWYT-1-26
- 19TH ESBWYT-45
- 20TH FHBSN-50
- 19TH EBSWYT-18
- 19TH EBSWYT-82

Proposed to add an extra column for these terms, the column header can be 'lab host' and use 'wheat' in the Characteristics [organism] column. Besides it would be better to add prefix 'wheat' in the terms, such as 'wheat RPWYT-35', which would be easy for users to understand what the lab host is.

**Comment by weili-apidb** [comment]
ERROR:  Taxa with Accession Or Name [NCBITAXON_9018] were not found in the database
ERROR:  Taxa with Accession Or Name [NCBITAXON_57401] were not found in the database
RROR:  Taxa with Accession Or Name [NCBITAXON_9957] were not found in the database
ERROR:  Taxa with Accession Or Name [NCBITAXON_9852] were not found in the database

Seems like those terms are not added into http://purl.obolibrary.org/obo/eupath.owl

**Comment by weili-apidb** [comment]
Hi Jie. I have done that, but still don't have those accessions in FungiDB-inc.

**Comment by zhengj2007** [comment]
If the terms are not in the database ontology table, can we reload the NCBITaxon ontology?
