### ISSUE TITLE
Import the synonyms of all terms from external resources

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#409]
Current VEuPathDB ontology retrieved labels and definitions from external OBO Foundry ontologies but importing synonyms/alternative terms are optional. For using synonyms in solr search on the website, we should retrieve the synonym/'alternative term' annotation of the terms from all external ontologies.

**Comment by johnwjudkins** [comment]
I can work on that, but should the "has...synonym" annotations be mapped to 'alternative label' or remain as they are?
