### ISSUE TITLE
NTR: status of population endemicity

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#429]
For new term requests, please provide the following information:
**Term Label** status of population endemicity

**Synonyms** [optional]

**Definition** 
(I am unsure if my label name is ontologically correct but this is the description of the values I want to use in the variable).

I would like to make a new variable for describing tick populations collected in the field. The three values are ‘no records’, ‘reported’, ‘established’. Counties were classified as established if at least six individual ticks or at least two of the three host-seeking life stages had been identified in a single collection period. Here, a single collection period is defined as a single year. Counties were classified as reported if they failed to meet the criteria for established but if at least one tick of any life stage had been identified at any time in that county, or if county records did not specify the number of ticks or life stages collected. Lack of tick records from a county—“no records”—does not imply that ticks are absent from that county, only that records of ticks having been collected in the county are lacking.

**Suggested Parent Term** [required]

Material
-population - http://purl.obolibrary.org/obo/OBI_0000181

**Comment by zhengj2007** [comment]
How about label term as 'information on collected tick population' and add as a subclassOf 'information content entity'?
- no record of collected tick population (no records): A [record of missing knowledge](http://purl.obolibrary.org/obo/OBI_0000852) indicating lacking of information of collected tick population.
- reported information on collected tick population (reported):  An information of collected tick population that failed to meet the criteria for established but if at least one tick of any life stage had been identified at any time in that county, or if county records did not specify the number of ticks or life stages collected.
- established information on collected tick population (established): An information of collected tick population indicates at least six individual ticks or at least two of the three host-seeking life stages had been identified in a single collection period.

Will discuss in the ontology team meeting on term labels and definitions.

**Comment by bobular** [comment]
This looks great, thanks. If we could reformulate the `established` definition to remove any specific numbers, that would make it more generally applicable.

**Comment by zhengj2007** [comment]
I found information of “established”, “reported”, and “no record”:
https://www.cdc.gov/ticks/surveillance/TickSurveillanceData.html

**Comment by SAK22** [comment]
@bobular would you still like to remove the number from established? Once that is done I think this looks great!

**Comment by bobular** [comment]
Ah, yes, I see. The CDC definition makes it pretty official and I guess we can keep the "6". Will the new terms make reference to the CDC?

**Comment by johnwjudkins** [comment]
Some small changes just to make it clear:

label: information on collected tick population
definition: An information content entity that is about a population of tick specimens.

label: no record of collected tick population
definition: A [record of missing knowledge](http://purl.obolibrary.org/obo/OBI_0000852) indicating a lack of information on collected tick population.

label: reported information on collected tick population
definition: An information of collected tick population that does not meet the criteria for established information on collected tick population, but indicates that at least one tick (or an unspecified number of ticks) of any life stage had been identified at any time in a second-order administrative region.

label: established information on collected tick population
definition: An information on collected tick population that indicates that at least six individual ticks or at least two of the three host-seeking life stages had been identified in a single collection period in a second-order administrative region.

(Not every US state uses "county" to name its administrative divisions.)

**Comment by johnwjudkins** [comment]
EUPATH:0043259
EUPATH:0043260
EUPATH:0043261
EUPATH:0043262
