### ISSUE TITLE
Missing ontology scope

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#43]
According to OBO Foundry [principle 5](http://obofoundry.org/principles/fp-005-delineated-content.html), we should specify the scope of the VEuPathDB ontology. 

OBO Foundry principle 5: "The scope of an ontology is the extent of the domain or subject matter it intends to cover. The ontology must have a clearly specified scope and content that adheres to that scope."

Any suggestion on it?

**Comment by cstoeckert** [comment]
How about: "The scope of the VEuPathDB ontology is to support the annotation, representation, and organization of data in VEuPathDB (Eukaryotic Pathogen, Vector & Host Informatics Resources). The datatsets in VEuPathDB resources cover functional genomics, population biology, clinical epidemiology, and microbiomes."

**Comment by cstoeckert** [comment]
If only want keywrods, can use these: functional genomics, population biology, clinical epidemiology, and microbiomes

**Comment by zhengj2007** [comment]
Has been added and shown on OBO Foundry website.
http://www.obofoundry.org/ontology/eupath.html
