### ISSUE TITLE
general term for organism identification - should mention "taxon"?

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#432]
I think we should discuss here what we want for a general organism identification assay term before submitting to OBI. I had suggested revising the definition of [organism identification assay](http://purl.obolibrary.org/obo/OBI_0001624) to "An assay that identifies an organism in a specimen with regard to taxon." However, we have placeholder terms that refer to identification of Plasmodium specifically in its gametocyte or asexual stages. So the mention of "taxon" may be too specific, because identifying the life cycle stage can be as important as identifying the taxon. If so, we may want the definition "An assay that identifies an organism in a specimen."

**Comment by zhengj2007** [comment]
I'd prefer to make the term more general. Besides, I'd like the term can clarify whether identify including both what kind an organism is and how many the organism is in the specimen.

**Comment by johnwjudkins** [comment]
In that case the definition could be "An assay that specifies a type of organism and/or the number of individuals of a type of organism, in a specimen."

**Comment by zhengj2007** [comment]
related issue: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/424

**Comment by zhengj2007** [comment]
organism detection assay: An assay that detects a type of organism and/or the quantity of individuals of a type of organism.

**Comment by johnwjudkins** [comment]
https://github.com/obi-ontology/obi/issues/1633

**Comment by johnwjudkins** [comment]
The term has been merged into OBI. Closing.
