### ISSUE TITLE
NTR: Bag and mask resuscitation performed

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB-ontology/VEuPathDB-ontology#435]
For new term requests, please provide the following information:
**Term Label** Bag and mask resuscitation performed

**Synonyms** [optional]

**Definition** Multifilter value indicating if an infant had bag and mask resuscitation performed soon after birth

**Suggested Parent Term** [required]
Please look in the ontology hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/eupath) or choose one from following list: 
- [x ] Information (generically dependent on some artifact and stands in relation of aboutness to some entity, such as data, identifier, document)

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
Sheena, for ClinEpiDB

**Comment by johnwjudkins** [comment]
label: indicator of bag valve mask ventilation performed during baby delivery
definition: An information content entity that specifies whether bag valve mask ventilation was performed during a baby delivery.
definition source: http://purl.bioontology.org/ontology/SNOMEDCT/425447009
parent: information content entity

**Comment by SheenaTomko** [comment]
looks good, thanks

**Comment by johnwjudkins** [comment]
@zhengj2007 please review

**Comment by zhengj2007** [comment]
@johnwjudkins looks good to me.
