### ISSUE TITLE
NTR: Nyssorhynchus nuneztovari sensu lato

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#442]
For new term requests, please provide the following information:
**Term Label** Nyssorhynchus nuneztovari sensu lato

**Synonyms** Anopheles nuneztovari sensu lato

**Definition** [required except for organism name]
The definition should be understandable even for non-specialists. Include a PubMed ID or DOI to refer to any relevant article that provides additional information about the suggested term.

**Suggested Parent Term** [required]
Please look in the ontology hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/eupath) or choose one from following list: 
http://purl.obolibrary.org/obo/NCBITaxon_44543 - however....so what I am after is a parent of Nyssorhynchus nuneztovari sensu lato and the child that I now see here: http://purl.obolibrary.org/obo/NCBITaxon_30067 ...so I basically need your help where to place these!

**Requester** [optional]
VectorBase

**Comment by SAK22** [comment]
Thank you!

**Comment by bobular** [comment]
I would switch the synonym and main label in this case?

**Comment by zhengj2007** [comment]
@johnwjudkins Shall we close it since the term has been added?
