### ISSUE TITLE
NTR:  Early breastfeeding initiated

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB-ontology/VEuPathDB-ontology#451]
For new term requests, please provide the following information:
**Term Label** [required]
Early breastfeeding initiated

**Synonyms** [optional]

**Definition** [required except for organism name]
Whether breastfeeding was initiated within 1 hour of birth

**Suggested Parent Term** [required]
Please look in the ontology hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/eupath) or choose one from following list: 
- [ ] Material (independent of other entities and can be maintained through time, such as person, cell, sample)
- [ ] Process (has temporal proper parts and for some time depends on some material entity, such as life cycle, cell division, heart beating, sleeping)
- [x] Information (generically dependent on some artifact and stands in relation of aboutness to some entity, such as data, identifier, document)
- [ ] Characteristic/Quality (inheres in or is borne by other entities, such as height, color, disease)

http://purl.obolibrary.org/obo/EUPATH_0011730 | Breastfeeding

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
Please indicate which resource/database/project/ request the term.
ClinEpiDB

**Comment by johnwjudkins** [comment]
label: indicator of suckling behavior within hour after baby delivery
definition: An information on suckling behavior that indicates whether it started within a hour after baby delivery.
parent: [information on suckling behavior](https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/426)

**Comment by johnwjudkins** [comment]
Ready for review @SheenaTomko

**Comment by SheenaTomko** [comment]
Looks good @johnwjudkins!

**Comment by zhengj2007** [comment]
> parent: [information on suckling behavior](https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/426)

The link seems incorrect, it is an information rather than the process it is about.

The term looks good @johnwjudkins
