### ISSUE TITLE
NTR: Anopheles benarrochi B

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#454]
For new term requests, please provide the following information:
**Term Label** Anopheles benarrochi B

**Synonyms** [optional]

**Definition** [required except for organism name]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3583324/

**Suggested Parent Term** [required]
Please look in the ontology hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/eupath) or choose one from following list: 
- [ ] Material (independent of other entities and can be maintained through time, such as person, cell, sample) 
- I think this should go under **http://purl.obolibrary.org/obo/NCBITaxon_44543**

**Comment by johnwjudkins** [comment]
http://purl.obolibrary.org/obo/NCBITaxon_360405
