### ISSUE TITLE
Duplicate exact synonym terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#46]
We added the VEuPathDB display labels in the VEuPathDB ontology. So, some of the ontology terms with same synonym. I think it may cause confusion and prefer to remove them.

Here is the list of terms identified by OBO Dashboard checking. 

Term Label [ID] | Alternative Term
-- | --
presence of Vibrio cholerae O139 by   differential medium assay [EUPATH:0015293] | Vibrio cholerae O139, by bacteriology
data about Vibrio cholerae O139 by   differential medium assay [EUPATH:0015463] | Vibrio cholerae O139, by bacteriology
information specifying fever self-treated   in past 2 weeks [EUPATH:0021025] | Self-treated
indicator of self-treated malaria   [EUPATH:0021046] | Self-treated
presence of Plasmodium vivax by   microscopy [EUPATH:0021029] | Plasmodium vivax
Plasmodium vivax diagnosis within past   year [EUPATH:0021033] | Plasmodium vivax
presence of Plasmodium vivax by blood   sample PCR [EUPATH:0021050] | Plasmodium vivax
presence of Plasmodium vivax by falcivax   [EUPATH:0021054] | Plasmodium vivax
presence of Plasmodium malariae by   microscopy [EUPATH:0021030] | Plasmodium malariae
information on Plasmodium malariae   diagnosis within past year [EUPATH:0021034] | Plasmodium malariae
presence of Plasmodium malariae by blood   sample PCR [EUPATH:0021051] | Plasmodium malariae
presence of Plasmodium falciparum by   microscopy [EUPATH:0021028] | Plasmodium falciparum
Plasmodium falciparum diagnosis within   past year [EUPATH:0021032] | Plasmodium falciparum
presence of Plasmodium falciparum by   blood sample PCR [EUPATH:0021049] | Plasmodium falciparum
presence of Plasmodium falciparum by   falcivax [EUPATH:0021053] | Plasmodium falciparum
presence of Plasmodium falciparum by   optimal-IT [EUPATH:0021057] | Plasmodium falciparum
no Plasmodium by microscopy   [EUPATH:0021027] | Negative
no Plasmodium by blood sample PCR   [EUPATH:0021048] | Negative
no presence of Plasmodium by falcivax   [EUPATH:0021055] | Negative
no Plasmodium by optimal-IT   [EUPATH:0021059] | Negative
forgot which Plasmodium species in   diagnosis within past year [EUPATH:0021035] | Can't remember
forgot which antimalarial in most recent   treatment [EUPATH:0021038] | Can't remember
forgot where treatment within past year   occurred [EUPATH:0021047] | Can't remember
forgot whether used personal mosquito   repellent [EUPATH:0021066] | Can't remember
no knowledge of insecticide spraying in   last 12 months [EUPATH:0021073] | Can't remember

[VEuPathDB dashboard report](http://obo-dashboard-test.ontodev.com/eupath/robot_report.html)

**Comment by cstoeckert** [comment]
Simplest solution for the repeated alternative terms is to remove them as they are not helpful. For multifilter values, can prepend the parent category to make these distinct and useful.

**Comment by johnwjudkins** [comment]
Changed EUPATH:0015463 alternative term to "Vibrio cholerae O139, by bacteriology result"; this is the ClinEpi label. As for the multifilter values, I am prepending the ClineEpi parent name in parentheses e.g. '(Where treated) Can't remember' for EUPATH:0021047.

**Comment by zhengj2007** [comment]
Some terms with same synonym are found by ROBOT report need to be fixed.

Rule Name | Subject | Property | Value
-- | -- | -- | --
duplicate_exact_synonym | EUPATH:0021025 | IAO:0000118 | Self-treated
duplicate_exact_synonym | EUPATH:0021046 | IAO:0000118 | Self-treated
duplicate_exact_synonym | EUPATH:0021029 | IAO:0000118 | Plasmodium vivax
duplicate_exact_synonym | EUPATH:0021033 | IAO:0000118 | Plasmodium vivax
duplicate_exact_synonym | EUPATH:0021050 | IAO:0000118 | Plasmodium vivax
duplicate_exact_synonym | EUPATH:0021054 | IAO:0000118 | Plasmodium vivax
duplicate_exact_synonym | EUPATH:0021030 | IAO:0000118 | Plasmodium malariae
duplicate_exact_synonym | EUPATH:0021034 | IAO:0000118 | Plasmodium malariae
duplicate_exact_synonym | EUPATH:0021051 | IAO:0000118 | Plasmodium malariae
duplicate_exact_synonym | EUPATH:0021028 | IAO:0000118 | Plasmodium falciparum
duplicate_exact_synonym | EUPATH:0021032 | IAO:0000118 | Plasmodium falciparum
duplicate_exact_synonym | EUPATH:0021049 | IAO:0000118 | Plasmodium falciparum
duplicate_exact_synonym | EUPATH:0021053 | IAO:0000118 | Plasmodium falciparum
duplicate_exact_synonym | EUPATH:0021057 | IAO:0000118 | Plasmodium falciparum
duplicate_exact_synonym | EUPATH:0043028 | IAO:0000118 | house resting - daytime catch
duplicate_exact_synonym | EUPATH:0043057 | IAO:0000118 | house resting - daytime catch

**Comment by johnwjudkins** [comment]
In eupath_dev.owl, I changed the terms in the previous comment by prepending the ClineEpi parent name in parentheses as before, except for the terms with alternative label 'house resting - daytime catch'. I removed the alternative term and VectorBase ID from those two.

**Comment by johnwjudkins** [comment]
These changes are in the new release. Closing.
