### ISSUE TITLE
EFO:'anthropometric measurement'

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#461]
EFO is updated with a term for [anthropometric measurement](http://www.ebi.ac.uk/efo/EFO_0004302). Should this be imported (under [measurement datum](http://purl.obolibrary.org/obo/IAO_0000109)) and replace the project category placeholder 'Anthropometry' EUPATH:0000649?

**Comment by zhengj2007** [comment]
EFO is not an OBO Foundry ontology. Prefer not to replace EuPath term with EFO one.

**Comment by johnwjudkins** [comment]
[body morphological measurement](http://purl.obolibrary.org/obo/CMO_0000021) might be a better candidate to replace the Anthropometry placeholder. We already have CMO's [BMI](http://purl.obolibrary.org/obo/CMO_0000105) term, and that is a child of 'body morphological measurement'.

**Comment by zhengj2007** [comment]
We can check with clinEpi team and see whether they agree with it since 'Anthropometry' is a related Synonym of the term.
