### ISSUE TITLE
NTR: Strains of Anaplasma phagocytophilum

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#462]
For new term requests, please provide the following information:
**Term Label** [required]
Anaplasma phagocytophilum str. Ap-ha
Anaplasma phagocytophilum str. Ap-v1

**Synonyms** [optional]

**Definition** [required except for organism name]
[Trost et al. (2018)](javascript:;) identified three distinct clades of this intracellular bacterium by sequence divergence in the ankyrin A gene. The two clades that infect humans are known collectively as the Ap-ha strain and the strain that has not been shown to infect humans is known as Ap-v1. The Ap-v1 strain infects deer ([Massung et al. 2005](javascript:;)) and several other animals

https://academic.oup.com/jme/article/56/4/1122/5476390

**Suggested Parent Term** [required]

NCBITaxon_948 in EUPATH

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
Please indicate which resource/database/project/ request the term.

**Comment by johnwjudkins** [comment]
Please note that these EUPATH IDs have been replaced by recent additions to the NCBITaxon ontology:

Taxon name | Old IRI | Replacement IRI
-- | -- | --
Culex inconspicuosus | http://purl.obolibrary.org/obo/EUPATH_0043101 | http://purl.obolibrary.org/obo/NCBITaxon_2918769
Mimomyia hispida | http://purl.obolibrary.org/obo/EUPATH_0043108 | http://purl.obolibrary.org/obo/NCBITaxon_2918771
Uranotaenia mashonaensis | http://purl.obolibrary.org/obo/EUPATH_0043113 | http://purl.obolibrary.org/obo/NCBITaxon_48710

**Comment by johnwjudkins** [comment]
(deleted my previous comment)

ID | Label | Parent
-- | -- | --
EUPATH:0043254 | Anaplasma phagocytophilum str. Ap-ha | Anaplasma phagocytophilum
EUPATH:0043255 | Anaplasma phagocytophilum str. Ap-v1 | Anaplasma phagocytophilum
