### ISSUE TITLE
NTR: Borreliella mayonii

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#464]
For new term requests, please provide the following information:
**Term Label** [required]
Borreliella mayonii

**Synonyms** [optional]

**Definition** [required except for organism name]
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1674146

**Suggested Parent Term** [required]
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=64895&lvl=3&keep=1&srchmode=1&unlock

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
Please indicate which resource/database/project/ request the term.

**Comment by zhengj2007** [comment]
Borreliella mayonii is available in NCBITaxon
http://purl.obolibrary.org/obo/NCBITaxon_1674146
