### ISSUE TITLE
Propose to deprecate two terms without definition

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#47]
**object property: manifestation of [EUPATH:0000044]**
The relation is added for PRISM project aiming to infer class hierarchy that can be used as search filter on the website. Since we are taking different approach to achieve the goal, I suggest to obsolete the relation and removed all axioms that used the relation.

**annotation property: PRISM description [EUPATH:0000270]**
Not used and needed any more, suggest to obsolete

[VEuPathDB dashboard report](http://obo-dashboard-test.ontodev.com/eupath/robot_report.html)

**Comment by johnwjudkins** [comment]
These changes are in the release candidate (2020-03-13).
