### ISSUE TITLE
NTR: New taxon names

### ISSUE THREAD

**Issue by weili-apidb** [VEuPathDB-ontology/VEuPathDB-ontology#472]
Please add the following taxon names to ontology:

Puffinus newelli
Branta sandvicensis
Mareca americana
Anas acuta
Cygnus buccinator
Cygnus columbianus
Larus smithsonianus
Leucophaeus atricilla
Larus sp.
Brachyramphus marmoratus
Melanitta americana
Sterna hirundo
Circus hudsonius
Larus marinus
Bubo scandiacus
Branta canadensis
Leucophaeus pipixcan
Larus delawarensis
Cygnus olor
Phalacrocorax auritus

**Comment by zhengj2007** [comment]
http://purl.obolibrary.org/obo/NCBITaxon_232374 #Puffinus newelli
http://purl.obolibrary.org/obo/NCBITaxon_56282 #Branta sandvicensis
http://purl.obolibrary.org/obo/NCBITaxon_75832 #Mareca americana
http://purl.obolibrary.org/obo/NCBITaxon_28680 #Anas acuta
http://purl.obolibrary.org/obo/NCBITaxon_48397 #Cygnus buccinator
http://purl.obolibrary.org/obo/NCBITaxon_110926 #Cygnus columbianus
http://purl.obolibrary.org/obo/NCBITaxon_243888 #Larus smithsonianus
http://purl.obolibrary.org/obo/NCBITaxon_126679 #Leucophaeus atricilla
http://purl.obolibrary.org/obo/NCBITaxon_8911 #Larus
http://purl.obolibrary.org/obo/NCBITaxon_28694 #Brachyramphus marmoratus
http://purl.obolibrary.org/obo/NCBITaxon_1581554 #Melanitta americana
http://purl.obolibrary.org/obo/NCBITaxon_108405 #Sterna hirundo
http://purl.obolibrary.org/obo/NCBITaxon_2709557 #Circus hudsonius
http://purl.obolibrary.org/obo/NCBITaxon_8912 #Larus marinus
http://purl.obolibrary.org/obo/NCBITaxon_371907 #Bubo scandiacus
http://purl.obolibrary.org/obo/NCBITaxon_8853 #Branta canadensis
http://purl.obolibrary.org/obo/NCBITaxon_690715 #Leucophaeus pipixcan
http://purl.obolibrary.org/obo/NCBITaxon_126683 #Larus delawarensis
http://purl.obolibrary.org/obo/NCBITaxon_8869 #Cygnus olor
http://purl.obolibrary.org/obo/NCBITaxon_56069 #Phalacrocorax auritus

Found all the mapped NCBITaxon terms except 'Larus sp' (I think it means some species of Larus) that mapped to Larus which is a genus.
 
@weili-apidb Could you please check whether the mappings are OK?

**Comment by weili-apidb** [comment]
Yes, the mappings all look good. In fung-inc, the NCBI tax ID for "Larus sp" is 8911, so it is fine to map  'Larus sp' to Larus. Please add them in the eupath_isa.owl. Thank you.

**Comment by weili-apidb** [comment]
This is been successfully loaded to fung-inc. The issue is resolved. Thank you! Feel free to close this ticket.

**Comment by zhengj2007** [comment]
Need to import missing NCBITaxon terms in the ontology.

**Comment by zhengj2007** [comment]
@johnwjudkins Could you please review the mappings before I import the missing NCBITaxon terms if any?

**Comment by johnwjudkins** [comment]
@zhengj2007 Everything looks fine.
