### ISSUE TITLE
NTR: Cesarean delivery

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB-ontology/VEuPathDB-ontology#517]
**Term Label** [required]
Cesarean delivery

**Synonyms** [optional]
Cesarean section 
C-section
Cesarean birth

**Definition** [required except for organism name]
Whether the baby was delivered surgically through a cut (incision) made in the mother's abdomen and uterus

**Suggested Parent Term** [required]
Labor and delivery

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
microbiomeDB

**Comment by zhengj2007** [comment]
Propose to use OBO existing term, [caesarean section](http://purl.obolibrary.org/obo/OAE_0001041)
Defintion: A surgery where incisions are made through a woman's abdomen and uterus to deliver her baby.
Logical axiom: [human parturition procedure](https://ontobee.org/ontology/ONTONEO?iri=http://purl.obolibrary.org/obo/ONTONEO_00000280) and ([realizes](https://ontobee.org/ontology/ONTONEO?iri=http://purl.obolibrary.org/obo/BFO_0000055) some [concretizes](https://ontobee.org/ontology/ONTONEO?iri=http://purl.obolibrary.org/obo/RO_0000059) some [caesarean section plan](https://ontobee.org/ontology/ONTONEO?iri=http://purl.obolibrary.org/obo/ONTONEO_00000013))

**Comment by danicahelb** [comment]
yes that is fine, thanks @zhengj2007

**Comment by zhengj2007** [comment]
Import [caesarean section](http://purl.obolibrary.org/obo/OAE_0001041)

**Comment by johnwjudkins** [comment]
Adding as subclass of 'planned process'.
