### ISSUE TITLE
NTR: cm/year

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB-ontology/VEuPathDB-ontology#522]
For new term requests, please provide the following information:
**Term Label** [required]
cm/year

**Synonyms** [optional]

**Definition** [required except for organism name]
unit of measurement

**Suggested Parent Term** [required] 
unit

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
microbiomeDB

**Comment by zhengj2007** [comment]
Reserved ID: EUPATH_0009998

**Comment by johnwjudkins** [comment]
label: centimeter per year
definition: A rate unit that represents an increase in length of one centimeter in one year.
parent: [rate unit](http://purl.obolibrary.org/obo/UO_0000280)

Alternatively, I could broaden the definition to read "change" instead of "increase".

**Comment by danicahelb** [comment]
change is better thanks

**Comment by zhengj2007** [comment]
Does it fit [speed/velocity unit](http://purl.obolibrary.org/obo/UO_0000060) better than [rate unit](http://purl.obolibrary.org/obo/UO_0000280)?

**Comment by johnwjudkins** [comment]
We'll add this as an instance of 'unit'.

**Comment by johnwjudkins** [comment]
@zhengj2007 should we add "cm/year" as an annotation? Should it be an 'alternative label'?

**Comment by zhengj2007** [comment]
@johnwjudkins I'd prefer to add it as an 'alternative label'

**Comment by johnwjudkins** [comment]
EUPATH_0009998
label: centimeter per year
definition: A unit that represents a change in length of one centimeter in one year.
alternative label: cm/year
type: unit
example: the growth of a child during three years after birth

@zhengj2007 If this is OK, I'll make a pull request.
