### ISSUE TITLE
NTR: kg/year

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB-ontology/VEuPathDB-ontology#523]
For new term requests, please provide the following information:
Term Label [required]
kg/year

Synonyms [optional]

Definition [required except for organism name]
unit of measurement

Suggested Parent Term [required]
unit

Examples [optional]

Contributor [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

Requester [optional]
microbiomeDB

**Comment by zhengj2007** [comment]
Reserved ID: EUPATH_0009999

**Comment by johnwjudkins** [comment]
label: kilogram per year
definition: A rate unit that represents an increase in mass of one kilogram in one year.
parent: [rate unit](http://purl.obolibrary.org/obo/UO_0000280)

I also could broaden the definition to change in mass rather than increase.

**Comment by danicahelb** [comment]
change is better, thanks @johnwjudkins

**Comment by zhengj2007** [comment]
The definition of 'rate unit' is 'A unit which represents a standard measurement occurrence of a process per unit time.' So not sure whether it is the unit we mean. I found the term [mass rate](http://purl.obolibrary.org/obo/NCIT_C179799). However, don't find 'mass rate unit' in any OBO ontologies.

**Comment by johnwjudkins** [comment]
We can place this under 'unit'.

**Comment by johnwjudkins** [comment]
EUPATH_0009999
label: kilogram per year
definition: A unit that represents a change in mass of one kilogram in one year.
alternative label: kg/year
example: the increase in mass of a child during three years after birth
type: unit
@zhengj2007
