### ISSUE TITLE
NTR: DOI - digital object identifier

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#524]
Please can we (VectorBase/PopBio) have this term in the VEuPath Ontology?

http://purl.obolibrary.org/obo/OBI_0002110 "digital object identifier"

We already have its sibling, PubMed ID, which is great.

**Comment by zhengj2007** [comment]
Import http://purl.obolibrary.org/obo/OBI_0002110 "digital object identifier"
