### ISSUE TITLE
NTR: phenothrin

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#525]
For new term requests, please provide the following information:
**Term Label** 

* phenothrin

We currently have: `phenothrin [(1R)-trans- isomer]` used in PopBio dataset VBP0000024
Publication: https://pubmed.ncbi.nlm.nih.gov/1474386/ NOT AVAILABLE ONLINE
WAIT - yes it is: https://www.biodiversitylibrary.org/content/part/JAMCA/JAMCA_V08_N4_P394-397.pdf

There is actually no mention of phenothrin in the paper. They call it Sumithrin. Looking up Sumithrin in CHEBI we get this term:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:34916 which is a synonym for `phenothrin`

So we just need CHEBI:34916 added to VEuPath ontology please.

**Requester** VectorBase/PopBio

**Comment by zhengj2007** [comment]
Import CHEBI:34916 in the VEuPathDB ontology.
