### ISSUE TITLE
Figure out what to do with `Anopheles amhaicus`

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#526]
Original VBcv term:
```
[Term]
id: VBsp:0000067
name: Anopheles amhaicus
alt_id: NCBITaxon:193510
def: "A member species of the species complex Anopheles gambiae sensu lato. All populations found in Ethiopia." [PT:PT]
synonym: "Anopheles quadriannualtus B " EXACT []
synonym: "Anopheles quadriannulatus sp. B" EXACT []
xref: NCBITaxon:193510
is_a: VBsp:0003480 ! Anopheles gambiae sensu lato
created_by: Topito
creation_date: 2013-05-30T22:57:53Z
```

Not in NCBI

No results found for "Anopheles amhaicus" in Google

Only seen in VBP0000794 - pubmed ID 35030201

Sarah, please could you figure out if this really is _Anopheles quadriannualtus B_...

**Comment by bobular** [comment]
Oh, looks like it was a typo.  

Anopheles amharicus seems more correct. Not in NCBI still though.

**Comment by zhengj2007** [comment]
@bobular What is the parent term of 'Anopheles amharicus'? Is it [Anopheles quadriannulatus B](http://purl.obolibrary.org/obo/NCBITaxon_193510) or a kind of it?

Besides, I cannot find 'Anopheles gambiae sensu lato' in NCBITaxon.

**Comment by SAK22** [comment]
So I found this paper!
https://pubmed.ncbi.nlm.nih.gov/26131476/
and this
https://www.wrbu.si.edu/vectorspecies/mosquitoes/amharicus

Showing that Anopheles amharicus parent term should be Anopheles gambiae sensu lato which I think in NCBItaxon (which seems confusing to me)! It would be the gambiae complex term.

I hope that helps!

**Comment by zhengj2007** [comment]
@SAK22 Thanks for finding the reference paper. I cannot find 'Anopheles gambiae sensu lato' in NCBITaxon but in MIRO. The similar label I found in NCBITaxon is [Anopheles letifer sensu lato](http://purl.obolibrary.org/obo/NCBITaxon_2751809). I don't think it is correct. Could you please help with it? Thanks!

**Comment by SAK22** [comment]
No that is not correct you are right, in NCBITaxon it is as I confirm above. It would be the 'gambiae complex'. Hope that helps!

**Comment by zhengj2007** [comment]
Thanks! @SAK22

**Comment by bobular** [comment]
Thanks both.  Should `Anopheles quadriannulatus B` be a synonym, @SAK22 ?

**Comment by SAK22** [comment]
@bobular @zhengj2007 I found papers that state these two things below, so YES I think it should be a synonym.

Two new species within the Anopheles gambiae complex are here described and named. Based on molecular and bionomical evidence, the An. gambiae molecular "M form" is named Anopheles coluzzii Coetzee & Wilkerson sp. n., while the "S form" retains the nominotypical name Anopheles gambiae Giles. Anopheles quadriannulatus is retained for the southern African populations of this species, while the Ethiopian species is named Anopheles amharicus Hunt, Wilkerson & Coetzee sp. n., based on chromosomal, cross-mating and molecular evidence.

Sibling species A and B of Anopheles quadriannulatus (Theobald) are recognized as allopatric members of the Anopheles gambiae Giles complex of Afrotropical mosquitoes (Diptera: Culicidae). Species A represents An. quadriannulatus sensu stricto, widespread in southern Africa, whereas An. quadriannulatus species B occurs in Ethiopia.

**Comment by zhengj2007** [comment]
Since 'Anopheles quadriannulatus B' is a NCBITaxon term, how about we import the term in the VEuPathDB ontology?

Add [Anopheles quadriannulatus B](http://purl.obolibrary.org/obo/NCBITaxon_193510) in the VEuPathDB ontology
- synonym: 'Anopheles amharicus' and 'Anopheles quadriannulatus sp. B' as synonym
- parent [gambiae species complex](http://purl.obolibrary.org/obo/NCBITaxon_44542)

@bobular @SAK22 Does it work?

**Comment by SAK22** [comment]
Works for me, @bobular does that work for you?

**Comment by bobular** [comment]
Yes that's great @zhengj2007 @SAK22  Thanks!

**Comment by zhengj2007** [comment]
@johnwjudkins Do you want to work on the issue or you'd prefer I take care of it?
