### ISSUE TITLE
NTR: Anopheles culicifacies species complex

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#527]
VEuPathDB ontology currently has
![image](https://user-images.githubusercontent.com/308639/221658369-041dd24b-4309-40fd-aab2-36e9db91775b.png)

The A and D species should be children of the AD subgroup, if that's possible.

Then add a new term "Anopheles culicifacies BCE subgroup" (sibling of the AD subgroup; with a EUPATH:nnnnnnn ID) and add children "Anopheles culicifacies B", "Anopheles culicifacies C", and "Anopheles culicifacies E" using the [NCBITaxon terms](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=63408&lvl=3&keep=1&srchmode=1&unlock)

**Requester** 

PopBio/VB

**Comment by zhengj2007** [comment]
Move [Anopheles culicifacies A](http://purl.obolibrary.org/obo/NCBITaxon_63366) and [Anopheles culicifacies D](http://purl.obolibrary.org/obo/NCBITaxon_216372) under [Anopheles culicifacies AD subgroup](http://purl.obolibrary.org/obo/EUPATH_0043087)

@bobular Can I say [Anopheles culicifacies AD subgroup](http://purl.obolibrary.org/obo/EUPATH_0043087) = [Anopheles culicifacies A](http://purl.obolibrary.org/obo/NCBITaxon_63366) or [Anopheles culicifacies D](http://purl.obolibrary.org/obo/NCBITaxon_216372) ?

Need to add a new term in VEuPathDB ontology:  "Anopheles culicifacies BCE subgroup" (parent is: [culicifacies species complex](http://purl.obolibrary.org/obo/NCBITaxon_63408))
Import three NCBITaxon terms as its children:

1. Anopheles culicifacies B [NCBITaxon_63367](http://purl.obolibrary.org/obo/NCBITaxon_63367)
2. Anopheles culicifacies C [NCBITaxon_63368](http://purl.obolibrary.org/obo/NCBITaxon_63368)
3. Anopheles culicifacies E [NCBITaxon_216373](http://purl.obolibrary.org/obo/NCBITaxon_216373)

proposed logical axiom for term "Anopheles culicifacies BCE subgroup": 
= "Anopheles culicifacies B" or "Anopheles culicifacies C" or "Anopheles culicifacies E"

**Comment by bobular** [comment]
That's all correct, thanks Jie

**Comment by zhengj2007** [comment]
@johnwjudkins I will import the NCBITaxon terms. Do you mind taking care of adding the term "Anopheles culicifacies BCE subgroup" in the eupath_terms template? So, it will not end that both of us touch the same template.

**Comment by johnwjudkins** [comment]
Since the defining axioms for Anopheles culicifacies BCE subgroup are based on NCBITaxon terms, I will submit a pull request to add them after the NCBITaxon terms are merged.
