### ISSUE TITLE
NTR: species terms

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#535]
Taxon terms listed in https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/329

- "Aedes cataphylla" NCBITaxon_120871 (aka _Ochlerotatus cataphylla_)
- "Aedes condolescens" - not in NCBI - was in [MIRO](https://www.ebi.ac.uk/ols/ontologies/miro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMIRO_40001012)  which should give taxonomic context
- "Aedes epactius" NCBITaxon_173086 (aka _Ochlerotatus epactius_)
- "Aedes khazani" NCBITaxon_1245347 (aka _Phagomyia khazani_)
- "Aedes lineatopennis" NCBITaxon_869251
- "Aedes malayensis" NCBITaxon_1424567
- "Aedes niphadopsis" NCBITaxon_1205941 (aka _Ochlerotatus niphadopsis_)
- "Aedes poicilius" NCBITaxon_2773399
- "Aedes provocans" NCBITaxon_743693 (aka _Ochlerotatus provocans_)
- "Aedes pullatus" NCBITaxon_120876
- "Aedes schizopinax" NCBITaxon_1206307 (aka _Ochlerotatus schizopinax_)
- "Aedes zoosophus" NCBITaxon_1206036 (aka _Ochlerotatus zoosophus_)
- "Anopheles baimaii" NCBITaxon_48725
- "Anopheles demeilloni" NCBITaxon_1521113
- "Anopheles donaldi" NCBITaxon_2745526
- "Anopheles grabhamii" not in NCBI - was in [MIRO](https://www.ebi.ac.uk/ols/ontologies/miro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMIRO_40000104) 
- "Anopheles hancocki" NCBITaxon_1521115
- "Anopheles hodgkini" not in NCBI - was in [MIRO](http://purl.obolibrary.org/obo/MIRO_40003399)
- "Anopheles namibiensis" not in NCBI - was in [MIRO](http://purl.obolibrary.org/obo/MIRO_40000142) 
- "Anopheles oswaldoi" NCBITaxon_43181
- "Anopheles paludis" NCBITaxon_345577
- "Anopheles pollicaris" not in NCBI - [MIRO term](http://purl.obolibrary.org/obo/MIRO_40003423)
- "Anopheles vinckei" NCBITaxon_1300248
- Anophelinae - NCBITaxon_43816 a higher level term (child of Culicidae) that we don't have in VEuPath ontology currently that we have annotated some data with.
- "Armigeres flavus" NCBITaxon_1245360
- "Armigeres kesseli" NCBITaxon_753891
- "Armigeres magnus" not in NCBI - [MIRO term](http://purl.obolibrary.org/obo/MIRO_40000247)
- "Armigeres traubi" not in NCBI - [MIRO term](http://purl.obolibrary.org/obo/MIRO_40000251)
- "Bacillus thuringiensis var. israelensis" - this was used in VBP0000642 and is in IRO/MIRO as IRO:0000124
- "Coquillettidia crassipes" NCBITaxon_1245327
- "Culex abominator" - cool name - NCBITaxon_1085687
- "Culex alis" not in NCBI - [MIRO term](http://purl.obolibrary.org/obo/MIRO_40002490) however I noticed in OLS search there is also `Culex nr. alis KR26_A_1` in NCBI http://purl.obolibrary.org/obo/NCBITaxon_2793868 - maybe we should search the other "not NCBI" species in OLS? What does "nr." mean? Ah, thanks Google. https://en.wikipedia.org/wiki/Species_affinis It means near. So I guess NCBITaxon_2793868 is NOT _Culex alis_ but it's close!
- "Culex bahamensis" -> http://purl.obolibrary.org/obo/NCBITaxon_1206047
- "Culex declarator"  -> http://purl.obolibrary.org/obo/NCBITaxon_707281
- "Culex whitei" -> not in NCBI -> http://purl.obolibrary.org/obo/MIRO_40002718 
- "genus Armigeres" -> http://purl.obolibrary.org/obo/NCBITaxon_124916 (_Armigeres subalbatus_ http://purl.obolibrary.org/obo/NCBITaxon_124917 will need to be moved under the genus term)
- "genus Lutzomyia" -> http://purl.obolibrary.org/obo/NCBITaxon_7199 (Lutzomyia longipalpis will need to be moved under this)
- "Mansonia indiana" -> http://purl.obolibrary.org/obo/NCBITaxon_2035320
- "Psorophora varipes" -> http://purl.obolibrary.org/obo/NCBITaxon_2488823

**Comment by zhengj2007** [comment]
### Following NCBITaxon terms will be imported in VEuPathDB ontology.
http://purl.obolibrary.org/obo/NCBITaxon_120871 #Ochlerotatus cataphylla
http://purl.obolibrary.org/obo/NCBITaxon_173086 #Ochlerotatus epactius
http://purl.obolibrary.org/obo/NCBITaxon_1245347 #Phagomyia khazani
http://purl.obolibrary.org/obo/NCBITaxon_869251 #Aedes lineatopennis
http://purl.obolibrary.org/obo/NCBITaxon_1424567 #Aedes malayensis
http://purl.obolibrary.org/obo/NCBITaxon_1205941 #Ochlerotatus niphadopsis
http://purl.obolibrary.org/obo/NCBITaxon_2773399 #Aedes poicilius
http://purl.obolibrary.org/obo/NCBITaxon_743693 #aka Ochlerotatus provocans
http://purl.obolibrary.org/obo/NCBITaxon_120876 #Aedes pullatus
http://purl.obolibrary.org/obo/NCBITaxon_1206307 #Ochlerotatus schizopinax (Aedes schizopinax)
http://purl.obolibrary.org/obo/NCBITaxon_1206036 #Ochlerotatus zoosophus (Aedes zoosophus)
http://purl.obolibrary.org/obo/NCBITaxon_48725 #Anopheles baimaii
http://purl.obolibrary.org/obo/NCBITaxon_1521113 #Anopheles demeilloni
http://purl.obolibrary.org/obo/NCBITaxon_2745526 #Anopheles donaldi
http://purl.obolibrary.org/obo/NCBITaxon_1521115 #Anopheles hancocki
http://purl.obolibrary.org/obo/NCBITaxon_43181 #Anopheles oswaldoi
http://purl.obolibrary.org/obo/NCBITaxon_345577 #Anopheles paludis
http://purl.obolibrary.org/obo/NCBITaxon_1300248 #Anopheles vinckei
http://purl.obolibrary.org/obo/NCBITaxon_43816 #Anophelinae (child of Culicidae)
http://purl.obolibrary.org/obo/NCBITaxon_1245360 #Armigeres flavus
http://purl.obolibrary.org/obo/NCBITaxon_753891 #Armigeres kesseli
http://purl.obolibrary.org/obo/NCBITaxon_1245327 #Coquillettidia crassipes
http://purl.obolibrary.org/obo/NCBITaxon_1085687 #Culex abominator
http://purl.obolibrary.org/obo/NCBITaxon_1206047 #Culex bahamensis
http://purl.obolibrary.org/obo/NCBITaxon_707281 #Culex declarator
http://purl.obolibrary.org/obo/NCBITaxon_124916 #genus Armigeres
http://purl.obolibrary.org/obo/NCBITaxon_7199 #genus Lutzomyia
http://purl.obolibrary.org/obo/NCBITaxon_2035320 #Mansonia indiana
http://purl.obolibrary.org/obo/NCBITaxon_2488823 #Psorophora varipes

Due to our import strategy, two terms are not under genus. Import the genus terms and need to check:
- Armigeres subalbatus http://purl.obolibrary.org/obo/NCBITaxon_124917 will need to be moved under the genus term 'genus Armigeres'
- Lutzomyia longipalpis child of "genus Lutzomyia"

### Following terms will be added.
Label: Aedes condolescens
Definition: A species of subgenus Ochlerotatus.
Definition source: MIRO_40001012
Parent: http://purl.obolibrary.org/obo/NCBITaxon_53545 Ochlerotatus <subgenus>

Label: Anopheles grabhamii
Definition: A species of subgenus Anopheles.
Definition source: MIRO_40000104
Parent: http://purl.obolibrary.org/obo/NCBITaxon_44482 Anopheles <subgenus>

Label: Anopheles hodgkini
Definition: A species of subgenus Anopheles.
Definition source: MIRO:40003399
Parent: http://purl.obolibrary.org/obo/NCBITaxon_44482 Anopheles <subgenus>

Label: Anopheles namibiensis
Definition: A species of subgenus Anopheles.
Definition source: MIRO:40000142
Parent: http://purl.obolibrary.org/obo/NCBITaxon_44482 Anopheles <subgenus>

Label: Anopheles pollicaris
Definition: A species of subgenus Anopheles.
Definition source: MIRO:40003423
Parent: http://purl.obolibrary.org/obo/NCBITaxon_44482 Anopheles <subgenus>

Label: Armigeres magnus
Definition: A species of subgenus Leicesteria.
Definition source: MIRO:40000247
Parent: http://purl.obolibrary.org/obo/NCBITaxon_317812 Leicesteria (not in VEuPathDB ontology, need to import)

Label: Armigeres traubi
Definition: A species of subgenus Leicesteria. 
Definition source: MIRO:40000251
Parent: http://purl.obolibrary.org/obo/NCBITaxon_317812 Leicesteria

Label: Bacillus thuringiensis var. israelensis
Definition: A strain of Bacillus thuringiensis
Definition source: IRO:0000124, VBP0000642
Parent: http://purl.obolibrary.org/obo/NCBITaxon_1428 Bacillus thuringiensis (not in VEuPathDB ontology, need to import)

Label: Culex alis
Definition: A species of subgenus Culex.
Definition source: MIRO:40002490
Parent: http://purl.obolibrary.org/obo/NCBITaxon_53527 Culex <subgenus>

Label: Culex whitei
Definition: A species of subgenus Culex.
Definition source: MIRO_40002718
Parent: http://purl.obolibrary.org/obo/NCBITaxon_53527 Culex <subgenus>

@bobular Could you please review whether the terms? Thanks!

**Comment by bobular** [comment]
Hi @zhengj2007 - thanks for the quick turnaround.

It all looks good, thank you.

**Comment by johnwjudkins** [comment]
[Bacillus thuringiensis serovar israelensis](http://purl.obolibrary.org/obo/NCBITaxon_1430) is in NCBITaxon. Everything else looks good. @zhengj2007

**Comment by johnwjudkins** [comment]
@zhengj2007 I should have noticed this earlier--I don't think we should add definitions to the EUPATH species terms. I think we should follow the previous pattern in which we add EUPATH species terms with no definitions, but we provide an editor note mentioning that the species is not in NCBITaxon. The definitions here do not fully define the species (and many are duplicates e.g. EUPATH:0043266 and EUPATH:0043267).

**Comment by zhengj2007** [comment]
The reason I added the definition because it is consistent with 'definition source' annotation. I don't think it is any hurt of keeping the information. @johnwjudkins

**Comment by johnwjudkins** [comment]
@zhengj2007 I agree that it does not hurt to keep the information. However, I think we should not make VEuPathDB definitions that are duplicate or incorrect. Could we instead use the 'editor note' annotation to mention the MIRO IDs and definitions?

**Comment by zhengj2007** [comment]
@johnwjudkins We'd better keep the use same annotation property. So, it will be easy to retrieve all the terms that can associated with the terms in other resources. I will delete the definitions.
