### ISSUE TITLE
imported OBI subset is out-of-date

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#54]
VEuPathDB imports NIAID-GSC-BRC.owl (a subset of OBI) that was generated on April 13, 2015. It is out-of-date and needs to be updated.

**Comment by zhengj2007** [comment]
Sent request to OBI and discussed on Mar 16th OBI call. The view will be generated on each OBI release. See OBI tracker https://github.com/obi-ontology/obi/issues/1127

**Comment by cstoeckert** [comment]
Remove NIAID-GSC-BRC.owl from https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/tree/master/src/ontology/import
Instead use PURL redirect so that we always get the latest version from OBI.

**Comment by zhengj2007** [comment]
We will import latest released NIAID-GSC-BRC view of OBI using the URI:
http://purl.obolibrary.org/obo/obi/NIAID-GSC-BRC.owl
And removed import the NIAID-GSC-BRC.owl in VEuPathDB repository.

Will do after fixing the issue #60

**Comment by johnwjudkins** [comment]
eupath_dev now imports this subset using the link in the previous comment.

**Comment by zhengj2007** [comment]
The issue fixed on May 5 when fixing issue #60 

https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/blob/fed6081a1383e1166999e26d4ab710ad76215028/src/ontology/eupath_dev.owl
