### ISSUE TITLE
Parents of some terms related to presence of organism data item

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#55]
Following two terms with parent 'data item'
- EUPATH_0000423 parasite species information 
- EUPATH_0011001 presence of Cryptosporidium by modified acid stain microscopy

Might be children of class:
EUPATH_0000762 presence of organism in specimen

**Comment by johnwjudkins** [comment]
Agreed. Fixed in eupath_dev.owl. Closing.
