### ISSUE TITLE
'clinical visit' in VEuPath and 'health care encounter' in OMRSE

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#56]
'clinical visit' in VEuPath and 'health care encounter' in OMRSE seem to be equivalent or nearly so.

clinical visit:
A planned process in which a patient is seen by a medical practitioner.

health care encounter:
A temporally-connected health care process that has as participants an organization or person realizing the health care provider role and a person realizing the patient role.  The health care provider role and patient are realized during the health care encounter

I suggest deprecating 'clinical visit' in favor of 'health care encounter'. The only difference I see is that "practitioner" refers to one person.

**Comment by cstoeckert** [comment]
I agree with deprecating 'clinical visit' in favor of 'health care encounter'.

**Comment by johnwjudkins** [comment]
If we make the change, it raises the question of what to do with the terms that contain "clinical visit" in their labels (and there are many). We could change those labels, but we could instead leave the labels alone and use axioms to relate the terms to 'health care encounter'.

**Comment by cstoeckert** [comment]
+1 to this proposal:
"we could instead leave the labels alone and use axioms to relate the terms to 'health care encounter'."

**Comment by johnwjudkins** [comment]
I've implemented these changes.
