### ISSUE TITLE
Axioms for next release

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#58]
Most of these identify what some information content entity in VEuPath is about. I also plan to identify relationships between two material entities in VEuPath, e.g. that a blood specimen derives from blood.

ID | label |   | parent |   | object property |   | object | note
-- | -- | -- | -- | -- | -- | -- | -- | --
EUPATH:0000586 | 'drug usage information' | SubclassOf | 'information content entity' | and | 'is about' | some | 'administering substance in vivo' |  
EUPATH:0000350 | 'number of days per week at primary job' | SubclassOf | 'time measurement datum' | and | 'is about' | some | 'economic activity' |  
EUPATH:0000351 | 'number of days per week at secondary job' | SubclassOf | 'time measurement datum' | and | 'is about' | some | 'economic activity' |  
EUPATH:0000360 | 'primary economic activity pay period' | SubclassOf | 'time measurement datum' | and | 'is about' | some | 'economic activity' |  
EUPATH:0000361 | 'secondary economic activity  pay period' | SubclassOf | 'time measurement datum' | and | 'is about' | some | 'economic activity' |  
EUPATH:0000364 | 'salary of primary economic activity' | SubclassOf | 'data item' | and | 'is about' | some | 'economic activity' |  
EUPATH:0000365 | salary of seconary economic activity' | SubclassOf | 'data item' | and | 'is about' | some | 'economic activity' |  
EUPATH:0000602 | 'environmental pets or farm animals information' | SubclassOf | information content entity' | and | 'is about' | some | animal-associated environment |  
EUPATH:0010220 | 'time of first antibiotic administration to human participant under investigation' | SubclassOf | 'time measurement datum' | and | 'is about' | some | antibiotic administration process' ~~and realizes ('target of material addition role' and 'role of' some 'human participant under investigation')~~ |  
EUPATH:0000313 | 'single catch entomological measurement datum' | SubclassOf | 'measurement datum' | and | 'is about' | some | Arthropoda and 'has role' some 'specimen role' |  
EUPATH:0000750 | time to first malaria diagnosis' | SubclassOf | 'time measurement datum' | and | 'is about' | some | diagnosis of malaria' | ~~changing label also~~
~~EUPATH:0000345~~ | ~~'educational level information'~~ | ~~SubclassOf~~ | ~~'information content entity'~~ | ~~and~~ | ~~'is about'~~ | ~~some~~ | ~~education process'~~ | not using this education process term (will watch OMRSE)
EUPATH:0000342 | employment information | EquivalentTo | 'information content entity' | and | 'is about' | some | employment process' |  
EUPATH:0000587 | environment information | EquivalentTo | 'information content entity' | and | 'is about' | some | environmental feature' or 'environmental material' or 'environmental system' |  
EUPATH:0000306 | human genotype information | EquivalentTo | 'genotype information' | and | 'is about' | some | genotype and 'is concretized as' some ('inheres in' some ('nucleic acid' and 'part of' some 'Homo sapiens')) |  
EUPATH:0000572 | 'parasite organism genotype information' | EquivalentTo | 'genotype information' | and | 'is about' | some | genotype and 'is concretized as' some ('inheres in' some ('nucleic acid' and 'part of' some 'Homo sapiens')) |  
~~FLU:0001025~~ | ~~'passage history record'~~ | ~~SubclassOf~~ | ~~'data item'~~ | ~~and~~ | ~~'is about'~~ | ~~some~~ | ~~'has role' some 'host role'~~ |  the FLU term is deprecated
EUPATH:0000413 | 'fever treatment provider information' | SubclassOf | 'information content entity' | and | 'is about' | some | has role' some ('heath care provider role' and 'realized in' some (treatment and realizes some 'patient role' and 'role of' some ('bearer of' some Fever))) |  
EFO:0004326 | heart rate' | SubclassOf | 'measurement datum' | and | 'is about' | some | heart |  
EUPATH:0000093 | dwelling information | EquivalentTo | 'information content entity' | and | 'is about' | some | human dwelling |  
EUPATH:0000375 | 'information on whether a person plans to move' | SubclassOf | 'information content entity' | and | 'is about' | some | human dwelling |  
EUPATH:0000597 | 'percent adult occupants in a dwelling' | SubclassOf | 'data item' | and | 'is about' | some | human dwelling' |  
EUPATH:0000598 | percent male occupants in a dwelling' | SubclassOf | 'data item' | and | 'is about' | some | human dwelling' |  
EUPATH:0023002 | 'time of participant first enrolled in a study' | SubclassOf | 'time measurement datum' | and | 'is about' | some | human subject enrollment' |  
EUPATH:0015458 | 'stool test for microorganisms date' | SubclassOf | 'time measurement datum' | and | 'is about' | some | laboratory test' and realizes some ('specimen role' and 'role of' some 'feces specimen') |  
EUPATH:0000578 | 'vertical distance below a surface measurement datum' | SubclassOf | 'scalar measurement datum' | and | 'is about' | some | length |  
EUPATH:0022064 | 'time of most recent bednet treatment' | SubclassOf | 'time measurement datum' | and | 'is about' | some | material processing' and 'has participant' some pesticide |  
EUPATH:0000308 | hospitalization information | SubclassOf | 'information content entity' | and | 'is about' | some | part of' some ('health care encounter' and 'occurs in' some 'hospital facility') |  
EUPATH:0000219 | 'time of screening' | SubclassOf | 'time measurement datum' | and | 'is about' | some | patient screening' and realizes some ('patient role' and 'role of' some 'Homo sapiens') |  
EUPATH:0000745 | time to onset' | SubclassOf | 'time measurement datum' | and | 'is about' | some | process boundary' and starts some 'disease course' |  
EUPATH:0000290 | 'parasitemia start time' | SubclassOf | 'time measurement datum' | and | 'is about' | some | process boundary' and starts some (realizes some ~~parasitemia~~ 'parasitic infectious disease') |  
~~EUPATH:0000435~~ | ~~'poverty line'~~ | ~~SubclassOf~~ | ~~'data item'~~ | ~~and~~ | ~~'is about'~~ | ~~some~~ | ~~processual asset'~~ |  not importing proc. asset term
~~CMO:0000289~~ | ~~'respiration rate'~~ | ~~SubclassOf~~ | ~~'data item'~~ | ~~and~~ | ~~'is about'~~ | ~~some~~ | ~~respiratory gaseous exchange by respiratory system'~~ | this axiom not in CMO
EUPATH:0000455 | 'proportion mapped reads' | SubclassOf | 'data item' | and | 'is about' | some | sequencing assay' |  
EUPATH:0000762 | 'presence of organism in specimen' | SubclassOf | 'data item' | and | 'is about' | some | specimen |  
EUPATH:0010002 | information on case matching | EquivalentTo | 'information content entity' | and | 'is about' | some | subject pairing' and realizes some (concretizes some 'case-control study design') |  
EUPATH:0010320 | 'time of rehydration' | SubclassOf | 'time measurement datum' | and | 'is about' | some | treatment |  
EUPATH:0000575 | 'virulence score (LDt50)' | SubclassOf | 'data item' | and | 'is about' | some | virulence |  
EUPATH:0000576 | 'virulence score (slope)' | SubclassOf | 'data item' | and | 'is about' | some | virulence |  
~~EUPATH:0000278~~ | ~~'parasite clearance time'~~ | ~~SubclassOf~~ | ~~'time measurement datum'~~ | ~~and~~ | ~~'is duration of'~~ | ~~some~~ | ~~biological process' and 'occurs in' some 'Homo sapiens'~~ |  
EUPATH:0000155 | duration of anorexia' | SubclassOf | 'time measurement datum' | and | 'is quality measurement of' | some | anorexia | could make template based on this if this axiom is acceptable
EUPATH:0000026 | land area measured in acres | SubclassOf | 'scalar measurement datum' | and | 'is quality measurement of' | some | area |  
EUPATH:0023005 | blood bicarbonate concentration | EquivalentTo | 'scalar measurement datum' | and | 'is quality measurement of' | some | concentration of' and 'inheres in' some (hydrogencarbonate and 'part of' some 'blood specimen') | could make template based on this
~~OBI:0001620~~ | ~~'latitude coordinate measurement datum'~~ | ~~SubclassOf~~ | ~~'measurement datum'~~ | ~~and~~ | ~~'is quality measurement of'~~ | ~~some~~ | ~~inheres in' some 'geographic location'~~ | axiom not in OBI
~~OBI:0001621~~ | ~~'longitude coordinate measurement datum'~~ | ~~SubclassOf~~ | ~~'measurement datum'~~ | ~~and~~ | ~~'is quality measurement of'~~ | ~~some~~ | ~~inheres in' some 'geographic location'~~ |  axiom not in OBI
EUPATH:0010084 | first mid-upper arm circumference datum | SubclassOf | length measurement datum' | and | 'is quality measurement of' | some | length and 'inheres in' some arm |  
EUPATH:0000318 | hospital admission information | SubclassOf | 'information content entity' | and | denotes | some | hospital facility' and 'contains process' some ('health care encounter' and realizes some ('patient role' and 'role of' some ('participant under investigation'))) |  
EUPATH:0010405 | information on sex of matched case | EquivalentTo | information on case matching | and | denotes | some | sex and 'inheres in' some ('has role' some 'case role in case-control study') |  
IAO:0000401 | 'one dimensional cartesian spatial coordinate datum' | SubclassOf | 'data item' | and | denotes | some | zero-dimensional spatial region' and ('part of' some 'one-dimensional spatial region') | This axiom is already in IAO.
OBI:0000655 | 'blood specimen' | EquivalentTo | specimen | and | derives from' | some | blood | could make template based on this
EUPATH:0000026 | land area measured in acres | SubclassOf | 'scalar measurement datum' | and | has measurement unit label' | only | acre |  
EUPATH:0000754 | 'information on blood smear result' | SubclassOf | information content entity' | and | is about' | some | blood specimen' |  
EUPATH:0000147 | 'cause of participant death' | SubclassOf | information content entity' | and | is about' | some | causally upstream of or within' some 'death stage'
EUPATH:0000513 | 'information on availability of molecular data' | SubclassOf | information content entity' | and | is about' | some | ~~derives into' some~~ specimen |  
EUPATH:0000316 | 'malaria severity and basis information' | SubclassOf | information content entity' | and | is about' | some | diagnosis of malaria' |  
EUPATH:0000338 | 'malaria diagnosis and parasite status information' | SubclassOf | information content entity' | and | is about' | some | diagnosis of malaria' and is_specified_output_of some ('diagnostic process' and 'has part' some 'organism identification assay') |  
EUPATH:0000190 | 'medical care outside the study clinic since last seen information' | SubclassOf | information content entity' | and | is about' | some | health care encounter' |  
EUPATH:0000451 | healthcare information' | SubclassOf | information content entity' | and | is about' | some | health care process' |  
EUPATH:0000304 | 'socioeconomic factor' | SubclassOf | information content entity' | and | is about' | some | household |  
EUPATH:0000418 | 'indoor residents information' | SubclassOf | information content entity' | and | is about' | some | human dwelling' |  
EUPATH:0000410 | 'information on whether took antimalarial drugs in last 2 weeks' | SubclassOf | information content entity' | and | is about' | some | human participant under investigation' |  
EUPATH:0000515 | 'information on informed consent for data collection and usage' | SubclassOf | information content entity' | and | is about' | some | human participant under investigation' |  
EUPATH:0000553 | 'information on informed consent for future use of specimen' | SubclassOf | information content entity' | and | is about' | some | human participant under investigation' |  
EUPATH:0010153 | 'indicator of whether receiving medication' | SubclassOf | information content entity' | and | is about' | some | human participant under investigation' |  
EUPATH:0021026 | 'no treatment for fever' | SubclassOf | information content entity' | and | is about' | some | human participant under investigation' and 'bearer of' some (febrile and not ('participates in' some treatment)) |  
EUPATH:0022058 | 'reason besides fever for specimen collection' | SubclassOf | information content entity' | and | is about' | some | human participant under investigation' and 'has part' some ('derives into' some specimen) |  
EUPATH:0000374 | 'marital status' | SubclassOf | information content entity' | and | is about' | some | human social role' |  
EUPATH:0023056 | 'information on whether participant is member of tribe' | SubclassOf | information content entity' | and | is about' | some | human social role' |  
EUPATH:0010418 | 'indicator of participant eligibility for enrollment' | SubclassOf | information content entity' | and | is about' | some | human subject enrollment' |  
~~EUPATH:0000386~~ | ~~'information on place visited during a trip'~~ | ~~SubclassOf~~ | ~~information content entity'~~ | ~~and~~ | ~~is about'~~ | ~~some~~ | ~~human travel'~~ |  not using 'human travel'
~~EUPATH:0000388~~ | ~~'information on travel before malaria'~~ | ~~SubclassOf~~ | ~~information content entity'~~ | ~~and~~ | ~~is about'~~ | ~~some~~ | ~~human travel' and 'has participant' some 'human participant under investigation'~~
~~EUPATH:0000392~~ | ~~'information on contact with malaria'~~ | ~~SubclassOf~~ | ~~information content entity'~~ | ~~and~~ | ~~is about'~~ | ~~some~~ | ~~human travel' and 'has participant' some 'human participant under investigation'~~ | not using 'human travel'
EUPATH:0000612 | 'information specifying human or animal' | SubclassOf | information content entity' | and | is about' | some | ~~Metazoa~~ Opisthokonta |  
EUPATH:0000324 | 'mosquito parity information' | SubclassOf | information content entity' | and | is about' | some | ~~parity~~ parous and 'inheres in' some Culicoidea |  
EUPATH:0010038 | 'fecal specimen data item' | SubclassOf | data item' | and | is about' | some | quality and 'inheres in' some 'feces specimen' |  
EUPATH:0000440 | residence status information' | SubclassOf | information content entity' | and | is about' | some | socio-legal human social role' |  
EUPATH:0000611 | 'specimen source information' | SubclassOf | information content entity' | and | is about' | some | specimen collection process' |  
EUPATH:0000748 | iPCR datum | EquivalentTo | 'measurement datum' | and | is_specified_output_of | some | assay and 'has part' some 'inverse polymerase chain reaction' |  
EUPATH:0021027 | 'no Plasmodium by microscopy' | SubclassOf | 'data item' | and | is_specified_output_of | some | microscopy assay' and realizes some ('evaluant role' and 'role of' some 'blood specimen') |  
EUPATH:0000325 | 'sporozoite testing information' | SubclassOf | presence of organism in specimen' | and | is_specified_output_of | some | organism identification assay' and realizes some ('specimen role' and 'role of' some Arthropoda) |  
EUPATH:0021032 | 'Plasmodium falciparum diagnosis within past year' | SubclassOf | diagnosis | and | mentions | some | 'Plasmodium falciparum' |  
EUPATH:0021034 | 'information on Plasmodium malariae diagnosis within past year' | SubclassOf | diagnosis | and | mentions | some | 'Plasmodium malariae' | (I should remove "information on" in the label for consistency
~~EUPATH:0000600~~ |~~'information on class of antibiotics given to mom'~~ | ~~SubclassOf~~ | ~~information content entity'~~ | ~~and~~ | ~~mentions~~ | ~~some~~ | ~~active ingredient in' some antibiotics~~ |  RO needs to fix typo in 'active...'; will add to future release
EUPATH:0010040 | 'information specifying antibiotic administered before stool collection' | SubclassOf | information content entity' | and | mentions | some | antibiotics | may add more complex axiom in future
EUPATH:0000411 | 'information on existing illness' | SubclassOf | information content entity' | and | mentions | some | disease and 'inheres in' some 'human participant under investigation' |  
EUPATH:0000431 | 'information on who treated malaria last year' | SubclassOf | information content entity' | and | mentions | some | has role' some ('health care provider role' and realized in some treatment) | may add more complex axiom in future
EUPATH:0000436 | no illness information' | SubclassOf | information content entity' | and | mentions | some | Homo sapiens' and not ('bearer of' some disease) |  
~~EUPATH:0010379~~ | ~~'information on raising money for health care encounter'~~ | ~~SubclassOf~~ | ~~information content entity'~~ | ~~and~~ | ~~mentions~~ | ~~some~~ | ~~planned process' and has_specified_output some asset~~ | not using this asset term
EUPATH:0021033 | 'Plasmodium vivax diagnosis within past year' | SubclassOf | diagnosis | and | mentions | some | Plasmodium vivax' |  
EUPATH:0010378 | 'information on diarrhea treatment before clinical visit' | SubclassOf | information content entity' | and | mentions | some | treatment and (realizes some('participant under investigation role' and ('role of' some ('human participant under investigation' and ('bearer of' some diarrhea))))) and (precedes some 'health care encounter') |  
EUPATH:0000599 | 'information on whether antibiotics given to mom' | SubclassOf | ~~data item'~~ | and | part of' | some | clinical history' | could make template based on this

**Comment by cstoeckert** [comment]
For EUPATH:0010220, do we need more than is about antibiotic administration process?
EUPATH:0000572: cut/paste error? not about human
FLU:0001025: axiom doesn't seem correct. Also where is this from?

**Comment by johnwjudkins** [comment]
I agree with the first two points.
Still working on the issue with FLU:0001025. The FLU ontology is deprecated in the OBO Foundry. The ID was assigned to a genomics variable. If I don't find another term for it, I'll submit a NTR to OBI.

**Comment by cstoeckert** [comment]
EUPATH:0000278 parasite clearance time - not defined specifically for humans so logical definition should not have that restriction. Also duration of some biological process seems too general to be useful. 
EUPATH:0000155 duration of anorexia. Seems like a reasonable pattern to me. 
OBI:0000655 blood specimen - the axiom 'derives from some blood' is already in OBI but did not get imported into VEuPath.
EUPATH:0000513 information on availability of molecular data - doesn't match axiom of derives into specimen.
EUPATH:0010038 fecal specimen data item - not sure that data are only about qualities. What about counts? when collected? etc. 
EUPATH:0021031 microscopy assay performed - would be more useful to tie to microscopy assay than to specimen
EUPATH:0000325 sporozoite testing information - could apply to blood specimen not arthropod specimen. More useful to tie to organism detected (sporozoite stage of some parasite) than the specimen.
EUPATH:0000436 no illness information - label is ambiguous. Could mean 'no information on illness' or 'information that there is no illness'
General question about whether we want to have terms with identical logical definitions (we would not do this for textual definitions).

**Comment by johnwjudkins** [comment]
I'll suggest these changes to axioms:
EUPATH:0000278 'time measurement datum' and 'is duration of' some (**'defense response to other organism'** and **'has primary input'** some 'parasite organism') (terms in bold are from GO and RO, respectively, and would need to be imported. This could be easier if GO had roles defined along with its biol. processes.)
EUPATH:0000513 'information content entity' and 'is about' some specimen (I think I misunderstood the meaning of "specimen source".)
EUPATH:0000325 'presence of organism in specimen' and is_specified_output_of some 'organism identification assay' and realizes some ('evaluant role' and 'inheres in' some ('participates in' some 'sporozoite stage')))

As for the others:
EUPATH:0000436 The label 'information that there is no illness' fits best.
EUPATH:0010038 I wrote the axiom this way because I understand the 5 children of this term in ClinEpi to be qualities. It is the siblings (not children) of EUPATH:0010038 that are about the count of stool or when it is collected etc. I think the superclass 'Stool sample' EUPATH:0011877 is about the specimen itself, and EUPATH:0010038 is about some quality of the specimen.

In response to your general question:
I think it's fine for multiple classes to have the same subclass axiom, because multiple classes can have the same subclass. But I think it's good to try to find classes (or create them) that represent the differentia between those classes, in order for the subclass axioms to be different.

**Comment by cstoeckert** [comment]
Thank you for the explanation of EUPATH:0010038 'fecal specimen data item'. The definition makes sense but the label should reflect the focus on qualities. Perhaps 'fecal specimen quality data item'?

**Comment by johnwjudkins** [comment]
I'll make the label change.

I hadn't addressed your comment on EUPATH:0021031 'microscopy assay performed'. This ICE indicates _whether_ the microscopy assay was done, and the object of 'is about' has to exist. So I think the ICE is about the _history_ (BFO_0000182) of the specimen, which may include a microscopy assay or other assays.

**Comment by cstoeckert** [comment]
Leave out axiom for EUPATH:0021031 'microscopy assay performed' for now until a clearer use case is developed.

**Comment by cstoeckert** [comment]
Captured in June 2020 release.
