### ISSUE TITLE
'human traveling Information' in both VEuPath and OMRSE

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#59]
The definition is the same except OMRSE uses "travel" instead of "traveling". It seems to be closer to OMRSE's domain than VEuPath's.

**Comment by cstoeckert** [comment]
We should use the one from OMRSE (http://purl.obolibrary.org/obo/OMRSE_00000142). We may have requested it!

**Comment by johnwjudkins** [comment]
The OMRSE term is imported and the EUPATH term is obsoleted. These changes are in eupath_dev and will go into the upcoming release candidate.
