### ISSUE TITLE
'geographic location' imported as both individual and class

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#63]
http://purl.obolibrary.org/obo/GAZ_00000448 geographic location
imported as both individual and class

**Comment by johnwjudkins** [comment]
https://github.com/EnvironmentOntology/gaz/issues/34

**Comment by johnwjudkins** [comment]
I added import_GAZ.owl, which contains only GAZ_00000448 and associates it only as a class (not as an individual). eupath_dev.owl will draw from import_GAZ.owl, but (until they fix this issue) GAZ_00000448 will not be in any of the input .txt files we use for importing.
