### ISSUE TITLE
'follow-up visit' deprecated in ICO

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#64]
ICO:0000094 is deprecated. Looking at their annotations, it seems they decided it was outside their domain. This ID isn't in any of our projects. Should we submit a NTR for this term? To OGMS? Or just remove it?

**Comment by cstoeckert** [comment]
If not being used, I would remove it.

**Comment by johnwjudkins** [comment]
The ICO term was removed. Closing.
