### ISSUE TITLE
'Muscle aches' equivalent to Myalgia in HP

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#66]
'Muscle aches' EUPATH:0000252 is in VEuPath and is under Symptoms in the PRISM and PRISM2 projects. Myalgia HP:0003326 is an equivalent class and should replace the EUPATH class.

**Comment by cstoeckert** [comment]
I agree.

**Comment by johnwjudkins** [comment]
Changes have been pushed: The EUPATH term is deprecated, and the HP term is in the import files. (The IRI is also replaced in PRISM 1 & 2.) Closing.
