### ISSUE TITLE
2 shock terms in ontology

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#67]
I suggest removing the SNOMEDCT term 'shock' from externalByHand.owl. (The ontology also has the HP term 'Shock' that has the same meaning.)

However, the SNOMEDCT term is in use in protein_array.owl.

**Comment by cstoeckert** [comment]
I agree with removing and replacing with HP term in protein_array.owl.

**Comment by johnwjudkins** [comment]
The changes have been pushed. 'Shock' was removed from externalByHand.owl. The HP term will be imported in future releases, and replaces the SNOMEDCT term in protein_array.owl. Closing.
