### ISSUE TITLE
2 'pain' terms in ontology

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#68]
VEuPath has 2 'pain' terms: HP:0012531 and SYMP:0000099. Both are defined, and the two definitions seem similar. Only the SYMP term is used in ClinEpi (as 'Aches or pains'); based on that, it would seem better to remove the HP term. However, HP appears to be in more active development.

**Comment by cstoeckert** [comment]
Let's go with the HP term.

**Comment by johnwjudkins** [comment]
The SYMP term has been replaced with the HP term, both in eupath-dev and in ClinEpi projects. Closing.
