### ISSUE TITLE
2 'respiratory stress' terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#69]
We have both HP:0002098 SYMP:0000642 in the ontology. HP:0002098 is defined and used in ClinEpi projects. SYMP:0000642 has no definition and is not used in ClinEpi projects. I suggest removing the SYMP term.

**Comment by cstoeckert** [comment]
Can you check if it is used in other VEuPathDB associated projects (Microbiome, EuPathDB)? If not used elsewhere too, then I agree with removing. Thanks.

**Comment by johnwjudkins** [comment]
Not in any VEuPath associated projects. I'll remove it.

**Comment by johnwjudkins** [comment]
Changes have been pushed. Closing.
