### ISSUE TITLE
Bacteremia and Viremia in HP could replace equiv. EUPATH terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#70]
Bacteremia HP:0031864 could replace 'presence of bacteria in the blood' EUPATH:0000037.
Viremia HP:0020071 could replace 'presence of virus in the blood' EUPATH:0000039.

The only difference is HP's Bacteremia definition mentions that the bacteria are viable, but I don't think that matters.

Neither of these EUPATH IDs are used in ClinEpiDB or other projects, so we could just deprecate them without replacing them, but they might be useful for axiom development.

Note that these EUPATH terms are for phenotypic abnormalities unlike the "presence of (organism)..." terms for data items.

**Comment by cstoeckert** [comment]
I'm OK with deprecating them at least if not used. Also OK with replacing with HP terms too.

**Comment by johnwjudkins** [comment]
These terms are deprecated with a note explaining we will import the HP terms to replace these, if needed.
