### ISSUE TITLE
NTR: parasite group

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#71]
VEuPathDB Genomics need a new term for 'isolate group'. I have assigned the term ID, EUPATH_0005034.

The isolate group is identified based on phylogenetic and clustering analyzing SNP results. Details see reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4811772/ (Figure 2 and associated data)

**Comment by cstoeckert** [comment]
Have looked into how to define 'parasite group' with ID: EUPATH_0005034. From the associated publication, the isolate groups (ISC1, ISC2, .. ISC10) are clades based on genotyping of clinical samples from the Indian SubContinent (ISC).

**Comment by johnwjudkins** [comment]
Label: parasite isolate population
Definition: A population of parasites that derives from a population collected from the same site at the same time and kept isolated from other populations.
additional source: J. Med. Microbiol. Vol. 49 􏰁(2000), 397-401 https://doi.org/10.1099/0022-1317-49-5-397 (about bacteria but still useful)

There seems to be disagreement on whether "isolate" and "strain" are synonymous. I am tempted to define this term as a population of parasites of the same strain, especially since we already have the term 'parasite strain'.

**Comment by cstoeckert** [comment]
I don't think the part of the proposed definition that says "collected from the same site at the same time and kept isolated from other populations" fits the motivating use case. The isolate groups were identified genotypically as belonging to the same group even though they were collected from different sites and these are native so not kept isolated.
Maybe something like: A population of parasites that is defined by shared features such as genetic markers reflecting a common origin and distinguishing the population from other related parasite populations.

**Comment by cstoeckert** [comment]
We think this term should be submitted to PCO. Here is the proposed submission:

## Preferred term label

parasite isolate population

## Synonyms

## Textual definition

A microbial population of parasites that is defined by shared features such as genetic markers reflecting a common origin and distinguishing the population from other related parasite populations.

## Suggested parent term

https://purl.obolibrary.org/obo/PCO_0000046 microbial population

## Attribution

VEuPathDB

## Example of usage

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4811772/ (Figure 2 and associated data)

**Comment by johnwjudkins** [comment]
https://github.com/PopulationAndCommunityOntology/pco/issues/90

**Comment by ramonawalls** [comment]
The term has been added to PCO and will be released in a few days.

**Comment by johnwjudkins** [comment]
http://purl.obolibrary.org/obo/PCO_0000061
