### ISSUE TITLE
Deprecate term EUPATH_0000064 clinical characteristics

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#72]
We added EUPATH_0000064 'clinical characteristics' for grouping phenotype and disease long time ago. Current the term is not used by any VEuPathDB projects. It is not aligned well with BFO and causes confusion. I proposed to deprecate the term.

**Comment by zhengj2007** [comment]
Besides, we need to revisit term: EUPATH_0000046 'severe malaria symptom or sign'.

It is the only term asserted under EUPATH_0000064 'clinical characteristics'. The term EUPATH_0000046 is a kind of diagnosis and used in the ClinEpi Project. We need to make corresponding updates in the ontology.

**Comment by johnwjudkins** [comment]
I agree, and since EUPATH_0000046 is about signs & symptoms, I think we can categorize it as information.

**Comment by cstoeckert** [comment]
Agree to deprecate clinical characteristics and move children to follow standard OBO Foundry hierarchy. 
Also make EUPATH_0000046 'severe malaria symptom or sign' an information content entity under http://purl.obolibrary.org/obo/EUPATH_0000309 'symptom or sign information'
