### ISSUE TITLE
NTR: insecticide resistance and LD related values

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#77]
These are requested for PopBio data:
insecticide concentration in percent
insecticide concentration in parts per million or billion
insecticide concentration in mass per volume
insecticide concentration in mass per standard assay bottle
- units can't be interconverted. should also create a parent term for insecticide concentration.

Likewise need for dose response assays:
LD50 in percent
LD50 in parts per million or billion
LD50 in mass per volume
LD50 in mass per standard assay bottle

LD90 in percent
LD95 in parts per million or billion
LD95 in mass per volume
LD95 in mass per standard assay bottle

May need these in future 
LD90 in percent
LD90 in parts per million or billion
LD90 in mass per volume
LD90 in mass per standard assay bottle

LD99 in percent
LD99 in parts per million or billion
LD99 in mass per volume
LD99 in mass per standard assay bottle

**Comment by johnwjudkins** [comment]
I wonder if we should use 'pesticide' instead of 'insecticide' to include all arthropods (not only insects). However, 'insecticide resistance assay' and its children are already in VEuPath.

Label | Definition | Equivalent axiom
-- | -- | --
insecticide concentration | A scalar measurement datum of the concentration of an insecticide. | 'scalar measurement datum' and 'is quality measurement of' some ('concentration of' and 'inheres in' some ('has role' some insecticide))
insecticide concentration in percent | An insecticide concentration measured as a percent. | 'insecticide concentration' and 'has measurement unit label' only percent
insecticide concentration in parts per million or billion | An insecticide concentration measured as either parts per million or parts per billion. | 'insecticide concentration' and 'has measurement unit label' only ('parts per million' or 'parts per billion')
insecticide concentration in density unit | An insecticide concentration that has a density unit. | 'insecticide concentration' and 'has measurement unit label' only 'density unit'
insecticide concentration in mass per standard assay bottle | An insecticide concentration that has a unit of mass unit per standard assay bottle, which is 250 ml. |  
virulence score (LDt50) in percent | A virulence score (LDt50) measured as a percent. | 'virulence score (LDt50)' and 'has measurement unit label' only percent
virulence score (LDt50) in parts per million or billion | A virulence score (LDt50) measured as either parts per million or parts per billion. | 'virulence score (LDt50)' and 'has measurement unit label' only ('parts per million' or 'parts per billion')
virulence score (LDt50) in density unit | A virulence score (LDt50) that has a density unit. | 'virulence score (LDt50)' and 'has measurement unit label' only 'density unit'
virulence score (LDt50) in mass per standard assay bottle | A virulence score (LDt50) that has a unit of mass unit per standard assay bottle, which is 250 ml. |

**Comment by johnwjudkins** [comment]
virulence score (LDt90)

A data item that is about some virulence and is the count of infectious agents that kill 90% of a collection of human beings infected with the agents

subclass axiom: 'is about' some virulence

**Comment by bobular** [comment]
Thanks John - this looks like a great start.

- Insecticide vs pesticide - no strong opinion, as long as our chosen display names can be used in our resources
- Did you ask Sarah about the standard assay bottle size?
- Does the word 'virulence' imply viruses to anyone else, or is it just me?
- Also does 'score' imply that a higher number means more virulence?  In this case it doesn't.  A higher concentration means the insecticide is less effective at killing.
- I see from a quick Google that LD50 (lethal dose) is more generic than LC50 (lethal concentration) - because the dose can measure things like radiation - we can go with this, but what is the 't' in LDt50?

**Comment by bobular** [comment]
Great - when we're done with concentrations and LDt50 - just a reminder that LT50 and KDT50 (and KDT90 etc) are also needed.

**Comment by johnwjudkins** [comment]
It turns out "virulence" is not appropriate here after all since it refers to an _infectious_ agent.

So here's what I now propose for LD50 in percent:
Label: lethal insecticide concentration 50
Definition: The concentration of an insecticide that is expressed as a percentage and kills 50% of a population of insects.

**Comment by johnwjudkins** [comment]
LT50
Label: lethal insecticide time 50
Definition: A time measurement datum that is about the duration of exposure to an insecticide that results in the death of 50% of a population of insects.

By the way, we can make these more generic if preferred, in other words without reference to insecticide or pesticide.

**Comment by cstoeckert** [comment]
Sarah and Sam agree with proposed definition.

**Comment by johnwjudkins** [comment]
Here are updated labels and definitions for the original list. All terms besides the first term in the list are subclasses of the first term.

Label | Definition | Equivalent axiom
-- | -- | --
insecticide concentration datum | A scalar measurement datum of the concentration of an insecticide. | 'scalar measurement datum' and 'is quality measurement of' some ('concentration of' and 'inheres in' some ('has role' some insecticide))
insecticide concentration in percent | An insecticide concentration measured as a percent. | 'insecticide concentration datum' and 'has measurement unit label' only percent
insecticide concentration in parts per million or billion | An insecticide concentration measured as either parts per million or parts per billion. | 'insecticide concentration datum' and 'has measurement unit label' only ('parts per million' or 'parts per billion')
insecticide concentration in density unit | An insecticide concentration that has a density unit. | 'insecticide concentration datum' and 'has measurement unit label' only 'density unit'
insecticide concentration in mass per standard assay bottle | An insecticide concentration that has a unit of mass unit per standard assay bottle, which is 250 ml. |  
lethal insecticide concentration 50 | A data item that is about the concentration of an insecticide that kills 50% of a population of insects. |  
lethal insecticide concentration 50 in percent | A lethal insecticide concentration 50, expressed as a percent. | 'lethal insecticide concentration 50' and 'has measurement unit label' only percent
lethal insecticide concentration 50 in parts per million or billion | A lethal insecticide concentration 50, expressed as either parts per million or parts per billion. | 'lethal insecticide concentration 50' and 'has measurement unit label' only ('parts per million' or 'parts per billion')
lethal insecticide concentration 50 in density unit | A lethal insecticide concentration 50 that has a density unit. | 'lethal insecticide concentration 50' and 'has measurement unit label' only 'density unit'
lethal insecticide concentration 50 in mass per standard assay bottle | A lethal insecticide concentration 50 that has a unit of mass unit per standard assay bottle, which is 250 ml. |  
lethal insecticide concentration 95 | A data item that is about the concentration of an insecticide that kills 95% of a population of insects. |  
lethal insecticide concentration 95 in percent | A lethal insecticide concentration 95, expressed as a percent. | 'lethal insecticide concentration 95' and 'has measurement unit label' only percent
lethal insecticide concentration 95 in parts per million or billion | A lethal insecticide concentration 95, expressed as either parts per million or parts per billion. | 'lethal insecticide concentration 95' and 'has measurement unit label' only ('parts per million' or 'parts per billion')
lethal insecticide concentration 95 in density unit | A lethal insecticide concentration 95 that has a density unit. | 'lethal insecticide concentration 95' and 'has measurement unit label' only 'density unit'
lethal insecticide concentration 95 in mass per standard assay bottle | A lethal insecticide concentration 95 that has a unit of mass unit per standard assay bottle, which is 295 ml. |

**Comment by cstoeckert** [comment]
Need to add alternative labels for LC50 like terms.

**Comment by bobular** [comment]
Hi John,
Everything from "lethal insecticide concentration 50" and below should be a child of a new parent "insecticide resistance datum" 
thank you!

**Comment by bobular** [comment]
Hi John,
These are all the combinations of measurement-type and unit in the current live VB release.
I'm making another sheet in the master spreadsheet to create the look-up I'll need to map the old data to the new terms.  I'll comment on Slack when I'm done.  thanks!

```
fraction greater than 99th percentile reference activity:percent
KDT50:minute
LC100:percent
LC50:gram per meter squared
LC50:microgram
LC50:microgram per liter
LC50:microgram per milliliter
LC50:milligram per liter
LC50:milligram per square meter
LC50:parts per billion
LC50:parts per million
LC50:percent
LC90:milligram per liter
LC90:parts per million
LC95:gram per meter squared
LC95:microgram
LC95:microgram per liter
LC95:milligram per liter
LC95:milligram per square meter
LC95:parts per billion
LC95:parts per million
LC99:microgram
LC99:milligram per liter
LC99:parts per million
log2(mean sample activity / mean reference strain activity):ratio
log2(median sample activity / median reference strain activity):ratio
LT50:minute
LT90:minute
LT95:minute
mortality rate:percent
```

**Comment by bobular** [comment]
Does "density unit" mean mass per volume?

We also have mass per area, see above.   Do we need two flavours of terms:  "volume density unit" and "area density unit" ?

Please also ask me or Sarah about the enzymatic activity measures if you need any help.

**Comment by johnwjudkins** [comment]
The Unit Ontology has 'density unit', based on influence exerted by some mass. Children of that term include 'area density unit' (influence on an area) and 'mass density unit' (influence over a volume). That last one should be labeled "volume density unit" but isn't. I will import those terms that aren't in VEuPath.

**Comment by johnwjudkins** [comment]
@zhengj2007 I'm thinking of defining 'insecticide concentration' using this axiom:

'scalar measurement datum' and 'is quality measurement of' some ('concentration of' and 'inheres in' some ('has role' some insecticide and 'part of' some water))

This is the same axiom I posted here, except I added the reference to water. This follows ENVO's use of 'concentration of' to define terms axiomatically.

Should I add this axiom? I think we discussed not using 'concentration of' in axioms, so I wonder if I should come up with an alternative.

**Comment by zhengj2007** [comment]
It looks good to me. Since the domain of 'has role' is 'independent continuant', shall we make it clear as?
'concentration of' and 
  ('inheres in' some (('material entity' and ('has role' some insecticide))
      and ('part of' some 'liquid water')))

**Comment by cstoeckert** [comment]
May not always be 'liquid water' - want to replace with solvent.

**Comment by bobular** [comment]
These terms from https://docs.google.com/spreadsheets/d/1vlj-4NTpKJNjj-eU-JgJr6d2OHXiGwiK14InUeNmA7c/edit#gid=1074853426
will also need terms please
VBcv:0001116 log2(mean sample activity / mean reference strain activity) UO:0000190 ratio
VBcv:0001124 log2(median sample activity / median reference strain activity) UO:0000190 ratio
VBcv:0001111 fraction greater than 99th percentile reference activity UO:0000187 percent

**Comment by SAK22** [comment]
1. A ratio of the mean enzymatic activity of a field-collected sample compared to that of a reference strain (usually a laboratory colony) expressed as a log base two transformed ratio
2. A ratio of the median enzymatic activity of a field-collected sample compared to that of a reference strain (usually a laboratory colony) expressed as a log base two transformed ratio
3. The fraction of individuals exhibiting higher activity than the 99th percentile of the control insects.

**Comment by cstoeckert** [comment]
Make these individuals of the ratio class.

**Comment by johnwjudkins** [comment]
EUPATH:0043140
Label:
unit of log2 ratio of specimen population mean enzymatic activity to that of reference specimen population
Definition:
A ratio unit that denotes the mean enzymatic activity of a field-collected population of specimens compared to that of a reference population, normalized by a base two logarithmic transformation.

EUPATH:0043141
Label:
unit of log2 ratio of specimen population median enzymatic activity to that of reference specimen population
DefinitIon:
A ratio unit that denotes the median enzymatic activity of a field-collected population of specimens compared to that of a reference population, normalized by a base two logarithmic transformation.

EUPATH:0043142
Label:
unit of population fraction with greater enzymatic activity than 99th percentile of reference population
Definition:
A fraction unit that denotes the fraction of a population exhibiting higher enzymatic activity than the 99th percentile of a reference population.

**Comment by johnwjudkins** [comment]
These are all in eupath_dev now, except I'm still working on some KDT and LT terms.
For 'mortality rate' I suggest http://purl.obolibrary.org/obo/APOLLO_SV_00000445 because it is defined as a measurement datum. (Other ontologies have 'mortality rate' as a quality.)

**Comment by zhengj2007** [comment]
APOLLO_SV_00000445 looks good to me. May consider to contact APOLLO_SV to relabel the term like 'mortality rate measurement datum' to make it clarified.

**Comment by SAK22** [comment]
Just checking John are these the ontologies you want Bob and I to check from the meeting notes?

**Comment by johnwjudkins** [comment]
@SAK22 Yes, please review the terms here: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/blob/master/src/ontology/axiom_template/insecticide_resistance.csv and the 3 terms I put in a comment here 3 days ago.

**Comment by SAK22** [comment]
Ok so the ones from three days ago look good @johnwjudkins, @bobular can you confirm you agree?
The ones in the link also look good, could you explain to me the ones that say A data item that....for things like lethal insecticide concentration 50. I think it is just me not understanding ontology wording! @bobular can you confirm you are happy with these?

**Comment by johnwjudkins** [comment]
We  use the phrase "a data item that..." for these concentration data terms because we need to distinguish between data about the concentration and the concentration itself. Only data about the concentration can have units (percent, g/m^2, etc.).

**Comment by bobular** [comment]
Updated mapping spreadsheet here: https://docs.google.com/spreadsheets/d/1vlj-4NTpKJNjj-eU-JgJr6d2OHXiGwiK14InUeNmA7c/edit#gid=1074853426 for discussion on call

**Comment by johnwjudkins** [comment]
Label: median knockdown time 
Definition: A time measurement datum specifying the time at which half of a population of insects has died as a result of exposure to insecticide.
Source: PMC2459197 
Alternative term: **KDT50**

If the above is OK, I'll add it to the template along with:
90 percent knockdown time
95 percent knockdown time

**Comment by bobular** [comment]
That's correct John, there's no KDT95 (for example) in our data, and unlikely to come.

The term + definition look good to me.  Thanks

**Comment by johnwjudkins** [comment]
For the remaining ratio data terms (for which we already have units):

EUPATH:0043152
label: ratio of specimen population mean enzymatic activity to that of reference specimen population

definition: A data item that denotes the proportionality of the mean enzymatic activity of a field-collected population of specimens compared to that of a reference population.

EUPATH:0043153
label: ratio of specimen population median enzymatic activity to that of reference specimen population

definition: A data item that denotes the proportionality of the median enzymatic activity of a field-collected population of specimens compared to that of a reference population.

EUPATH:0043154
label: population fraction with greater enzymatic activity than 99th percentile of reference population

definition: A data item that specifies the fraction of a population exhibiting higher enzymatic activity than the 99th percentile of a reference population.

Subclass axiom for all 3 terms:
'is about' some ('catalytic activity' and realizes some ('function of' only enzyme))

**Comment by cstoeckert** [comment]
Should change 'denotes' to 'specifies' for first two terms.

**Comment by johnwjudkins** [comment]
In release; closing.
