### ISSUE TITLE
Axioms for next release

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#83]
ID | label |   |   | notes
-- | -- | -- | -- | --
EUPATH:0000026 | 'land area measured in acres' | subclass | ('is quality measurement of' some area) and ('has measurement unit label' only acre) |  
EUPATH:0000317 | 'diagnosis of disease other than malaria' | subclass | mentions some (disease and not malaria) |  on reflection, changed to subclass (axiom does not exactly define the term)
EUPATH:0000321 | 'diagnosis at discharge' | subclass | diagnosis and is_specified_input_of some 'patient discharge' | I have a template for this.
EUPATH:0000325 | 'sporozoite testing information' | subclass | is_specified_output_of some (assay and realizes some ('evaluant role' and 'role of' some ('collection of specimens' and 'has member' only Arthropoda)) and realizes some ('measurand role' and 'role of' some ('participates in' only 'sporozoite stage'))) |  Will create 'sporozoite detection assay'.  Need UBERON's explanation of how they categorize life stages - for now, changing **some** 'sporozoite stage' to **only**.
EUPATH:0000327 | 'entomological data item' | subclass | is about' some ('object aggregate' and 'has member' some Arthropoda) |  
EUPATH:0000377 | 'years of living in the dwelling' | subclass | is duration of' only (realizes some 'residence function') |
EUPATH:0000377 | 'years of living in the dwelling' | subclass | 'has measurement unit label' only year |  (edited per Jie's comment) 
EUPATH:0000528 | 'gametocyte detection assay' | subclass | assay and realizes some (‘measurand role' and 'role of' some ‘parasite organism’ and (‘participates in' some 'gametocyte stage'))| (edited per Jie's comment)  
EUPATH:0000529 | 'gametocyte detection protocol' | subclass | protocol and 'is concretized as' some ('realized in' some ('gametocyte detection assay' ~~and 'has specified output' some ('scalar measurement datum' and 'is quality measurement of' some 'volumetric density')~~)) |  
EUPATH:0000581 | 'mode of baby delivery' | subclass | has part' some parturition | should also be moved from biological_process to 'health care encounter'
EUPATH:0000600 | 'information on class of antibiotics given to mom' | subclass | information content entity' and mentions some ('active ingredient in' some antibiotics) |  
EUPATH:0000603 | 'sequencing protocol' | equivalent | protocol and 'is concretized as' some ('realized in' some 'sequencing assay') |  
EUPATH:0000610 | 'skin symptom or sign information' | subclass | is about' some 'zone of skin' |  
EUPATH:0000614 | 'ear thickness' | equivalent | scalar measurement datum' and 'is quality measurement of' some (thickness and 'inheres in' some pinna) |  not including yet - I've requested PATO revise 'thickness' definition
EUPATH:0000615 | 'transepidermal water loss' | subclass | is about' some 'regulation of water loss via skin' |  
EUPATH:0000618 | 'skin pathology score' | subclass | is about' some 'Abnormality of the skin' | not a measurement in ClinEpi
EUPATH:0000620 | 'degree of skin thickening' | subclass | is about' some 'Thickened skin' |  
EUPATH:0000621 | 'lesion size' | subclass | is quality measurement of' some (area and 'inheres in' some ('zone of skin' and 'bearer of' some lesioned)) |  
EUPATH:0000625 | 'groin lesion score before treatment' | subclass | is quality measurement of' some (lesioned and 'inheres in' some 'inguinal part of abdomen') |  (edited 'groin' -> 'inguinal part ...')
EUPATH:0000626 | 'groin lesion score during treatment' | subclass | is quality measurement of' some (lesioned and 'inheres in' some 'inguinal part of abdomen') |  (edited 'groin' -> 'inguinal part ...')
EUPATH:0000627 | 'groin lesion score after treatment' | subclass | is quality measurement of' some (lesioned and 'inheres in' some 'inguinal part of abdomen') |  (edited 'groin' -> 'inguinal part ...')
EUPATH:0000630 | 'pinna lesion score after treatment' | subclass | is quality measurement of' some (lesioned and 'inheres in' some pinna) |  
EUPATH:0000632 | 'skin lesion duration' | subclass | is duration of' some (('has participant some ('zone of skin' and 'bearer of' some lesioned)) and ('ends during' some 'collecting specimen with swab')) |  
EUPATH:0000633 | 'degree of skin redness' | subclass | is quality measurement of' some Erythema |  
EUPATH:0000634 | 'degree of skin inflammation' | subclass | is quality measurement of' some (area and 'inheres in' some ('zone of skin' and 'bearer of' some 'Inflammatory abnormality of the skin')) |  
EUPATH:0000636 | 'degree of hairloss' | subclass | is quality measurement of' some Alopecia |  
EUPATH:0000638 | 'diagnosis at hospitalization' | subclass | diagnosis and is_specified_input_of some 'admission process' | I have a template for this. This diagnosis determines whether patient needs inpatient care.
EUPATH:0000640 | 'animal cage number for experiment' | subclass | denotes some 'animal cage' |  
EUPATH:0000641 | 'mouse cage number' | subclass | denotes some 'animal cage' |  
EUPATH:0010085 | 'second mid-upper arm circumference datum' | subclass | is quality measurement of' some (length and ('inheres in' some arm)) |  
EUPATH:0010086 | 'third mid-upper arm circumference datum' | subclass | is quality measurement of' some (length and ('inheres in' some arm)) |  
EUPATH:0015120 | 'flaky paint dermatosis information' | equivalent | symptom or sign information' and mentions some 'Flaky paint dermatosis' |  
EUPATH:0015130 | 'diagnosis of diarrhea' | subclass | mentions some diarrhea | Note it's 'diarrhea' the disease, not 'Diarrhea' the abnormality.
EUPATH:0022048 | 'duration of current main occupation' | subclass | is duration of' only (realizes some 'social role') |  
EUPATH:0022049 | 'duration of current secondary occupation' | subclass | is duration of' only (realizes some 'social role') |  last 2 changed to 'is duration of' *only*

Diagnosis template: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/blob/master/src/ontology/axiom_template/diagnosis.csv

**Comment by zhengj2007** [comment]
('is quality measurement of' some area) and ('has measurement unit label' some acre)

Shall use 'only' like:
('is quality measurement of' some area) and ('has measurement unit label' only acre)

**Comment by johnwjudkins** [comment]
Based on Jie's comments, I plan to add 'groin lesion score', 'pinna lesion score', and 'axillary lesion score', defined as "Skin symptom or sign information that is about a lesion on the groin/pinna/axilla of a patient and specifies the extent of damage to the tissue.", with subclass axiom

'is quality measurement of' some (lesioned and 'inheres in' some axilla/'inguinal part of abdomen'/pinna)

**Comment by cstoeckert** [comment]
Sounds good. Is it really 'lesioned" in the axiom or is that a typo for 'lesion'?

**Comment by johnwjudkins** [comment]
"lesioned" is correct - it is a PATO quality referring to the altered condition of the body part.

**Comment by johnwjudkins** [comment]
Update on axioms for diagnosis at discharge and diagnosis at hospitalization:

The admission and discharge processes in OMRSE are document acts; thus they have documents as specified outputs. I also found out through Outreach that:

- the diagnosis at hospitalization is the initial diagnosis which leads to the patient being admitted
- the diagnosis at discharge can be from a diagnostic process at the time of discharge or carried over from a previous diagnostic process

I now propose for 'diagnosis at hospitalization' subclass axiom:
diagnosis and 'part of' some (document and is_specified_output_of some 'admission process')

Similarly for 'diagnosis at discharge' subclass axiom:
diagnosis and 'part of' some (document and is_specified_output_of some 'patient discharge')

(By the way, Ontobee doesn't display these OMRSE processes correctly in the hierarchy at the moment; I suggest viewing in Protégé instead. I've alerted OMRSE to the problem.)

**Comment by cstoeckert** [comment]
An alternate definition for 'diagnosis at hospitalization' might be: a diagnosis that is documented during the admission process.
Likewise for 'diagnosis at discharge' : a diagnosis that is documented during the discharge process.
