### ISSUE TITLE
NTRs for GECKO

### ISSUE THREAD

**Issue by beckyjackson** [VEuPathDB-ontology/VEuPathDB-ontology#84]
We are adding more terms to GECKO, and I came across your "environment associated with human dwelling" class. We have some specifics we'd like to model within this class and I wanted to check if you're interested in adding any of these terms to EUPATH as subclasses of "environment associated with human dwelling" (I'm totally OK with changing the labels, these are just suggestions):

### human dwelling environment
**Definition**: An environment associated with human dwelling that constitutes a human's immediate residence.
### human neighborhood environment
**Definition**: An environment associated with human dwelling that constitutes the immediate social and/or geographical region in which a human resides.
### human workplace environment
**Definition**: An environment associated with human dwelling that constitutes the physical location in which a human works.

---

Additionally, you have a "hospitalization information" class, but no information about routine clinical visits (e.g., annual doctor appointments), so I'd like to request a class for that:

### routine clinical visit information
**Associated axiom**: `'is about' some ('part of' some 'routine clinical visit')`
**Definition**: Information that is about a part of a routine clinical visit.

**Comment by cstoeckert** [comment]
Thanks so much for these requests. We will explore how they relate to our current and expected data variables we have and coordinate with you.

**Comment by zhengj2007** [comment]
Hi @beckyjackson, We discussed the terms you submitted and think the environmental related terms fit EnVO ontology scope and submitted the terms to EnVO including EUPATH term "environment associated with human dwelling" (see issue: https://github.com/EnvironmentOntology/envo/issues/1008).

Could you please add comments to EnVO tracker if you have any? Thanks!

**Comment by beckyjackson** [comment]
Thanks for opening that issue! That looks great to me. I'll close this here.

**Comment by beckyjackson** [comment]
Sorry, I realized that there was one term not addressed here @zhengj2007 @cstoeckert 

## routine clinical visit information
Associated axiom: 'is about' some ('part of' some 'routine clinical visit')
Definition: Information that is about a part of a routine clinical visit.

Is this something that EUPATH would be interested in adding?

**Comment by cstoeckert** [comment]
We are wondering if this would be of general interest and fit in OMRSE along with 'hospitalization information'. We propose checking that out.

**Comment by johnwjudkins** [comment]
https://github.com/OGMS/ogms/issues/146

I requested both 'routine health care encounter' and 'information on part of routine health care encounter' in this item.

**Comment by beckyjackson** [comment]
@cstoeckert @johnwjudkins "routine health care encounter" would be perfect for our use as well. I requested it here because EUPATH has some similar terms, but I'd be happy to use OGMS instead.

**Comment by zhengj2007** [comment]
It seems terms have been add in the OGMS.

@johnwjudkins Shall we close the issue?
