### ISSUE TITLE
NTR: Blood host role

### ISSUE THREAD

**Issue by cstoeckert** [VEuPathDB-ontology/VEuPathDB-ontology#85]
Need a term for referring to species identified as the source of a blood meal for invertebrate vectors. It will be used by VectorBase and listing on MapVeu.

'blood host role' = A role borne by an organism that is gained during a process in which another organism ingests blood as food from the organism. 

example of usage: A mosquito feeds on a human whereby the human acquires the blood host role for the mosquito blood meal.

**Comment by johnwjudkins** [comment]
The only issue I noticed is that the label suggests that this is a ['host role'](http://purl.obolibrary.org/obo/OBI_0000725), and it might not be. The definition is unclear about what it is that's "within the organism"; does it mean that the acquisition of nourishment occurs within the organism, or does it mean that the other organism is inside the host organism?

**Comment by cstoeckert** [comment]
Agreed, it is really a 'blood meal source role' rather than a host.
