### ISSUE TITLE
Deprecate 'educational level information'?

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#87]
The latest OMRSE release has ['highest level of education data item'](http://purl.obolibrary.org/obo/OMRSE_00002045), which seems to be equivalent to our ['educational level information'](http://purl.obolibrary.org/obo/EUPATH_0000345).

**Comment by cstoeckert** [comment]
I agree.

**Comment by zhengj2007** [comment]
+1
