### ISSUE TITLE
ENVO and VEuPath each have their own term for eaves

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#88]
ENVO: A part of a building roof which overhangs the face of a wall and, normally, projects beyond the side of a building.
VEuPath: A processed material that is the bottom edge of a roof. The primary function of the eaves is to keep rain water off the walls and to prevent the ingress of water at the junction where the roof meets the wall. The secondary function is to control solar penetration; the eaves overhang can be designed to adjust the building's solar heat gain to suit the local climate, the latitude and orientation of the building, refer to passive solar building design. The eaves overhang may also shelter openings to ventilate the roof space.

Our definition provides an explanation of the function of eaves (that is lacking in the ENVO definition), but the ENVO definition is correct. Should we deprecate our term?

**Comment by cstoeckert** [comment]
We should go with ENVO.

**Comment by cstoeckert** [comment]
Ask ENVO if they would add the function of eaves.

**Comment by johnwjudkins** [comment]
https://github.com/EnvironmentOntology/envo/issues/1013
