### ISSUE TITLE
dyspepsia is deprecated

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#89]
Dyspepsia is deprecated in DOID. We could import it from HP, but do we still need it? I don't see a dyspepsia/ indigestion/upset stomach term in any of the projects.

**Comment by zhengj2007** [comment]
For PRISM project we started in 2014, many disease terms were imported into VEuPathDB ontology. However, some of these terms are not required to be ontology terms or ignored in clinEpi database now. So, I think we can remove the term and import appropriate ontology term if we need in the future.
