### ISSUE TITLE
'environmental feature' deprecated - affects VEuPath terms

### ISSUE THREAD

**Issue by johnwjudkins** [VEuPathDB-ontology/VEuPathDB-ontology#90]
ENVO has deprecated 'environmental feature', which is parent to 'garbage disposal' and 'human waste disposal'. I think the simplest solution is to make these terms children of 'material entity', which includes changing the parent mentioned in the definitions. Accordingly, we could also remove the reference to environmental feature' from the definition and axiom for 'environment information'. Are there any alternative or additional steps we should take based on this change?

**Comment by cstoeckert** [comment]
Need to look at values and determine what exactly these refer to (site, device, process?)

**Comment by johnwjudkins** [comment]
In ClinEpi, 'Child waste disposal' ('human child waste disposal' here) is associated with answers to questions of both how (process) and where (site) child feces are disposed of. I propose changing this term and its parent to ICEs.

**Comment by johnwjudkins** [comment]
That leaves EUPATH:0000368 'garbage disposal', defined as "An environmental feature for disposing garbage" ClinEpi values are 1-Bury, 2-Burn, 3-Left in an open area, 4-Left in an open trench, 5-Bury and burn. These are processes. We could substitute this with 'waste disposal process' (ENVO:01001260). This is defined as "a process during which materials deemed to be waste are transported away from a site", and I think some kind of transportation is involved even in just burning the garbage.

**Comment by zhengj2007** [comment]
See related discussion on: https://github.com/EnvironmentOntology/envo/issues/981
