### ISSUE TITLE
Request import terms for MicrobiomeDB

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#92]
http://purl.obolibrary.org/obo/NCIT_C13195
bronchoalveolar lavage fluid
(specimen)

http://purl.obolibrary.org/obo/CMO_0000254
forced expiratory volume
(measurement datum)

http://purl.obolibrary.org/obo/HP_0032319
Health status
(phenotype?)

**Comment by johnwjudkins** [comment]
I think http://purl.obolibrary.org/obo/OBI_0100067 refers to the same thing as NCIT_C13195.

HP_0032319 looks like a clinical data item that is part of a clinical history.

**Comment by zhengj2007** [comment]
OBI_0100067 bronchial alveolar lavage looks good. 

It's good to import 'Health status' under clinical history.

**Comment by johnwjudkins** [comment]
I'll include these in the release candidate.
