### ISSUE TITLE
Imported IAO annotation terms with multiple labels or definitions

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#93]
IAO_0000111 
editor preferred label: specified in VEuPathDB, imported from some OBO ontology (import_OBO.owl) [old label, should be removed]
editor preferred term: all other resources [correct label]
**Notes:** we should remove the label of IAO_0000111 specified in eupath_dev.owl

IAO_0000115
textual definition:  imported from some OBO ontologies (import_OBO.owl) [old label, should be removed]
definition: all other resources [correct label]

IAO_0000117
definition editor: imported from some OBO ontologies (import_OBO.owl) [old label, should be removed]
term editor: all other resources [correct label]

Suggestions: manually remove the wrong labels in the eupath.owl (release candidate) to prevent error propagation.

**Comment by zhengj2007** [comment]
Following terms with multiple definitions:
IAO:0100001 term replaced by
Definitions:
- Add as annotation triples in the granting ontology@en
- Use on obsolete terms, relating the term to another term that can be used as a substitute (correct one)

IAO:0000115 definition
Definitions:
- A property representing the English language definitions of what NCI means by the concept. They may also include information about the definition's source and attribution in a form that can easily be interpreted by software.
- English language definitions of what NCI means by the concept. These are limited to 1024 characters. They may also include information about the definition's source and attribution in a form that can easily be interpreted by software.
- The official OBI definition, explaining the meaning of a class or property. Shall be Aristotelian, formalized and normalized. Can be augmented with colloquial definitions.@en
- The official definition, explaining the meaning of a class or property. Shall be Aristotelian, formalized and normalized. Can be augmented with colloquial definitions. (correct one)

IAO:0000119 definition source
Definitions:
- Formal citation, e.g.   identifier in external database to indicate / attribute source(s) for the   definition. Free text indicate / attribute source(s) for the definition.   EXAMPLE: Author Name, URI, MeSH Term C04, PUBMED ID, Wiki uri on   31.01.2007@en (minor edits)
- formal citation, e.g. identifier in   external database to indicate / attribute source(s) for the definition. Free   text indicate / attribute source(s) for the definition. EXAMPLE: Author Name,   URI, MeSH Term C04, PUBMED ID, Wiki uri on 31.01.2007@en (correct one)

Consider to fix the issues in the future.

**Comment by johnwjudkins** [comment]
I edited import_OBO.owl, so these will be fixed when I run "make" again. I also left comments in input_OBO.txt to remove these annotations whenever import_OBO.owl is remade.

**Comment by zhengj2007** [comment]
Issues still found in the release candidate. How about fix it by manually removing the wrong label the release file?
