### ISSUE TITLE
Imported terms with multiple definitions due to import from different ontology release versions

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#94]
VEuPathDB was built on NIAID-GSC-BRC.owl. We have asked OBI to build the NIAID-GSC-BRC view on each release. Current version used in VEuPathDB is made on 2020-04-09. However, OBI made the release on 2020-08-24 without making the NIAID-GSC-BRC view. It caused following terms with multiple definitions due to definition updated in latest release.
- ENVO:00010483 environmental material
- IAO:0000027 data item
- IAO:0000032 scalar measurement datum
- IAO:0000115 definition
- IAO:0000119 definition source
- IAO:0000121 organizational term
- IAO:0000136 is about
- IAO:0000219 denotes
- IAO:0000221 is quality measurement of

NIAID-GSC-BRC.owl contains terms from multiple ontologies including OBI. It means even we keep NIAID-GSC-BRC.owl with OBI release. It could still have problem if IAO, ENVO or other OBO Foundry ontology terms made updates and release before OBI NIAID-GSC-BRC view release. 

We need to think about how to deal with it.

**Comment by johnwjudkins** [comment]
They did update NIAID-GSC-BRC, but they did not update the PURL. (eupath_dev imports NIAID-GSC-BRC based on the PURL.)

**Comment by zhengj2007** [comment]
All other issues still occur in VEuPathDB release candidate due to terms imported from multiple resources. Are we planning to fix the issues before next release?

**Comment by johnwjudkins** [comment]
I downloaded eupath.owl from the release page just now. ENVO:00010483 has only one definition (with "fiat object part").
