### ISSUE TITLE
two terms with same definition

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#96]
EUPATH:0000787 groin lesion score
EUPATH:0000788 axillary lesion score
definition: skin symptom or sign information that is about a lesion on the groin of a patient and specifies the extent of damage to the tissue

(Note: the definition better starts with upper case)

**Comment by johnwjudkins** [comment]
I will fix that and the pinna lesion score definition.
