### ISSUE TITLE
NTR protein variant prevalence terms

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#97]
For each new variant (e.g. Kdr L1014F) and wild type (e.g. Kdr L1014) positional term X being developed in the protein ontology, we will need a "prevalence of X" term too, to use as a variable in the vector popbio data.

**Comment by cstoeckert** [comment]
Is this for prevalence in a sample? Do you need terms for both variant and wild type (i.e., will the column header and values just be for the variant? Or will you have a separate column for each?)

**Comment by cstoeckert** [comment]
Could do subtraction but would aid searches to have both. Also there may be more than one variant type at the same site. Need to make sure that wild type amount is assayed and not inferred.

**Comment by cstoeckert** [comment]
Probably a mix of both. Need to look through datasets for examples. 
Prevalence of wild type defined as being assayed or inferred.

**Comment by cstoeckert** [comment]
How is this?
‘prevalence of Kdr L1014F’: A data item that is the output of an assay to quantify the frequency of genetic variation resulting in the Kdr L1014F protein.’ 
logical definition: ‘data item’  and ‘is about’ some ‘Kdr L1014’ 

If this pattern is OK we can apply to others.

**Comment by cstoeckert** [comment]
Prevalence of wild type defined as being assayed or inferred - seems to be inferred but will define as possibly either. 

Pattern in last comment is approved.

**Comment by cstoeckert** [comment]
We will create the following prevalence terms using the pattern: 
‘prevalence of [protein variant]': A data item that is the output of an assay to quantify the frequency of genetic variation resulting in the [protein variant].
- logical definition: ‘data item’ and ‘is about’ some [protein variant]
where [protein variant] is:
prevalence of Kdr L1014F
prevalence of Kdr S989P
prevalence of Kdr I1011M
prevalence of Kdr I1011V
prevalence of Kdr L1014S
prevalence of Kdr L1014C
prevalence of Kdr V1016G
prevalence of Kdr V1016I
prevalence of Kdr I1532T
prevalence of Kdr F1534C
prevalence of Kdr F1534L
prevalence of Kdr F1534S
prevalence of Kdr N1575Y
prevalence of Kdr D1763Y
prevalence of AChE1 G119S
prevalence of AChE1 F290V
prevalence of AChE1 F331W
prevalence of Gste2 I114T
prevalence of Gste2 L119F
prevalence of Rdl A296G
prevalence of Rdl A296S

**Comment by cstoeckert** [comment]
We will create the following prevalence terms using the pattern:
‘prevalence of wild type [protein position]': A data item that is the output of an assay to quantify the frequency of the reference sequence amino acid at [protein position] or is calculated from data items of the frequency of a variant at that position.

    logical definition: ‘data item’ and ‘is about’ some [reference protein]
    where [protein position] and [reference protein] is:
Kdr L1014 PR:000050403
Kdr S989 PR:000050403
Kdr I1011 PR:000050403
Kdr V1016 PR:000050403
Kdr I1532 PR:000050403
Kdr F1534 PR:000050403
Kdr N1575 PR:000050403
Kdr D1763 PR:000050403
AChE1 G119 PR:000050402
AChE1 F290 PR:000050402
AChE1 F331 PR:000050402
Gste2 I114 PR:000050443
Gste2 L119 PR:000050443
Rdl A296 PR:000050413

**Comment by bobular** [comment]
https://proconsortium.org/ PR ontology browser for reference

**Comment by cstoeckert** [comment]
I'll provide PR IDs for the protein variants.

**Comment by cstoeckert** [comment]
Kdr L1014F PR:000050450
Kdr S989P PR:000050416
Kdr I1011M PR:000050414
Kdr I1011V PR:000050415
Kdr L1014S PR:000050417
Kdr L1014C PR:000050449
Kdr V1016G PR:000050412
Kdr V1016I PR:000050431
Kdr I1532T PR:000050418
Kdr F1534C PR:000050419
Kdr F1534L PR:000050426
Kdr F1534S PR:000050427
Kdr N1575Y PR:000050428
Kdr D1763Y PR:000050429
AChE1 G119S PR:000050435
AChE1 F290V PR:000050436
AChE1 F331W PR:000050437
Gste2 I114T PR:000050446
Gste2 L119F PR:000050447
Rdl A296G PR:000050439
Rdl A296S PR:000050440

**Comment by bobular** [comment]
The list above covers everything currently in qa.vectorbase.org popbio map genotype view, **and more**.  (Which is a good thing.)

We don't have data for 
 AChE1 F290V PR:000050436
 AChE1 F331W PR:000050437
 Gste2 I114T PR:000050446

but it's no problem at all to have them in the ontology.  Where did they come from, out of interest?

**Comment by cstoeckert** [comment]
Leave these out for now from prevalence template

**Comment by bobular** [comment]
Thanks for remembering the wild type prevalence terms :-)

**Comment by bobular** [comment]
Hi John - in your last commit I think the trailing 'P' is erroneous?

EUPATH:0043191,prevalence of wild type Rdl A296P

**Comment by johnwjudkins** [comment]
Yes @bobular it's fixed.

**Comment by johnwjudkins** [comment]
In latest release; closing.
