### ISSUE TITLE
NTR: device used for arthropod/insect/whatever collection (variable)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB-ontology/VEuPathDB-ontology#98]
Hi all,
The old VB ontology terms for the collection protocol were a bit of a mess/mix of protocols and devices.
We're separating out the device into a separate variable and we'll need an ontology term for the variable.
Ping me by Slack if you need any further info.
thanks

**Comment by cstoeckert** [comment]
Will the general 'device' term http://purl.obolibrary.org/obo/OBI_0000968 work?
That's the parent we use in VEuPathDB ontology for 'arthropod trap', 'hand-held sweep net',
'dipper for arthropod immatures' and 'device for resting of adult arthropods for collection'.

**Comment by cstoeckert** [comment]
Go with general device for now until differentia are needed.
