### ISSUE TITLE
NTR: case type

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB-ontology/VEuPathDB-ontology#99]
I am unsure exactly what to call the term but I would like a term that would be used for 'case type' this would be used for COVID data for us to describe whether the data is deaths, symptoms or any other disease outcome.  It is not the outcome of a treatment, as we do not know if all patients have been treated as such.

**Comment by cstoeckert** [comment]
We think this might be an 'information' type class (maybe like diagnosis) for characterizing what the count is about.

**Comment by cstoeckert** [comment]
In addition to death there will be counts of cases for different symptoms, positive tests.

**Comment by cstoeckert** [comment]
All of these are clinically related (even home isolation since it is for health reasons). How about using 'clinical finding' http://purl.obolibrary.org/obo/OGMS_0000014 which we use in VEuPathDB?

**Comment by SAK22** [comment]
To me this looks good! So use clinical finding for all of them? Or add these terms under that?

**Comment by cstoeckert** [comment]
I was thinking that the column header would be 'clinical finding' with values such as 'death confirmed likely from covid-19' and paired with the column 'count' with values some integer.
